#!/usr/bin/env python3
"""
本地词典翻译：将英文知识点名称翻译为中文
不依赖外部 API，使用内置术语词典 + 组合规则
"""

import json
import re
from pathlib import Path

TREES_DIR = Path(__file__).parent.parent / "data" / "trees" / "cn-unified"
MAP_DATA = Path(__file__).parent.parent / "data" / "knowledge-map-data.json"

# ─── 核心术语词典 ─────────────────────────────────────────
# 覆盖学术/工程/计算机/数学/物理/化学/生物/地球科学领域
DICT = {
    # ── 通用学术词 ──
    "introduction": "导论", "intro": "入门", "basics": "基础", "fundamentals": "基础",
    "overview": "概述", "definition": "定义", "concepts": "概念", "concept": "概念",
    "principles": "原理", "principle": "原理", "theory": "理论", "theorem": "定理",
    "law": "定律", "laws": "定律", "rule": "规则", "rules": "规则",
    "model": "模型", "models": "模型", "method": "方法", "methods": "方法",
    "technique": "技术", "techniques": "技术", "approach": "方法", "approaches": "方法",
    "analysis": "分析", "design": "设计", "synthesis": "合成", "classification": "分类",
    "applications": "应用", "application": "应用", "properties": "性质", "property": "性质",
    "structure": "结构", "structures": "结构", "mechanism": "机制", "mechanisms": "机制",
    "process": "过程", "processes": "过程", "types": "类型", "type": "类型",
    "characteristics": "特征", "features": "特征", "comparison": "比较",
    "advanced": "高级", "basic": "基本", "general": "一般", "special": "特殊",
    "modern": "现代", "classical": "经典", "abstract": "抽象", "applied": "应用",
    "computational": "计算", "numerical": "数值", "theoretical": "理论",
    "experimental": "实验", "practical": "实践", "formal": "形式",
    "first": "第一", "second": "第二", "third": "第三", "higher": "高阶",
    "selection": "选择", "optimization": "优化", "evaluation": "评估",
    "test": "检验", "testing": "测试", "verification": "验证",

    # ── 数学 ──
    "algebra": "代数", "algebraic": "代数", "geometry": "几何", "geometric": "几何",
    "topology": "拓扑", "topological": "拓扑", "calculus": "微积分",
    "arithmetic": "算术", "number": "数", "numbers": "数",
    "equation": "方程", "equations": "方程", "inequality": "不等式",
    "function": "函数", "functions": "函数", "variable": "变量", "variables": "变量",
    "polynomial": "多项式", "matrix": "矩阵", "matrices": "矩阵",
    "vector": "向量", "vectors": "向量", "tensor": "张量", "tensors": "张量",
    "scalar": "标量", "determinant": "行列式", "eigenvalue": "特征值",
    "eigenvector": "特征向量", "eigenvalues": "特征值",
    "linear": "线性", "nonlinear": "非线性", "multilinear": "多线性",
    "differential": "微分", "integral": "积分", "integrals": "积分",
    "derivative": "导数", "derivatives": "导数", "gradient": "梯度",
    "limit": "极限", "limits": "极限", "continuity": "连续性", "continuous": "连续",
    "convergence": "收敛", "divergence": "散度", "series": "级数",
    "sequence": "序列", "sequences": "序列", "sum": "和", "summation": "求和",
    "infinite": "无穷", "finite": "有限", "countable": "可数",
    "set": "集合", "sets": "集合", "subset": "子集", "group": "群",
    "groups": "群", "ring": "环", "rings": "环", "field": "域",
    "fields": "域", "space": "空间", "spaces": "空间",
    "subspace": "子空间", "subgroup": "子群", "quotient": "商",
    "homomorphism": "同态", "isomorphism": "同构", "automorphism": "自同构",
    "morphism": "态射", "functor": "函子", "category": "范畴", "categories": "范畴",
    "mapping": "映射", "transformation": "变换", "operator": "算子", "operators": "算子",
    "projection": "投影", "embedding": "嵌入", "extension": "扩展",
    "dimension": "维数", "dimensional": "维", "rank": "秩",
    "norm": "范数", "metric": "度量", "measure": "测度", "measures": "测度",
    "probability": "概率", "statistics": "统计", "statistical": "统计",
    "distribution": "分布", "random": "随机", "stochastic": "随机",
    "expectation": "期望", "variance": "方差", "correlation": "相关",
    "regression": "回归", "estimation": "估计", "hypothesis": "假设",
    "sampling": "抽样", "bayesian": "贝叶斯", "inference": "推断",
    "combinatorics": "组合", "combinatorial": "组合", "permutation": "排列",
    "graph": "图", "graphs": "图", "tree": "树", "trees": "树",
    "path": "路径", "cycle": "环/循环", "node": "节点", "edge": "边",
    "vertex": "顶点", "network": "网络", "networks": "网络",
    "logic": "逻辑", "logical": "逻辑", "boolean": "布尔",
    "predicate": "谓词", "proposition": "命题", "proof": "证明", "proofs": "证明",
    "induction": "归纳", "recursion": "递归", "recursive": "递归",
    "iteration": "迭代", "iterative": "迭代",
    "partial": "偏", "ordinary": "常", "order": "阶",
    "boundary": "边界", "initial": "初始", "condition": "条件", "conditions": "条件",
    "solution": "解", "solutions": "解", "existence": "存在性", "uniqueness": "唯一性",
    "stability": "稳定性", "stable": "稳定", "unstable": "不稳定",
    "approximation": "近似", "interpolation": "插值", "extrapolation": "外推",
    "fourier": "傅里叶", "laplace": "拉普拉斯", "taylor": "泰勒",
    "euler": "欧拉", "gauss": "高斯", "riemann": "黎曼",
    "hilbert": "希尔伯特", "banach": "巴拿赫", "cauchy": "柯西",
    "lebesgue": "勒贝格", "borel": "博雷尔", "hausdorff": "豪斯多夫",
    "galois": "伽罗瓦", "abel": "阿贝尔", "abelian": "阿贝尔",
    "sylow": "西罗", "noether": "诺特", "lagrange": "拉格朗日",
    "hamilton": "哈密顿", "hamiltonian": "哈密顿", "jacobi": "雅可比",
    "jacobian": "雅可比", "hessian": "海森", "wronskian": "朗斯基",
    "manifold": "流形", "manifolds": "流形", "surface": "曲面", "surfaces": "曲面",
    "curve": "曲线", "curves": "曲线", "curvature": "曲率",
    "compact": "紧", "compactness": "紧性", "connected": "连通",
    "open": "开", "closed": "闭", "dense": "稠密", "complete": "完备",
    "separable": "可分", "metrizable": "可度量化",
    "homotopy": "同伦", "homology": "同调", "cohomology": "上同调",
    "sheaf": "层", "bundle": "丛", "fiber": "纤维",
    "ideal": "理想", "module": "模", "modules": "模",
    "representation": "表示", "representations": "表示",
    "symmetry": "对称", "symmetric": "对称", "antisymmetric": "反对称",
    "dual": "对偶", "duality": "对偶性", "conjugate": "共轭",
    "complex": "复", "real": "实", "rational": "有理", "irrational": "无理",
    "integer": "整数", "integers": "整数", "prime": "素数", "primes": "素数",
    "divisibility": "整除性", "congruence": "同余", "modular": "模",
    "factorization": "因式分解", "decomposition": "分解",
    "maximum": "最大值", "minimum": "最小值", "extrema": "极值",
    "supremum": "上确界", "infimum": "下确界",
    "monotone": "单调", "convex": "凸", "concave": "凹",

    # ── 物理 ──
    "physics": "物理", "physical": "物理", "mechanics": "力学", "mechanical": "力学",
    "dynamics": "动力学", "dynamic": "动态", "kinematics": "运动学",
    "statics": "静力学", "motion": "运动", "velocity": "速度", "acceleration": "加速度",
    "force": "力", "forces": "力", "momentum": "动量", "impulse": "冲量",
    "energy": "能量", "power": "功率", "work": "功", "torque": "力矩",
    "mass": "质量", "weight": "重力", "gravity": "引力", "gravitational": "引力",
    "pressure": "压强", "density": "密度", "volume": "体积",
    "friction": "摩擦", "elasticity": "弹性", "elastic": "弹性",
    "oscillation": "振荡", "oscillations": "振荡", "vibration": "振动",
    "wave": "波", "waves": "波", "frequency": "频率", "wavelength": "波长",
    "amplitude": "振幅", "resonance": "共振", "interference": "干涉",
    "diffraction": "衍射", "reflection": "反射", "refraction": "折射",
    "optics": "光学", "optical": "光学", "light": "光", "photon": "光子", "photons": "光子",
    "laser": "激光", "spectrum": "光谱", "spectroscopy": "光谱学",
    "electromagnetic": "电磁", "electromagnetism": "电磁学",
    "electric": "电", "electrical": "电", "magnetic": "磁", "magnetism": "磁学",
    "current": "电流", "voltage": "电压", "resistance": "电阻",
    "capacitance": "电容", "capacitor": "电容器", "inductance": "电感",
    "circuit": "电路", "circuits": "电路", "diode": "二极管", "transistor": "晶体管",
    "semiconductor": "半导体", "conductor": "导体", "insulator": "绝缘体",
    "charge": "电荷", "electron": "电子", "electrons": "电子",
    "proton": "质子", "neutron": "中子", "nucleus": "原子核", "nuclear": "核",
    "atom": "原子", "atomic": "原子", "atoms": "原子",
    "molecule": "分子", "molecular": "分子", "molecules": "分子",
    "ion": "离子", "ions": "离子", "ionic": "离子",
    "particle": "粒子", "particles": "粒子", "quantum": "量子",
    "spin": "自旋", "orbit": "轨道", "orbital": "轨道",
    "thermodynamics": "热力学", "thermodynamic": "热力学",
    "temperature": "温度", "heat": "热", "thermal": "热",
    "entropy": "熵", "enthalpy": "焓", "gibbs": "吉布斯",
    "boltzmann": "玻尔兹曼", "maxwell": "麦克斯韦", "planck": "普朗克",
    "schrodinger": "薛定谔", "heisenberg": "海森堡", "dirac": "狄拉克",
    "einstein": "爱因斯坦", "newton": "牛顿", "newtonian": "牛顿",
    "relativity": "相对论", "relativistic": "相对论",
    "fluid": "流体", "fluids": "流体", "flow": "流动", "turbulence": "湍流",
    "turbulent": "湍流", "laminar": "层流", "viscosity": "粘度", "viscous": "粘性",
    "aerodynamics": "空气动力学", "hydrodynamics": "水动力学",
    "plasma": "等离子体", "gas": "气体", "liquid": "液体", "solid": "固体",
    "crystal": "晶体", "crystalline": "晶体", "crystallography": "晶体学",
    "condensed": "凝聚态", "superconductor": "超导体", "superconductivity": "超导",
    "magnetization": "磁化", "polarization": "极化", "ferromagnetic": "铁磁",
    "acoustic": "声学", "acoustics": "声学", "sound": "声",
    "radiation": "辐射", "radioactive": "放射性", "decay": "衰变",
    "fission": "裂变", "fusion": "聚变", "reactor": "反应堆",
    "isotope": "同位素", "isotopes": "同位素",
    "field": "场", "potential": "势", "flux": "通量",
    "inertia": "惯性", "angular": "角", "rotation": "旋转", "rotational": "转动",
    "collision": "碰撞", "scattering": "散射", "absorption": "吸收",
    "emission": "发射", "excitation": "激发", "ionization": "电离",
    "transition": "跃迁", "transitions": "跃迁",
    "band": "能带", "bands": "能带", "gap": "能隙",
    "lattice": "晶格", "phonon": "声子", "phonons": "声子",

    # ── 化学 ──
    "chemistry": "化学", "chemical": "化学", "organic": "有机", "inorganic": "无机",
    "biochemistry": "生物化学", "biochemical": "生化",
    "reaction": "反应", "reactions": "反应", "reactivity": "反应性",
    "catalyst": "催化剂", "catalysis": "催化", "catalytic": "催化",
    "enzyme": "酶", "enzymes": "酶", "enzymatic": "酶促",
    "kinetics": "动力学", "kinetic": "动力学", "equilibrium": "平衡",
    "thermochemistry": "热化学", "electrochemistry": "电化学",
    "oxidation": "氧化", "reduction": "还原", "redox": "氧化还原",
    "acid": "酸", "base": "碱", "salt": "盐", "buffer": "缓冲",
    "solvent": "溶剂", "solute": "溶质", "solution": "溶液/解",
    "concentration": "浓度", "dilution": "稀释", "titration": "滴定",
    "bond": "键", "bonds": "键", "bonding": "成键", "covalent": "共价",
    "hydrogen": "氢", "oxygen": "氧", "nitrogen": "氮", "carbon": "碳",
    "sulfur": "硫", "phosphorus": "磷", "chlorine": "氯", "fluorine": "氟",
    "metal": "金属", "metals": "金属", "metallic": "金属",
    "polymer": "聚合物", "polymers": "聚合物", "polymerization": "聚合",
    "monomer": "单体", "monomers": "单体",
    "isomer": "异构体", "isomers": "异构体", "isomerism": "异构",
    "stereochemistry": "立体化学", "chirality": "手性",
    "functional": "官能团", "alkane": "烷烃", "alkene": "烯烃", "alkyne": "炔烃",
    "aromatic": "芳香", "benzene": "苯", "alcohol": "醇", "aldehyde": "醛",
    "ketone": "酮", "ether": "醚", "ester": "酯", "amide": "酰胺",
    "amine": "胺", "amino": "氨基", "carboxyl": "羧基",
    "synthesis": "合成", "decomposition": "分解", "substitution": "取代",
    "addition": "加成", "elimination": "消除", "condensation": "缩合",
    "hydrolysis": "水解", "hydrogenation": "加氢", "dehydration": "脱水",
    "precipitation": "沉淀", "dissolution": "溶解", "evaporation": "蒸发",
    "distillation": "蒸馏", "chromatography": "色谱", "electrolysis": "电解",
    "stoichiometry": "化学计量", "molar": "摩尔", "mole": "摩尔",
    "valence": "化合价", "oxidation": "氧化",
    "periodic": "周期", "element": "元素", "elements": "元素",
    "compound": "化合物", "compounds": "化合物", "mixture": "混合物",
    "crystal": "晶体", "amorphous": "非晶",
    "spectral": "光谱", "nmr": "核磁共振", "infrared": "红外", "ultraviolet": "紫外",
    "cholesterol": "胆固醇", "lipid": "脂质", "lipids": "脂质",
    "fatty": "脂肪", "glycolysis": "糖酵解", "gluconeogenesis": "糖异生",
    "citric": "柠檬酸", "krebs": "克雷布斯",
    "metabolism": "代谢", "metabolic": "代谢", "catabolism": "分解代谢",
    "anabolism": "合成代谢", "biosynthesis": "生物合成",

    # ── 生物 ──
    "biology": "生物学", "biological": "生物", "cell": "细胞", "cells": "细胞",
    "cellular": "细胞", "membrane": "膜", "membranes": "膜",
    "protein": "蛋白质", "proteins": "蛋白质", "peptide": "肽",
    "dna": "DNA", "rna": "RNA", "gene": "基因", "genes": "基因",
    "genetic": "遗传", "genetics": "遗传学", "genomic": "基因组", "genome": "基因组",
    "chromosome": "染色体", "chromosomes": "染色体",
    "mutation": "突变", "mutations": "突变", "expression": "表达",
    "transcription": "转录", "translation": "翻译", "replication": "复制",
    "mitosis": "有丝分裂", "meiosis": "减数分裂",
    "photosynthesis": "光合作用", "respiration": "呼吸", "fermentation": "发酵",
    "evolution": "进化", "evolutionary": "进化", "natural": "自然",
    "species": "物种", "population": "种群", "community": "群落",
    "ecosystem": "生态系统", "ecology": "生态学", "ecological": "生态",
    "organism": "生物体", "organisms": "生物体",
    "tissue": "组织", "tissues": "组织", "organ": "器官", "organs": "器官",
    "nervous": "神经", "neural": "神经", "neuron": "神经元", "neurons": "神经元",
    "brain": "大脑", "synapse": "突触", "synaptic": "突触",
    "immune": "免疫", "immunity": "免疫", "antibody": "抗体", "antigen": "抗原",
    "virus": "病毒", "viral": "病毒", "bacteria": "细菌", "bacterial": "细菌",
    "infection": "感染", "pathogen": "病原体", "disease": "疾病",
    "hormone": "激素", "hormones": "激素", "endocrine": "内分泌",
    "signaling": "信号传导", "signal": "信号", "receptor": "受体", "receptors": "受体",
    "pathway": "通路", "pathways": "通路", "cascade": "级联",
    "apoptosis": "凋亡", "necrosis": "坏死", "autophagy": "自噬",
    "stem": "干细胞", "differentiation": "分化",
    "amino": "氨基", "nucleotide": "核苷酸", "nucleotides": "核苷酸",
    "codon": "密码子", "anticodon": "反密码子",
    "polymerase": "聚合酶", "ligase": "连接酶", "kinase": "激酶",
    "phosphorylation": "磷酸化", "glycosylation": "糖基化",
    "atp": "ATP", "adp": "ADP", "nad": "NAD", "nadh": "NADH",
    "mitochondria": "线粒体", "chloroplast": "叶绿体",
    "ribosome": "核糖体", "ribosomes": "核糖体",
    "cytoplasm": "细胞质", "cytoskeleton": "细胞骨架",
    "endoplasmic": "内质网", "golgi": "高尔基体",
    "lysosome": "溶酶体", "vacuole": "液泡", "vesicle": "囊泡",
    "homeostasis": "稳态", "regulation": "调控", "feedback": "反馈",
    "inhibition": "抑制", "activation": "激活", "stimulation": "刺激",
    "substrate": "底物", "product": "产物", "cofactor": "辅因子",
    "allosteric": "变构", "competitive": "竞争性", "noncompetitive": "非竞争性",
    "specificity": "特异性", "affinity": "亲和力", "binding": "结合",
    "transport": "转运", "diffusion": "扩散", "osmosis": "渗透",
    "active": "主动", "passive": "被动", "channel": "通道",
    "carbohydrate": "碳水化合物", "glucose": "葡萄糖", "sucrose": "蔗糖",
    "starch": "淀粉", "cellulose": "纤维素",
    "photosystem": "光系统", "pigment": "色素", "chlorophyll": "叶绿素",
    "nitrogen": "氮", "fixation": "固定", "cycle": "循环",
    "food": "食物", "chain": "链", "web": "网",
    "biodiversity": "生物多样性", "conservation": "保护",
    "adaptation": "适应", "selection": "选择", "speciation": "物种形成",
    "phylogenetic": "系统发育", "taxonomy": "分类学",
    "plant": "植物", "animal": "动物", "fungus": "真菌", "fungi": "真菌",
    "prokaryote": "原核生物", "eukaryote": "真核生物",
    "vertebrate": "脊椎动物", "invertebrate": "无脊椎动物",
    "mammal": "哺乳动物", "reptile": "爬行动物",
    "seed": "种子", "root": "根", "leaf": "叶", "flower": "花", "fruit": "果实",
    "germination": "萌发", "pollination": "授粉",
    "digestion": "消化", "absorption": "吸收", "excretion": "排泄",
    "circulation": "循环", "blood": "血液", "heart": "心脏",
    "lung": "肺", "kidney": "肾", "liver": "肝",
    "muscle": "肌肉", "bone": "骨骼", "skeletal": "骨骼",
    "reproduction": "生殖", "sexual": "有性", "asexual": "无性",
    "embryo": "胚胎", "development": "发育", "developmental": "发育",
    "aging": "衰老", "growth": "生长",
    "behavior": "行为", "behavioral": "行为", "cognition": "认知",
    "learning": "学习", "memory": "记忆",
    "sensory": "感觉", "vision": "视觉", "hearing": "听觉",
    "degradation": "降解", "ammonia": "氨", "synthase": "合酶", "synthetase": "合成酶",
    "aminoacyl": "氨酰", "trna": "tRNA", "mrna": "mRNA",
    "branched": "支链", "disaccharides": "二糖", "polysaccharides": "多糖",
    "monosaccharides": "单糖", "saccharide": "糖", "saccharides": "糖",
    "hydrolysis": "水解", "hydrolyze": "水解",
    "oxidative": "氧化", "deamination": "脱氨", "transamination": "转氨",
    "post": "翻译后", "translational": "翻译",
    "centrosome": "中心体", "centrosomes": "中心体",
    "microtubule": "微管", "microtubules": "微管",
    "cytokinesis": "胞质分裂", "spindle": "纺锤体",
    "checkpoint": "检查点", "histone": "组蛋白", "histones": "组蛋白",
    "acetylation": "乙酰化", "methylation": "甲基化",
    "epigenetic": "表观遗传", "epigenetics": "表观遗传学",
    "meiotic": "减数分裂", "mitotic": "有丝分裂",
    "recombination": "重组", "crossing": "交叉", "crossover": "交换",
    "homolog": "同源", "homologous": "同源", "pairing": "配对",
    "synapsis": "联会", "prophase": "前期",
    "proteasomal": "蛋白酶体", "proteasome": "蛋白酶体",
    "ubiquitin": "泛素", "ubiquitination": "泛素化",
    "marking": "标记", "editing": "编辑",
    "modification": "修饰", "modifications": "修饰",
    "fertilization": "受精", "cleavage": "卵裂",
    "gastrulation": "原肠化", "neurulation": "神经管形成",
    "morphogen": "形态发生素", "gradients": "梯度",
    "pluripotency": "多能性", "reprogramming": "重编程",
    "evo": "进化发育", "devo": "生物学",
    "proofreading": "校读", "fidelity": "保真度",
    "reticulum": "网", "spliceosome": "剪接体",
    "splicing": "剪接", "intron": "内含子", "exon": "外显子",
    "promoter": "启动子", "enhancer": "增强子", "silencer": "沉默子",
    "telomere": "端粒", "telomerase": "端粒酶",
    "chromatin": "染色质", "nucleosome": "核小体",
    "polyploidy": "多倍体", "aneuploidy": "非整倍体",
    "translocation": "易位", "deletion": "缺失", "insertion": "插入",
    "inversion": "倒位", "duplication": "重复",
    "operon": "操纵子", "repressor": "阻遏物",
    "plasmid": "质粒", "vector": "载体",
    "pcr": "PCR", "electrophoresis": "电泳", "blotting": "印迹",
    "sequencing": "测序", "cloning": "克隆",
    "crispr": "CRISPR", "cas": "Cas",
    "bioethics": "生物伦理", "bioinformatics": "生物信息学",
    "proteomics": "蛋白质组学", "genomics": "基因组学",
    "metabolomics": "代谢组学", "transcriptomics": "转录组学",
    "microbiome": "微生物组", "metagenomics": "宏基因组学",
    "symbiosis": "共生", "parasitism": "寄生", "mutualism": "互利共生",
    "predation": "捕食", "competition": "竞争",
    "succession": "演替", "climax": "顶极",
    "biome": "生物群落", "tundra": "冻原", "taiga": "针叶林",
    "savanna": "稀树草原", "tropical": "热带", "temperate": "温带",
    "habitat": "栖息地", "niche": "生态位",
    "migration": "迁移", "hibernation": "冬眠",
    "camouflage": "伪装", "mimicry": "拟态",
    "phenotype": "表现型", "genotype": "基因型",
    "allele": "等位基因", "alleles": "等位基因",
    "dominant": "显性", "recessive": "隐性",
    "heterozygous": "杂合", "homozygous": "纯合",
    "linkage": "连锁", "epistasis": "上位",
    "pleiotropy": "一因多效", "polygenic": "多基因",
    "pedigree": "系谱", "karyotype": "核型",
    "haploid": "单倍体", "diploid": "二倍体",
    "zygote": "受精卵", "gamete": "配子", "gametes": "配子",
    "ovum": "卵", "sperm": "精子", "pollen": "花粉",
    "embryonic": "胚胎", "fetal": "胎儿", "neonatal": "新生儿",
    "morphogenesis": "形态发生", "organogenesis": "器官发生",
    "totipotent": "全能", "multipotent": "多能",
    "apical": "顶端", "meristem": "分生组织",
    "xylem": "木质部", "phloem": "韧皮部",
    "transpiration": "蒸腾", "stomata": "气孔",
    "tropism": "向性", "auxin": "生长素",
    "cytokinin": "细胞分裂素", "gibberellin": "赤霉素",
    "abscisic": "脱落酸", "ethylene": "乙烯",
    "decomposer": "分解者", "producer": "生产者", "consumer": "消费者",
    "trophic": "营养级", "biomass": "生物量",
    "eutrophication": "富营养化", "acidification": "酸化",
    "deforestation": "森林砍伐", "desertification": "荒漠化",
    "extinction": "灭绝", "endangered": "濒危",
    "invasive": "入侵", "endemic": "特有",
    "phylogeny": "系统发育", "clade": "分支", "cladistics": "分支学",
    "homology": "同源性", "analogy": "类似", "convergent": "趋同",
    "divergent": "趋异", "coevolution": "协同进化",
    "biogeography": "生物地理学", "continental": "大陆",
    "vestigial": "退化", "atavism": "返祖",
    # ── 补充缺失高频词 ──
    "lemma": "引理", "effect": "效应", "critical": "临界",
    "axiom": "公理", "axioms": "公理", "problem": "问题", "problems": "问题",
    "length": "长度", "polar": "极坐标", "formula": "公式",
    "coefficients": "系数", "coefficient": "系数",
    "form": "形式", "forms": "形式",
    "cryptography": "密码学", "independence": "独立性", "independent": "独立",
    "functors": "函子", "integration": "积分",
    "measurement": "测量", "propagation": "传播",
    "rates": "速率", "rate": "速率", "area": "面积",
    "identities": "恒等式", "identity": "恒等式",
    "seasons": "季节", "seasonal": "季节性",
    "factors": "因素", "factor": "因素",
    "plasticity": "可塑性", "conduction": "传导",
    "secretion": "分泌", "potentials": "电位",
    "uncertainty": "不确定性", "nomenclature": "命名法",
    "normal": "正态", "arc": "弧",
    "coordinates": "坐标", "coordinate": "坐标",
    "spherical": "球面", "well": "势阱",
    "angle": "角", "angles": "角",
    "asymptotic": "渐近", "distributions": "分布",
    "ratio": "比率", "separation": "分离",
    "gauge": "规范", "canonical": "正则",
    "relation": "关系", "relations": "关系",
    "expansion": "展开", "phenomena": "现象", "phenomenon": "现象",
    "semantic": "语义", "hierarchy": "层次",
    "amplifier": "放大器", "amplification": "放大",
    "determination": "确定", "capacity": "容量",
    "sigma": "σ", "interpretation": "解释",
    "transduction": "转导", "sensing": "感应",
    "absolute": "绝对", "term": "项",
    "action": "作用", "multivariate": "多元",
    "limiting": "极限", "reagent": "试剂", "reagents": "试剂",
    "thin": "薄", "projections": "投影",
    "complexes": "络合物", "singular": "奇异",
    "chains": "链", "harmonic": "调和",
    "transformations": "变换", "bifurcation": "分岔",
    "map": "映射", "notation": "记号",
    "closure": "闭包", "change": "变化",
    "orthogonal": "正交", "orthonormal": "标准正交",
    "sex": "性别", "biogeochemical": "生物地球化学",
    "carrying": "承载", "heritability": "遗传力",
    "broad": "广义", "narrow": "狭义", "sense": "意义",
    "life": "生命", "history": "历史", "strategies": "策略", "strategy": "策略",
    "metapopulation": "复合种群", "connectivity": "连通性", "patches": "斑块",
    "nutrient": "养分", "cycling": "循环",
    "phenotypic": "表型", "variation": "变异", "populations": "种群",
    "evolvability": "可进化性",
    "exaptation": "预适应", "fitness": "适合度",
    "landscape": "景观", "hawk": "鹰", "dove": "鸽",
    "game": "博弈", "heterozygote": "杂合子", "advantage": "优势",
    "inbreeding": "近交", "consequences": "后果",
    "inclusive": "包容性", "parsimony": "简约法",
    "phylogenetics": "系统发育学",
    "synonymous": "同义", "nonsynonymous": "非同义",
    "substitutions": "替换", "substitution": "替换",
    "wahlund": "瓦伦德", "dihybrid": "双杂合",
    "crosses": "杂交", "cross": "杂交",
    "barcoding": "条形码", "markers": "标记", "marker": "标记",
    "one": "一", "two": "二", "three": "三", "multi": "多",
    "iupac": "IUPAC", "friedel": "傅-克", "crafts": "反应",
    "pka": "pKa", "pkb": "pKb", "ph": "pH",
    "sigma": "σ", "pi": "π", "delta": "δ", "omega": "ω",
    "alpha": "α", "beta": "β", "gamma": "γ",

    # ── 地球科学 ──
    "earth": "地球", "geology": "地质学", "geological": "地质",
    "geophysics": "地球物理", "geochemistry": "地球化学",
    "plate": "板块", "tectonic": "构造", "tectonics": "构造",
    "volcano": "火山", "volcanic": "火山", "earthquake": "地震", "seismic": "地震",
    "ocean": "海洋", "oceanic": "海洋", "marine": "海洋",
    "atmosphere": "大气", "atmospheric": "大气", "climate": "气候", "weather": "天气",
    "continent": "大陆", "continental": "大陆",
    "mineral": "矿物", "minerals": "矿物", "rock": "岩石", "rocks": "岩石",
    "sediment": "沉积物", "sedimentary": "沉积", "igneous": "火成",
    "metamorphic": "变质", "erosion": "侵蚀", "weathering": "风化",
    "glacier": "冰川", "glacial": "冰川", "ice": "冰",
    "river": "河流", "lake": "湖泊", "groundwater": "地下水",
    "soil": "土壤", "desert": "沙漠", "forest": "森林",
    "mountain": "山脉", "basin": "盆地", "valley": "谷地",
    "fossil": "化石", "fossils": "化石", "stratigraphy": "地层学",
    "paleontology": "古生物学", "paleoclimate": "古气候",
    "solar": "太阳", "sun": "太阳", "moon": "月球", "lunar": "月球",
    "planet": "行星", "planetary": "行星", "planets": "行星",
    "star": "恒星", "stars": "恒星", "stellar": "恒星",
    "galaxy": "星系", "galaxies": "星系", "universe": "宇宙", "cosmic": "宇宙",
    "nebula": "星云", "supernova": "超新星", "black": "黑",
    "hole": "洞", "comet": "彗星", "asteroid": "小行星",
    "orbit": "轨道", "orbital": "轨道", "satellite": "卫星",
    "telescope": "望远镜", "observatory": "天文台",
    "astrophysics": "天体物理", "cosmology": "宇宙学",
    "tide": "潮汐", "tidal": "潮汐", "current": "洋流",
    "salinity": "盐度", "depth": "深度", "surface": "表面",
    "wind": "风", "monsoon": "季风", "hurricane": "飓风", "cyclone": "气旋",
    "precipitation": "降水", "humidity": "湿度", "cloud": "云", "clouds": "云",
    "ozone": "臭氧", "greenhouse": "温室", "warming": "变暖",
    "carbon": "碳", "dioxide": "二氧化物", "methane": "甲烷",
    "water": "水", "hydrological": "水文", "hydrology": "水文学",
    "geomorphology": "地貌学", "landform": "地形", "topography": "地形",
    "mantle": "地幔", "crust": "地壳", "core": "地核/核心",
    "magnetic": "磁", "magnetosphere": "磁层",
    "formation": "形成", "boundary": "边界",

    # ── 计算机科学 ──
    "computer": "计算机", "computing": "计算", "computation": "计算",
    "algorithm": "算法", "algorithms": "算法", "data": "数据",
    "database": "数据库", "databases": "数据库",
    "programming": "编程", "program": "程序", "programs": "程序",
    "software": "软件", "hardware": "硬件", "firmware": "固件",
    "code": "代码", "coding": "编码", "debugging": "调试",
    "compiler": "编译器", "interpreter": "解释器",
    "syntax": "语法", "semantics": "语义", "parsing": "解析",
    "object": "对象", "class": "类", "interface": "接口",
    "inheritance": "继承", "polymorphism": "多态", "encapsulation": "封装",
    "abstraction": "抽象", "modular": "模块化", "module": "模块",
    "function": "函数", "procedure": "过程", "method": "方法",
    "variable": "变量", "constant": "常量", "parameter": "参数",
    "array": "数组", "list": "列表", "stack": "栈", "queue": "队列",
    "hash": "哈希", "table": "表", "linked": "链表",
    "binary": "二叉/二进制", "search": "搜索", "sort": "排序", "sorting": "排序",
    "tree": "树", "heap": "堆", "trie": "字典树",
    "complexity": "复杂度", "performance": "性能", "efficiency": "效率",
    "parallel": "并行", "concurrent": "并发", "distributed": "分布式",
    "thread": "线程", "process": "进程", "synchronization": "同步",
    "operating": "操作", "system": "系统", "systems": "系统",
    "kernel": "内核", "scheduler": "调度器", "scheduling": "调度",
    "file": "文件", "directory": "目录", "storage": "存储",
    "memory": "内存/记忆", "cache": "缓存", "virtual": "虚拟",
    "network": "网络", "protocol": "协议", "protocols": "协议",
    "tcp": "TCP", "ip": "IP", "http": "HTTP", "dns": "DNS",
    "routing": "路由", "router": "路由器", "switch": "交换机",
    "security": "安全", "encryption": "加密", "decryption": "解密",
    "authentication": "认证", "authorization": "授权",
    "firewall": "防火墙", "vulnerability": "漏洞",
    "artificial": "人工", "intelligence": "智能",
    "machine": "机器", "deep": "深度", "neural": "神经",
    "supervised": "监督", "unsupervised": "无监督", "reinforcement": "强化",
    "classification": "分类", "clustering": "聚类", "regression": "回归",
    "training": "训练", "dataset": "数据集", "feature": "特征",
    "overfitting": "过拟合", "underfitting": "欠拟合",
    "convolutional": "卷积", "recurrent": "循环", "attention": "注意力",
    "transformer": "变换器", "generative": "生成", "adversarial": "对抗",
    "natural": "自然", "language": "语言", "processing": "处理",
    "image": "图像", "recognition": "识别", "detection": "检测",
    "robot": "机器人", "robotics": "机器人学", "autonomous": "自主",
    "web": "网络/网", "internet": "互联网", "cloud": "云",
    "api": "API", "rest": "REST", "microservice": "微服务",
    "frontend": "前端", "backend": "后端", "fullstack": "全栈",
    "mobile": "移动", "embedded": "嵌入式", "iot": "物联网",
    "blockchain": "区块链", "cryptocurrency": "加密货币",
    "agile": "敏捷", "devops": "运维开发", "testing": "测试",
    "version": "版本", "control": "控制", "git": "Git",
    "ide": "集成开发环境", "framework": "框架", "library": "库",
    "architecture": "架构", "pattern": "模式", "patterns": "模式",
    "client": "客户端", "server": "服务器", "peer": "对等",
    "packet": "数据包", "bandwidth": "带宽", "latency": "延迟",
    "boolean": "布尔", "bit": "位", "byte": "字节",
    "register": "寄存器", "instruction": "指令", "assembly": "汇编",
    "cpu": "CPU", "gpu": "GPU", "ram": "RAM",
    "input": "输入", "output": "输出", "io": "输入输出",
    "exception": "异常", "error": "错误", "handling": "处理",
    "pointer": "指针", "reference": "引用", "garbage": "垃圾",
    "collection": "集合/回收", "allocation": "分配",
    "recursion": "递归", "iteration": "迭代", "loop": "循环",
    "conditional": "条件", "branch": "分支", "switch": "开关",
    "string": "字符串", "character": "字符", "unicode": "统一码",
    "regex": "正则", "pattern": "模式", "matching": "匹配",
    "automata": "自动机", "finite": "有限", "state": "状态",
    "turing": "图灵", "halting": "停机", "decidable": "可判定",
    "np": "NP", "hard": "难", "completeness": "完全性",
    "greedy": "贪心", "dynamic": "动态", "backtracking": "回溯",
    "divide": "分治", "conquer": "征服",
    "graph": "图", "traversal": "遍历", "shortest": "最短",
    "spanning": "生成", "minimum": "最小", "maximum": "最大",
    "flow": "流", "cut": "割", "matching": "匹配",
    "discrete": "离散", "continuous": "连续",
    "formal": "形式", "language": "语言", "grammar": "文法",
    "context": "上下文", "free": "自由/免费",
    "relational": "关系", "sql": "SQL", "nosql": "NoSQL",
    "transaction": "事务", "consistency": "一致性", "isolation": "隔离",
    "index": "索引", "query": "查询", "join": "连接",
    "normalization": "规范化", "schema": "模式",
    "socket": "套接字", "port": "端口", "connection": "连接",
    "wireless": "无线", "bluetooth": "蓝牙", "wifi": "WiFi",
    "signal": "信号", "analog": "模拟", "digital": "数字",
    "sampling": "采样", "quantization": "量化", "encoding": "编码",
    "compression": "压缩", "decompression": "解压缩",
    "pixel": "像素", "resolution": "分辨率", "render": "渲染", "rendering": "渲染",
    "simulation": "仿真", "modeling": "建模",
    "user": "用户", "experience": "体验", "usability": "可用性",
    "accessibility": "无障碍", "responsive": "响应式",

    # ── 工程 ──
    "engineering": "工程", "structural": "结构", "civil": "土木",
    "mechanical": "机械", "electrical": "电气", "electronic": "电子",
    "aerospace": "航空航天", "aeronautical": "航空", "astronautical": "航天",
    "marine": "船舶/海洋", "naval": "海军/船舶", "automotive": "汽车",
    "chemical": "化工", "biomedical": "生物医学", "environmental": "环境",
    "agricultural": "农业", "nuclear": "核", "hydraulic": "水利",
    "material": "材料", "materials": "材料", "composite": "复合",
    "concrete": "混凝土", "steel": "钢", "alloy": "合金", "aluminum": "铝",
    "beam": "梁", "column": "柱", "foundation": "基础/地基",
    "bridge": "桥梁", "dam": "大坝", "tunnel": "隧道",
    "construction": "施工", "building": "建筑",
    "stress": "应力", "strain": "应变", "deformation": "变形",
    "fatigue": "疲劳", "fracture": "断裂", "failure": "失效",
    "load": "荷载", "loading": "加载", "deflection": "挠度",
    "strength": "强度", "stiffness": "刚度", "hardness": "硬度",
    "ductility": "延展性", "toughness": "韧性", "brittle": "脆性",
    "corrosion": "腐蚀", "wear": "磨损", "erosion": "侵蚀",
    "welding": "焊接", "casting": "铸造", "forging": "锻造", "machining": "机加工",
    "manufacturing": "制造", "assembly": "装配", "quality": "质量",
    "tolerance": "公差", "precision": "精度", "accuracy": "精确度",
    "automation": "自动化", "control": "控制", "feedback": "反馈",
    "sensor": "传感器", "sensors": "传感器", "actuator": "执行器",
    "motor": "电机", "engine": "发动机", "turbine": "涡轮",
    "pump": "泵", "valve": "阀门", "pipe": "管道", "pipeline": "管线",
    "boiler": "锅炉", "compressor": "压缩机", "condenser": "冷凝器",
    "refrigeration": "制冷", "hvac": "暖通空调", "ventilation": "通风",
    "combustion": "燃烧", "fuel": "燃料", "propulsion": "推进",
    "thrust": "推力", "drag": "阻力", "lift": "升力",
    "wing": "机翼", "airfoil": "翼型", "fuselage": "机身",
    "landing": "着陆", "takeoff": "起飞", "navigation": "导航",
    "radar": "雷达", "sonar": "声呐", "gps": "GPS",
    "satellite": "卫星", "spacecraft": "航天器", "rocket": "火箭",
    "payload": "有效载荷", "orbit": "轨道",
    "irrigation": "灌溉", "drainage": "排水", "flood": "洪水",
    "reservoir": "水库", "canal": "运河", "levee": "堤坝",
    "crop": "作物", "harvest": "收获", "tillage": "耕作",
    "fertilizer": "肥料", "pesticide": "农药",
    "renewable": "可再生", "sustainability": "可持续",
    "wind": "风", "solar": "太阳能", "geothermal": "地热",
    "biomass": "生物质", "biofuel": "生物燃料",
    "transmission": "输电/传动", "generator": "发电机", "transformer": "变压器",
    "voltage": "电压", "frequency": "频率", "phase": "相位",
    "reliability": "可靠性", "maintenance": "维护", "inspection": "检测",
    "safety": "安全", "risk": "风险", "hazard": "危害",
    "pollution": "污染", "emission": "排放", "waste": "废物",
    "treatment": "处理", "recycling": "回收", "disposal": "处置",
    "ship": "船舶", "hull": "船体", "propeller": "螺旋桨",
    "buoyancy": "浮力", "stability": "稳性", "displacement": "排水量",
    "containment": "安全壳", "shielding": "屏蔽", "coolant": "冷却剂",
    "enrichment": "浓缩", "fuel": "燃料", "rod": "棒",
    "chain": "链式", "criticality": "临界",
    "tradeoffs": "权衡", "constraints": "约束", "specifications": "规格",
    "prototype": "原型", "iteration": "迭代", "testing": "测试",
    "standard": "标准", "standards": "标准", "code": "规范",
    "diagram": "图", "diagrams": "图", "schematic": "原理图",
    "blueprint": "蓝图", "cad": "CAD", "simulation": "仿真",

    # ── 第4轮补充：高频缺失词(497个) ──
    "time": "时间", "response": "响应", "fundamental": "基本",
    "transfer": "传递", "balance": "平衡", "equivalence": "等价",
    "line": "线", "transform": "变换", "information": "信息",
    "based": "基", "quantitative": "定量", "analytical": "分析",
    "rigorous": "严格", "multivariable": "多变量", "theorems": "定理",
    "counting": "计数", "propositional": "命题", "double": "二重",
    "machines": "机器", "body": "体", "level": "级",
    "point": "点", "weak": "弱", "examples": "例",
    "pdes": "偏微分方程", "uniform": "一致", "filter": "滤波器",
    "cycles": "循环", "microbial": "微生物", "operations": "运算",
    "plane": "平面", "superposition": "叠加", "statmech": "统计力学",
    "classes": "类", "relationships": "关系", "dependent": "相关",
    "non": "非", "contraction": "收缩", "variational": "变分",
    "exponential": "指数", "simple": "简单", "fermi": "费米",
    "management": "管理", "production": "产生", "adaptive": "自适应",
    "effective": "有效", "foundations": "基础", "locus": "轨迹",
    "coordination": "配位", "high": "高", "internal": "内",
    "common": "常见", "composition": "组合", "formulas": "公式",
    "partition": "划分", "coupling": "耦合",
    "forcing": "强迫", "organization": "组织",
    "over": "上", "axis": "轴", "basis": "基",
    "fungal": "真菌", "exchange": "交换", "calculations": "计算",
    "vapor": "蒸气", "self": "自", "shift": "移位",
    "relative": "相对", "levels": "能级", "extensions": "扩展",
    "exact": "正合", "planar": "平面", "probabilistic": "概率",
    "bounds": "界", "bounded": "有界", "tables": "表",
    "triple": "三重", "total": "全", "unit": "单位",
    "impedance": "阻抗", "lorentz": "洛伦兹", "transient": "瞬态",
    "fine": "精细", "checking": "检验", "filters": "滤波器",
    "exoplanet": "系外行星", "reconstruction": "重建",
    "remotesensing": "遥感", "ordinal": "序数", "cardinal": "基数",
    "metrics": "度量", "recovery": "恢复", "dating": "定年",
    "interactions": "相互作用", "effects": "效应", "single": "单",
    "domains": "域", "states": "态", "identification": "辨识",
    "sample": "样本", "constants": "常数", "elementary": "初等",
    "splitting": "分裂", "characteristic": "特征", "implicit": "隐式",
    "parametric": "参数", "trigonometric": "三角", "bipartite": "二部",
    "congruences": "同余", "paths": "路径", "coloring": "着色",
    "components": "分量", "multiplication": "乘法", "cartesian": "笛卡尔",
    "statements": "命题", "strong": "强", "conservative": "保守",
    "maps": "映射", "partials": "偏导数", "review": "综述",
    "central": "中心", "theoretic": "论", "tests": "检验",
    "descriptive": "描述", "sequential": "序贯", "induced": "诱导",
    "interior": "内部", "circular": "圆", "frames": "参考系",
    "interaction": "相互作用", "electrostatics": "静电学",
    "dielectric": "电介质", "regularization": "正则化",
    "bose": "玻色", "ensemble": "系综", "engines": "热机",
    "isentropic": "等熵", "mirror": "镜", "ray": "射线",
    "layer": "层", "codes": "码", "languages": "语言",
    "decidability": "可判定性", "hydrostatic": "静水",
    "crustal": "地壳", "truss": "桁架",
    "secondary": "二级", "movement": "运动", "dependence": "依赖",
    "ratios": "比", "drift": "漂移", "calibration": "标定",
    "records": "记录", "spontaneous": "自发",
    "prediction": "预测", "spatial": "空间", "perception": "感知",
    "selectivity": "选择性", "validation": "验证", "parameters": "参数",
    "polarity": "极性", "half": "半", "solubility": "溶解度",
    "matter": "物质", "ceramic": "陶瓷", "characterization": "表征",
    "rearrangement": "重排", "markovnikov": "马氏",
    "perturbation": "微扰", "orthogonality": "正交性",
    "direct": "直接", "products": "积", "ideals": "理想",
    "homological": "同调", "degree": "度", "argument": "辐角",
    "odes": "常微分方程", "pde": "偏微分方程", "inverse": "逆",
    "stokes": "斯托克斯", "binomial": "二项", "combinations": "组合",
    "pigeonhole": "鸽巢", "adjacency": "邻接", "ramsey": "拉姆齐",
    "cantor": "康托", "proving": "证明",
    "leastsquares": "最小二乘", "confidence": "置信", "intervals": "区间",
    "greens": "格林", "centerof": "质心",
    "magnitudeand": "大小与", "andexamples": "与例",
    "andnomenclature": "与命名", "fol": "一阶逻辑", "chisquare": "卡方",
    # ── 动词/形容词 ──
    "using": "使用", "involving": "涉及", "finding": "求解",
    "solving": "求解", "defining": "定义", "constructing": "构造",
    "extending": "扩展", "applying": "应用", "relating": "关联",
    "comparing": "比较", "understanding": "理解", "exploring": "探索",
    "representing": "表示", "generating": "生成",
    "measuring": "测量", "determining": "确定",
    "interpreting": "解释", "visualizing": "可视化",
    "optimizing": "优化", "approximating": "近似",
    "reducing": "化简", "combining": "组合",
    "classifying": "分类",
    # ── 物理补充 ──
    "isothermal": "等温", "adiabatic": "绝热", "isobaric": "等压",
    "isochoric": "等容", "carnot": "卡诺",
    "reversible": "可逆", "irreversible": "不可逆",
    "diatomic": "双原子", "monoatomic": "单原子",
    "microcanonical": "微正则", "grandcanonical": "巨正则",
    "superfluidity": "超流", "superconducting": "超导",
    "quasiparticle": "准粒子", "soliton": "孤子", "vortex": "涡旋",
    "renormalization": "重整化", "feynman": "费曼",
    "propagator": "传播子", "section": "截面",
    "dipole": "偶极", "multipole": "多极", "quadrupole": "四极",
    "faraday": "法拉第", "ampere": "安培",
    "coulomb": "库仑", "kirchhoff": "基尔霍夫",
    "thevenin": "戴维南", "norton": "诺顿",
    "biot": "毕奥", "savart": "萨伐尔",
    "lenz": "楞次", "poynting": "坡印廷",
    "doppler": "多普勒", "fresnel": "菲涅尔",
    "snell": "斯涅尔", "brewster": "布儒斯特",
    "compton": "康普顿", "photoelectric": "光电",
    "zeeman": "塞曼", "rydberg": "里德伯",
    "lyman": "莱曼", "balmer": "巴尔末", "paschen": "帕邢",
    "pauli": "泡利", "exclusion": "不相容",
    "aufbau": "构造", "hund": "洪特",
    "degeneracy": "简并", "degenerate": "简并",
    "perturbative": "微扰", "nonperturbative": "非微扰",
    "wkb": "WKB", "born": "玻恩",
    "oppenheimer": "奥本海默",
    "helium": "氦", "lithium": "锂", "beryllium": "铍", "boron": "硼",
    "sodium": "钠", "magnesium": "镁", "silicon": "硅",
    "potassium": "钾", "calcium": "钙", "iron": "铁",
    "copper": "铜", "zinc": "锌", "silver": "银",
    "gold": "金", "platinum": "铂", "titanium": "钛",
    "chromium": "铬", "manganese": "锰", "nickel": "镍",
    "cobalt": "钴", "tungsten": "钨", "uranium": "铀",
    # ── 数学补充 ──
    "endomorphism": "自同态", "monoid": "幺半群", "semigroup": "半群",
    "poset": "偏序集", "zorn": "佐恩",
    "ordinals": "序数", "cardinals": "基数",
    "transfinite": "超限", "continuum": "连续统",
    "constructive": "构造", "nonconstructive": "非构造",
    "computable": "可计算", "undecidable": "不可判定",
    "godel": "哥德尔", "incompleteness": "不完备",
    "soundness": "可靠性", "satisfiability": "可满足性",
    "tautology": "重言式", "disjunction": "析取", "conjunction": "合取",
    "negation": "否定", "implication": "蕴含",
    "biconditional": "双条件", "quantifier": "量词",
    "quantifiers": "量词", "universal": "全称", "existential": "存在",
    "contrapositive": "逆否", "contradiction": "矛盾",
    "counterexample": "反例", "counterexamples": "反例",
    "diagonalization": "对角化", "triangular": "三角",
    "upper": "上", "lower": "下", "row": "行",
    "echelon": "阶梯", "reduced": "简化",
    "span": "张成", "nullspace": "零空间",
    "inner": "内", "outer": "外",
    "bilinear": "双线性", "sesquilinear": "半双线性",
    "positive": "正", "definite": "定",
    "semidefinite": "半定", "indefinite": "不定",
    "nonsingular": "非奇异", "diagonalizable": "可对角化",
    "nilpotent": "幂零", "idempotent": "幂等",
    "adjoint": "伴随", "transpose": "转置",
    "hermitian": "厄米", "unitary": "酉",
    "similarity": "相似",
    "jordan": "若尔当",
    "annihilator": "零化", "cyclic": "循环",
    "finitely": "有限", "generated": "生成",
    "divisible": "可除",
    "injective": "内射", "surjective": "满射",
    "bijective": "双射", "bijection": "双射",
    "injection": "单射", "surjection": "满射",
    "short": "短", "long": "长", "derived": "导出",
    "projective": "射影", "flat": "平坦",
    "localization": "局部化", "completion": "完备化",
    "noetherian": "诺特", "artinian": "阿廷",
    "dedekind": "戴德金", "euclidean": "欧几里得",
    "principal": "主", "maximal": "极大",
    "radical": "根", "transcendental": "超越",
    "inseparable": "不可分",
    "correspondence": "对应", "fixed": "不动点",
    "stabilizer": "稳定子", "conjugacy": "共轭",
    "centralizer": "中心化子", "normalizer": "正规化子",
    "solvable": "可解", "alternating": "交错",
    "dihedral": "二面体", "presentation": "表示",
    "generators": "生成元",
    # ── 生物/医学补充 ──
    "haploinsufficiency": "单倍不足", "dosage": "剂量",
    "epigenomics": "表观基因组", "pharmacogenomics": "药物基因组学",
    "immunoglobulin": "免疫球蛋白", "cytokine": "细胞因子",
    "cytokines": "细胞因子", "interleukin": "白细胞介素",
    "interferon": "干扰素", "tumor": "肿瘤",
    "inflammation": "炎症", "inflammatory": "炎症",
    "autoimmune": "自身免疫", "hypersensitivity": "超敏反应",
    "complement": "补体", "innate": "先天",
    "acquired": "获得性", "humoral": "体液",
    "lymphocyte": "淋巴细胞", "macrophage": "巨噬细胞",
    "autonomic": "自主神经", "parasympathetic": "副交感",
    "sympathetic": "交感", "somatic": "躯体",
    "afferent": "传入", "efferent": "传出",
    "ganglion": "神经节", "cortex": "皮层",
    "hippocampus": "海马", "amygdala": "杏仁核",
    "cerebellum": "小脑", "thalamus": "丘脑",
    "hypothalamus": "下丘脑", "basal": "基底",
    "ganglia": "神经节", "prefrontal": "前额叶",
    "brainstem": "脑干", "spinal": "脊髓",
    "peripheral": "外周", "neurotransmitter": "神经递质",
    "dopamine": "多巴胺", "serotonin": "血清素",
    "glutamate": "谷氨酸", "glycine": "甘氨酸",
    # ── 地球科学补充 ──
    "seismology": "地震学", "volcanology": "火山学",
    "petrology": "岩石学", "mineralogy": "矿物学",
    "sedimentology": "沉积学", "geodesy": "大地测量",
    "geochronology": "地质年代学",
    "lithosphere": "岩石圈", "asthenosphere": "软流圈",
    "subduction": "俯冲", "rift": "裂谷",
    "orogeny": "造山", "folding": "褶皱",
    "faulting": "断裂", "detrital": "碎屑", "clastic": "碎屑",
    "carbonate": "碳酸盐", "evaporite": "蒸发岩",
    "diagenesis": "成岩", "lithification": "成�ite化",
    "facies": "相", "transgression": "海侵",
    "unconformity": "不整合", "biostratigraphy": "生物地层",
    "chronostratigraphy": "年代地层",
    "radiometric": "放射性", "isotopic": "同位素",
    "fractionation": "分馏", "convection": "对流", "advection": "平流",
    "subsidence": "沉降", "uplift": "隆起",
    "denudation": "剥蚀", "sedimentation": "沉积",
    "fluvial": "河流", "glaciation": "冰期",
    "interglacial": "间冰期", "quaternary": "第四纪",
    "holocene": "全新世", "pleistocene": "更新世",
    "cretaceous": "白垩纪", "jurassic": "侏罗纪",
    "triassic": "三叠纪", "cambrian": "寒武纪",
    "precambrian": "前寒武纪",
    "earths": "地球", "remotesensing": "遥感",


    # ── 第5轮补充 ──
    "computability": "可计算性", "moment": "力矩", "points": "点",
    "modes": "模式", "value": "值", "rigid": "刚体",
    "realization": "实现", "conductivity": "电导率",
    "regular": "正则", "remote": "遥感",
    "algebras": "代数", "means": "均值", "filtering": "滤波",
    "steady": "稳态", "dark": "暗", "definitions": "定义",
    "moments": "矩", "solids": "固体", "oscillator": "振荡器",
    "step": "阶跃", "gates": "门", "ordering": "序",
    "truth": "真值", "joint": "联合", "static": "静态",
    "dispersion": "色散", "zero": "零", "scaling": "标度",
    "anomaly": "异常", "layers": "层", "momentof": "转动惯量",
    "primary": "初级", "channels": "通道", "read": "读",
    "distance": "距离", "crystallization": "结晶",
    "constraint": "约束", "saturation": "饱和",
    "homogeneous": "齐次", "anti": "反", "gases": "气体",
    "rlc": "RLC", "countability": "可数性", "recurrence": "递推",
    "squares": "平方", "chebyshev": "切比雪夫",
    "floating": "浮点", "difference": "差分", "large": "大",
    "way": "路", "events": "事件", "dissipation": "耗散",
    "montecarlo": "蒙特卡洛", "virial": "维里",
    "pipes": "管道", "intensity": "强度", "observer": "观测者",
    "source": "源", "lens": "透镜", "union": "并",
    "implementation": "实现", "signals": "信号",
    "magnitude": "大小", "nondeterministic": "非确定性",
    "pspace": "PSPACE", "radiative": "辐射",
    "plastic": "塑性", "defects": "缺陷",
    "assessment": "评估", "size": "规模", "local": "局部",
    "balancing": "平衡", "bias": "偏差", "likelihood": "似然",
    "negative": "负", "compensation": "补偿",
    "morphology": "形态", "spectrometry": "质谱",
    "sensitivity": "灵敏度", "prevention": "预防",
    "fluorescence": "荧光", "preparation": "制备",
    "configuration": "构型", "orbitals": "轨道",
    "intermolecular": "分子间", "main": "主",
    "adsorption": "吸附", "relaxation": "弛豫",
    "tunneling": "隧穿", "unique": "唯一",
    "five": "五", "damping": "阻尼", "tangent": "切线",
    "breadth": "广度", "cardinality": "基数",
    "chromatic": "色", "predicates": "谓词",
    "dot": "点", "measurable": "可测", "connectives": "连接词",
    "equivalences": "等价", "curl": "旋度",
    "cylindrical": "柱坐标", "criterion": "准则",
    "variations": "变分", "elliptic": "椭圆",
    "exponents": "指数", "proportions": "比例",
    "expressions": "表达式", "markov": "马尔可夫",
    "brownian": "布朗", "kolmogorov": "柯尔莫哥洛夫",
    "invariants": "不变量", "precession": "进动",
    "newtons": "牛顿", "escape": "逃逸", "orbits": "轨道",
    "many": "多", "lines": "线", "transverse": "横",
    "invariant": "不变", "derivation": "推导",
    "unification": "统一", "qft": "量子场论",
    "brayton": "布雷顿", "clausius": "克劳修斯",
    "compressibility": "压缩性", "polytropic": "多变",
    "rankine": "朗肯", "strings": "弦",
    "speed": "速度", "combined": "组合",
    "lists": "链表", "objects": "对象", "big": "大",
    "all": "所有", "offs": "关", "locking": "锁定",
    "write": "写", "proxies": "代理", "address": "地址",
    "ipv": "IPv", "knowledge": "知识", "head": "头",
    "support": "支持", "generation": "生成", "sat": "SAT",
    # ── 生化术语 ──
    "machinery": "机器", "cofactors": "辅因子",
    "coenzymes": "辅酶", "cooperativity": "协同性",
    "fad": "FAD", "fadh": "FADH", "carriers": "载体",
    "fasted": "禁食", "fed": "进食", "glycogen": "糖原",
    "lactate": "乳酸", "michaelis": "米氏", "menten": "门顿",
    "salvage": "补救", "pentose": "戊糖", "phosphate": "磷酸",
    "phospholipid": "磷脂", "denaturation": "变性",
    "renaturation": "复性", "cascades": "级联",
    "targeting": "靶向", "subcellular": "亚细胞",
    "tertiary": "三级", "purine": "嘌呤", "pyrimidine": "嘧啶",
    "wobble": "摆动", "lipolysis": "脂解",
    "mobilization": "动员", "lipoproteins": "脂蛋白",
    "hormonal": "激素", "chemiosmosis": "化学渗透",
    "phenylketonuria": "苯丙酮尿症",
    "chaperones": "分子伴侣", "chaperone": "分子伴侣",
    "folding": "折叠", "misfolding": "错误折叠",
    "aggregation": "聚集", "fibril": "纤维",
    "amyloid": "淀粉样", "prion": "朊病毒",
    "glycoprotein": "糖蛋白", "glycolipid": "糖脂",
    "sphingolipid": "鞘脂", "ceramide": "神经酰胺",
    "ganglioside": "神经节苷脂",
    "cholesterol": "胆固醇", "steroid": "类固醇",
    "sterol": "固醇", "bile": "胆汁",
    "bilirubin": "胆红素", "heme": "血红素",
    "porphyrin": "卟啉", "globin": "珠蛋白",
    "myoglobin": "肌红蛋白", "hemoglobin": "血红蛋白",
    "collagen": "胶原", "elastin": "弹性蛋白",
    "keratin": "角蛋白", "actin": "肌动蛋白",
    "myosin": "肌球蛋白", "tubulin": "微管蛋白",
    "fibronectin": "纤维连接蛋白",
    "integrin": "整合素", "cadherin": "钙黏蛋白",
    "selectin": "选择素",
    "glucagon": "胰高血糖素", "insulin": "胰岛素",
    "thyroxine": "甲状腺素", "cortisol": "皮质醇",
    "estrogen": "雌激素", "testosterone": "睾酮",
    "progesterone": "孕激素", "aldosterone": "醛固酮",
    "vasopressin": "加压素", "oxytocin": "催产素",
    "epinephrine": "肾上腺素", "melatonin": "褪黑素",
    "prostaglandin": "前列腺素", "leukotriene": "白三烯",
    "thromboxane": "血栓素",
    "nadph": "NADPH", "fadh2": "FADH2",
    "coenzyme": "辅酶", "ubiquinone": "泛醌",
    "cytochrome": "细胞色素",
    "succinate": "琥珀酸", "fumarate": "富马酸",
    "malate": "苹果酸", "oxaloacetate": "草酰乙酸",
    "acetyl": "乙酰", "coa": "辅酶A",
    "pyruvate": "丙酮酸", "ketone": "酮体",
    "beta": "β", "alpha": "α",
    # ── 更多通用词 ──
    "into": "到", "not": "非", "are": "是",
    "can": "能", "how": "如何", "what": "什么",
    "new": "新", "old": "旧", "same": "相同",
    "different": "不同", "other": "其他", "more": "更多",
    "less": "更少", "most": "最", "least": "最小",
    "very": "非常", "only": "仅", "also": "也",
    "both": "两", "each": "每", "every": "每",
    "any": "任意", "some": "某些", "few": "少数",
    "full": "完全", "empty": "空", "true": "真",
    "false": "假", "equal": "相等", "greater": "大于",
    "smaller": "小于", "between": "之间", "within": "之内",
    "without": "无", "about": "关于", "before": "之前",
    "after": "之后", "during": "期间", "through": "通过",
    "under": "下", "above": "上", "below": "下",
    "near": "近", "far": "远", "left": "左",
    "right": "右", "top": "顶", "bottom": "底",
    "front": "前", "back": "后", "end": "末",
    "begin": "始", "start": "开始", "stop": "停止",
    "four": "四", "six": "六", "seven": "七",
    "eight": "八", "nine": "九", "ten": "十",
    "hundred": "百", "thousand": "千",
    # ── CS/EE 补充 ──
    "nfa": "NFA", "dfa": "DFA", "cfg": "上下文无关文法",
    "pda": "下推自动机", "regex": "正则表达式",
    "reducibility": "可归约性", "np": "NP",
    "coNP": "coNP", "polynomial": "多项式",
    "exponential": "指数", "logarithmic": "对数",
    "amortized": "摊还", "deterministic": "确定性",
    "probabilistic": "概率", "randomized": "随机化",
    "heuristic": "启发式", "approximation": "近似",
    "optimal": "最优", "suboptimal": "次优",
    "feasible": "可行", "infeasible": "不可行",
    "objective": "目标", "simplex": "单纯形",
    "duality": "对偶性", "slack": "松弛",
    "surplus": "剩余", "tableau": "单纯形表",
    "pivot": "主元", "basic": "基本",
    "integer": "整数",
    "assignment": "分配", "transportation": "运输",
    "scheduling": "调度", "knapsack": "背包",
    "travelling": "旅行", "salesman": "商人",
    "vertex": "顶点", "clique": "团",
    "independent": "独立", "covering": "覆盖",
    "euler": "欧拉", "hamiltonian": "哈密顿",
    "biconnected": "双连通", "articulation": "割点",
    "topological": "拓扑", "strongly": "强",
    "weakly": "弱",


    # ── 第6轮补充：生化/物理/CS/地学 ──
    "initiation": "起始", "elongation": "延伸", "termination": "终止",
    "conformational": "构象", "remodeling": "重塑",
    "eukaryotic": "真核", "prokaryotic": "原核",
    "stages": "阶段", "reactive": "活性",
    "fragmentation": "碎片化", "satisfaction": "满足",
    "bodies": "体", "mean": "平均",
    "planes": "平面", "mixing": "混合",
    "tipping": "临界", "gram": "格拉姆",
    "color": "色", "orders": "阶",
    "clapeyron": "克拉珀龙", "vibrational": "振动",
    "lie": "李", "values": "值",
    "inequalities": "不等式", "luminosity": "光度",
    "breaking": "破缺", "access": "访问",
    "hazards": "危害", "causal": "因果",
    "undecidability": "不可判定性", "zones": "带",
    "instability": "不稳定性", "paleoclimatology": "古气候学",
    "stratification": "分层", "convective": "对流",
    "earthquakes": "地震", "magma": "岩浆",
    "coastal": "海岸", "zone": "区",
    "lapse": "递减", "impact": "影响",
    "gis": "GIS", "divider": "分压器",
    "work": "功", "directions": "方向",
    "strengthening": "强化", "volumes": "体积",
    "shock": "激波", "bodeplot": "伯德图",
    "reductions": "归约", "instantiation": "实例化",
    "deduction": "演绎", "zfc": "ZFC公理系统",
    "aircraft": "飞行器",
    "polypeptide": "多肽", "peptidyl": "肽基",
    "transferase": "转移酶", "messenger": "信使",
    "urea": "尿素", "anaphase": "后期",
    "promoting": "促进", "calvin": "卡尔文",
    "death": "死亡", "currency": "货币",
    "leading": "前导", "lagging": "后随",
    "strands": "链", "primers": "引物",
    "helicase": "解旋酶", "damage": "损伤",
    "responses": "响应", "repair": "修复",
    "correction": "纠正", "silencing": "沉默",
    "transcriptional": "转录", "aminoacylation": "氨酰化",
    "divergence": "散度", "mechanics": "力学",
    # ── 连写词拆分翻译 ──
    "chemiosmotic": "化学渗透", "crosssection": "截面",
    "steadystate": "稳态", "timedomain": "时域",
    "frequencydomain": "频域", "openloop": "开环",
    "closedloop": "闭环", "halflife": "半衰期",
    "groundstate": "基态", "excitedstate": "激发态",
    "blackbody": "黑体", "whitedwarf": "白矮星",
    "redshift": "红移", "blueshift": "蓝移",
    "mainsequence": "主序", "neutronstar": "中子星",
    "darkmatter": "暗物质", "darkenergy": "暗能量",
    "spacetime": "时空", "worldline": "世界线",
    "lightyear": "光年", "solarsystem": "太阳系",
    "milkyway": "银河系", "bigbang": "大爆炸",
    "standardmodel": "标准模型",
    # ── 更多数学/逻辑/CS ──
    "satisfiable": "可满足", "unsatisfiable": "不可满足",
    "valid": "有效", "invalid": "无效",
    "premise": "前提", "conclusion": "结论",
    "inference": "推理", "modus": "假言",
    "ponens": "推理", "tollens": "否定式",
    "resolution": "归结", "unification": "合一",
    "herbrand": "厄布朗", "skolem": "斯科伦",
    "prenex": "前束", "clausal": "子句",
    "horn": "Horn", "prolog": "Prolog",
    "backchain": "反向链", "forward": "正向",
    "backward": "反向", "chaining": "链接",
    "monotonic": "单调", "nonmonotonic": "非单调",
    "default": "缺省", "circumscription": "限制",
    "abduction": "溯因", "inductive": "归纳",
    "deductive": "演绎",
    "complexity": "复杂度",
    "space": "空间", "hardness": "困难性",
    "membership": "成员", "emptiness": "空性",
    "equivalence": "等价", "inclusion": "包含",
    "complement": "补", "intersection": "交",
    "difference": "差", "symmetric": "对称",
    "subset": "子集", "superset": "超集",
    "power": "幂", "product": "积",
    "coproduct": "余积", "pullback": "拉回",
    "pushout": "推出", "limit": "极限",
    "colimit": "余极限", "adjunction": "伴随",
    "monad": "单子", "natural": "自然",
    "yoneda": "米田", "representable": "可表",
    # ── 控制/信号处理 ──
    "pid": "PID", "proportional": "比例",
    "integral": "积分", "derivative": "微分",
    "overshoot": "超调", "settling": "稳定",
    "risetime": "上升时间", "bandwidth": "带宽",
    "gain": "增益", "margin": "裕度",
    "nyquist": "奈奎斯特", "bode": "伯德",
    "root": "根", "locus": "轨迹",
    "pole": "极点", "zeros": "零点",
    "transfer": "传递", "function": "函数",
    "laplace": "拉普拉斯", "fourier": "傅里叶",
    "convolution": "卷积", "correlation": "相关",
    "autocorrelation": "自相关", "crosscorrelation": "互相关",
    "spectral": "频谱", "density": "密度",
    "windowing": "窗函数", "aliasing": "混叠",
    "sampling": "采样", "nyquist": "奈奎斯特",
    "reconstruction": "重建", "interpolation": "插值",
    "decimation": "抽取", "upsampling": "上采样",
    "downsampling": "下采样",
    "modulation": "调制", "demodulation": "解调",
    "amplitude": "幅度", "frequency": "频率",
    "baseband": "基带", "passband": "通带",
    "stopband": "阻带", "cutoff": "截止",
    "butterworth": "巴特沃斯", "chebyshev": "切比雪夫",
    "bessel": "贝塞尔", "elliptic": "椭圆",
    # ── 天文/地质 ──
    "accretion": "吸积", "protoplanetary": "原行星盘",
    "supergiant": "超巨星", "redgiant": "红巨星",
    "habitable": "宜居", "exoplanetary": "系外行星",
    "spectroscopic": "光谱", "photometric": "测光",
    "parallax": "视差", "parsec": "秒差距",
    "absolute": "绝对", "apparent": "视",
    "bolometric": "热辐射", "extinction": "消光",
    "interstellar": "星际", "intergalactic": "星系际",
    "cosmological": "宇宙学", "hubble": "哈勃",
    "redshift": "红移", "microwave": "微波",
    "background": "背景", "inflation": "暴涨",
    "nucleosynthesis": "核合成", "primordial": "原初",
    "baryon": "重子", "lepton": "轻子",
    "quark": "夸克", "gluon": "胶子",
    "boson": "玻色子", "fermion": "费米子",
    "hadron": "强子", "meson": "介子",
    "muon": "缪子", "neutrino": "中微子",
    "antimatter": "反物质", "annihilation": "湮灭",
    "pair": "对", "production": "产生",
    "higgs": "希格斯", "electroweak": "电弱",
    "chromodynamics": "色动力学", "asymptotic": "渐近",
    "confinement": "禁闭", "string": "弦",
    "supersymmetry": "超对称", "brane": "膜",
    "graviton": "引力子", "gravitational": "引力",
    "spacetime": "时空", "geodesic": "测地线",
    "singularity": "奇点", "horizon": "视界",
    "penrose": "彭罗斯", "hawking": "霍金",
    "schwarzschild": "施瓦西", "kerr": "克尔",
    "frame": "参考系", "dragging": "拖曳",
    "ligo": "LIGO", "gravitational": "引力波",
    "pulsar": "脉冲星", "magnetar": "磁星",
    "quasar": "类星体", "blazar": "耀变体",
    "active": "活动", "galactic": "星系",
    "nucleus": "核", "jet": "喷流",
    "accretion": "吸积", "disk": "盘",

}

# ── 后处理修正 ──
# 处理一些组合词的特殊翻译
PHRASE_DICT = {
    "black hole": "黑洞",
    "big bang": "大爆炸",
    "dark matter": "暗物质",
    "dark energy": "暗能量",
    "red shift": "红移",
    "white dwarf": "白矮星",
    "neutron star": "中子星",
    "main sequence": "主序",
    "hertzsprung russell": "赫罗图",
    "standard model": "标准模型",
    "wave function": "波函数",
    "uncertainty principle": "不确定性原理",
    "special relativity": "狭义相对论",
    "general relativity": "广义相对论",
    "ideal gas": "理想气体",
    "free energy": "自由能",
    "activation energy": "活化能",
    "le chatelier": "勒夏特列",
    "van der waals": "范德华",
    "ionic bond": "离子键",
    "covalent bond": "共价键",
    "metallic bond": "金属键",
    "hydrogen bond": "氢键",
    "lewis structure": "路易斯结构",
    "electron configuration": "电子构型",
    "periodic table": "元素周期表",
    "noble gas": "稀有气体",
    "transition metal": "过渡金属",
    "alkali metal": "碱金属",
    "oxidation state": "氧化态",
    "chain reaction": "链式反应",
    "half life": "半衰期",
    "binding energy": "结合能",
    "control rod": "控制棒",
    "fuel rod": "燃料棒",
    "heat exchanger": "换热器",
    "heat transfer": "传热",
    "mass transfer": "传质",
    "fluid mechanics": "流体力学",
    "solid mechanics": "固体力学",
    "finite element": "有限元",
    "boundary condition": "边界条件",
    "initial condition": "初始条件",
    "time complexity": "时间复杂度",
    "space complexity": "空间复杂度",
    "binary search": "二分搜索",
    "bubble sort": "冒泡排序",
    "merge sort": "归并排序",
    "quick sort": "快速排序",
    "insertion sort": "插入排序",
    "linked list": "链表",
    "hash table": "哈希表",
    "binary tree": "二叉树",
    "red black tree": "红黑树",
    "depth first": "深度优先",
    "breadth first": "广度优先",
    "dynamic programming": "动态规划",
    "divide and conquer": "分治法",
    "greedy algorithm": "贪心算法",
    "machine learning": "机器学习",
    "deep learning": "深度学习",
    "neural network": "神经网络",
    "decision tree": "决策树",
    "random forest": "随机森林",
    "support vector": "支持向量",
    "gradient descent": "梯度下降",
    "back propagation": "反向传播",
    "natural language": "自然语言",
    "computer vision": "计算机视觉",
    "operating system": "操作系统",
    "file system": "文件系统",
    "virtual memory": "虚拟内存",
    "context switch": "上下文切换",
    "dead lock": "死锁", "deadlock": "死锁",
    "race condition": "竞态条件",
    "relational database": "关系数据库",
    "object oriented": "面向对象",
    "functional programming": "函数式编程",
    "version control": "版本控制",
    "open source": "开源",
    "call stack": "调用栈",
    "garbage collection": "垃圾回收",
    "type system": "类型系统",
    "error handling": "错误处理",
    "unit test": "单元测试",
    "software engineering": "软件工程",
    "design pattern": "设计模式",
    "data structure": "数据结构",
    "data structures": "数据结构",
    "control system": "控制系统",
    "control systems": "控制系统",
    "power plant": "发电厂",
    "power system": "电力系统",
    "water treatment": "水处理",
    "waste water": "废水",
    "soil mechanics": "土力学",
    "rock mechanics": "岩石力学",
    "plate tectonics": "板块构造",
    "sea floor": "海底",
    "sea floor spreading": "海底扩张",
    "el nino": "厄尔尼诺",
    "la nina": "拉尼娜",
    "jet stream": "急流",
    "trade winds": "信风",
    "coriolis effect": "科里奥利效应",
    "citric acid cycle": "柠檬酸循环",
    "electron transport": "电子传递",
    "krebs cycle": "克雷布斯循环",
    "cell division": "细胞分裂",
    "cell cycle": "细胞周期",
    "gene expression": "基因表达",
    "natural selection": "自然选择",
    "genetic drift": "遗传漂变",
    "hardy weinberg": "哈迪-温伯格",
    "food chain": "食物链",
    "food web": "食物网",
    "carbon cycle": "碳循环",
    "nitrogen cycle": "氮循环",
    "water cycle": "水循环",
    "amino acid": "氨基酸",
    "nucleic acid": "核酸",
    "fatty acid": "脂肪酸",
}


def translate_name(name):
    """将英文知识点名称翻译为中文，支持中英混合文本"""
    
    # 1. 先查短语词典（长短语优先）
    sorted_phrases = sorted(PHRASE_DICT.items(), key=lambda x: -len(x[0]))
    for phrase, cn in sorted_phrases:
        if phrase in name.lower():
            name = re.sub(re.escape(phrase), cn, name, flags=re.IGNORECASE)
    
    # 2. CamelCase 拆分: "ATPSynthase" -> "ATP Synthase"
    name = re.sub(r'([a-z])([A-Z])', r'\1 \2', name)
    name = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', name)
    
    # 3. 在中英文边界处插入空格，使得后续能正确分词
    # "氨基酸分类And性质" -> "氨基酸分类 And 性质"
    name = re.sub(r'([\u4e00-\u9fff])([A-Za-z])', r'\1 \2', name)
    name = re.sub(r'([A-Za-z])([\u4e00-\u9fff])', r'\1 \2', name)
    
    # 4. 分词翻译
    words = re.split(r'\s+', name)
    translated_parts = []
    
    SKIP_WORDS = {"and", "or", "the", "of", "in", "on", "at", "to", "for", "with",
                  "by", "from", "an", "a", "its", "their", "via", "vs", "between"}
    
    for word in words:
        w_lower = word.lower().strip("(),.-:;'\"")
        if not w_lower:
            continue
        if w_lower in SKIP_WORDS:
            if w_lower == "and":
                translated_parts.append("与")
            # 其他连接词直接省略
            continue
        if w_lower in DICT:
            val = DICT[w_lower]
            if "/" in val:
                val = val.split("/")[0]
            translated_parts.append(val)
        elif re.match(r'^[\u4e00-\u9fff]', word):
            # 已经是中文
            translated_parts.append(word)
        else:
            # 保留原文
            translated_parts.append(word)
    
    # 5. 组合结果
    result = "".join(p for p in translated_parts if p)
    
    # 6. 清理
    result = re.sub(r'\s+', '', result)
    result = re.sub(r'与{2,}', '与', result)
    result = result.strip("与")
    
    # 如果完全没有中文，视为翻译失败
    cn_chars = len(re.findall(r'[\u4e00-\u9fff]', result))
    if cn_chars == 0:
        return name
    
    return result


KEEP_EN = {
    "DNA", "RNA", "tRNA", "mRNA", "rRNA", "ATP", "ADP", "AMP",
    "NAD", "NADH", "NADPH", "FAD", "FADH", "FADH2", "GTP", "GDP",
    "CPU", "GPU", "RAM", "ROM", "TCP", "IP", "HTTP", "DNS", "SQL",
    "USB", "LED", "LCD", "API", "REST", "HTML", "CSS", "IoT",
    "PCR", "CRISPR", "Cas", "GABA", "HIV", "AIDS",
    "NFA", "DFA", "SAT", "NP", "PSPACE", "WKB",
    "RLC", "pH", "pKa", "pKb", "IUPAC", "UV", "IR", "NMR",
    "GIS", "CAD", "IPv", "WiFi", "Git", "ATAC",
}


def should_translate_name(name):
    """仅翻译以英文为主、且含待译英文词的节点名"""
    if not name or not re.search(r'[A-Za-z]{3,}', name):
        return False
    cn = len(re.findall(r'[\u4e00-\u9fff]', name))
    en = len(re.findall(r'[A-Za-z]', name))
    if cn > en:
        return False
    words = re.findall(r'[A-Za-z]+', name)
    for w in words:
        if len(w) >= 3 and w not in KEEP_EN and w.upper() not in KEEP_EN:
            return True
    return False


def is_acceptable_translation(original, result):
    """拒绝中英乱拼的劣质翻译"""
    if not result or result == original:
        return False
    cn_chars = len(re.findall(r'[\u4e00-\u9fff]', result))
    if cn_chars < 2:
        return False
    bad_en = [
        w for w in re.findall(r'[A-Za-z]{4,}', result)
        if w.upper() not in KEEP_EN
    ]
    if bad_en:
        return False
    return True


def main():
    import sys
    map_only = '--map-only' in sys.argv
    print("📋 加载数据...")
    map_data = json.loads(MAP_DATA.read_text("utf-8"))
    
    # 统计
    en_count = 0
    translated_count = 0
    failed = []
    
    print("🔄 翻译节点名称...")
    for node in map_data["nodes"]:
        name = node["name"]
        if not should_translate_name(name):
            continue
        
        en_count += 1
        cn_name = translate_name(name)
        
        if is_acceptable_translation(name, cn_name):
            if "name_en" not in node:
                node["name_en"] = name
            node["name"] = cn_name
            translated_count += 1
        else:
            failed.append(name)
    
    print(f"   英文节点: {en_count}")
    print(f"   成功翻译: {translated_count}")
    print(f"   保留原文: {len(failed)}")
    
    if failed:
        print(f"\n   前 20 个未翻译:")
        for f in failed[:20]:
            print(f"     {f}")
    
    from datetime import datetime, timezone
    map_data.setdefault("stats", {})["translated_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # 保存
    print("\n📝 保存 knowledge-map-data.json...")
    MAP_DATA.write_text(json.dumps(map_data, ensure_ascii=False), "utf-8")

    if map_only:
        print("   (--map-only：跳过知识树 / nodes-metadata / _index 同步)")
        print("\n✅ 图谱数据已更新！")
        return
    
    # 同步更新知识树 JSON
    print("📝 更新知识树 JSON...")
    tree_updated = 0
    for f in TREES_DIR.glob("*.json"):
        if f.name == "_index.json":
            continue
        data = json.loads(f.read_text("utf-8"))
        changed = False
        for domain in data.get("domains", []):
            for node in domain.get("nodes", []):
                # 优先用 name_en 作为翻译源，否则用 name
                en_name = node.get("name_en", "") or node.get("name", "")
                if not should_translate_name(en_name):
                    continue
                cn = translate_name(en_name)
                if is_acceptable_translation(en_name, cn):
                    node["name_en"] = en_name
                    node["name"] = cn
                    changed = True
                    tree_updated += 1
        if changed:
            f.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")
    
    print(f"   更新了 {tree_updated} 个节点")
    
    # 更新 nodes-metadata.json
    meta_file = Path(__file__).parent.parent / "data" / "nodes-metadata.json"
    if meta_file.exists():
        print("📝 更新 nodes-metadata.json...")
        meta = json.loads(meta_file.read_text("utf-8"))
        nodes_list = meta.get("nodes", []) if isinstance(meta, dict) else meta
        meta_updated = 0
        for entry in nodes_list:
            if not isinstance(entry, dict):
                continue
            name = entry.get("name", "")
            if re.search(r'[A-Za-z]{3,}', name):
                cn = translate_name(name)
                if cn != name:
                    entry["name_en"] = name
                    entry["name"] = cn
                    meta_updated += 1
        meta_file.write_text(json.dumps(meta, ensure_ascii=False), "utf-8")
        print(f"   更新了 {meta_updated} 条")
    
    # 更新 _index.json
    idx_file = TREES_DIR / "_index.json"
    if idx_file.exists():
        print("📝 更新 _index.json...")
        idx = json.loads(idx_file.read_text("utf-8"))
        idx_updated = 0
        for entry in idx:
            name = entry.get("name", "")
            if re.search(r'[A-Za-z]{3,}', name):
                cn = translate_name(name)
                if cn != name:
                    entry["name_en"] = name
                    entry["name"] = cn
                    idx_updated += 1
        idx_file.write_text(json.dumps(idx, ensure_ascii=False, indent=2), "utf-8")
        print(f"   更新了 {idx_updated} 条")
    
    print("\n✅ 全部完成！")


if __name__ == "__main__":
    main()
