const VOCAB = [
  {en:'accept',zh:'接受',pos:'vt.',theme:'其他'},
  {en:'achieve',zh:'达到; 取得',pos:'vt.',theme:'其他'},
  {en:'add',zh:'增添; 增加 的; (用于疑问句、否定句)一些; 什么',pos:'vt.',theme:'其他'},
  {en:'advise',zh:'忠告; 劝告; 建议',pos:'vt.',theme:'其他'},
  {en:'allow',zh:'允许, 准允',pos:'vt.',theme:'其他'},
  {en:'appear',zh:'出现',pos:'vi.',theme:'其他'},
  {en:'arrive',zh:'到达; 达到',pos:'vi.',theme:'其他'},
  {en:'breathe',zh:'呼吸',pos:'vi.',theme:'其他'},
  {en:'buy',zh:'买',pos:'vt.',theme:'其他'},
  {en:'bye',zh:'再见',pos:'int.',theme:'其他'},
  {en:'chant',zh:'咏唱; 歌颂',pos:'vt.',theme:'其他'},
  {en:'choose',zh:'选择',pos:'vt.',theme:'其他'},
  {en:'clean',zh:'弄干净, 擦干净',pos:'vt.',theme:'其他'},
  {en:'collect',zh:'收集, 搜集',pos:'vt.',theme:'其他'},
  {en:'come',zh:'来, 来到',pos:'vi.',theme:'其他'},
  {en:'compare',zh:'比较; 对比',pos:'vt.',theme:'其他'},
  {en:'complete',zh:'完成; 结束',pos:'vt.',theme:'其他'},
  {en:'connect',zh:'连接; 把…联系起来',pos:'vt.',theme:'其他'},
  {en:'consider',zh:'考虑',pos:'vt.',theme:'其他'},
  {en:'count',zh:'数, 点数',pos:'vt.',theme:'其他'},
  {en:'create',zh:'创造; 造成',pos:'vt.',theme:'其他'},
  {en:'depend',zh:'依靠; 依赖; 指望; 取决于',pos:'vi.',theme:'其他'},
  {en:'describe',zh:'描写, 叙述',pos:'vt.',theme:'其他'},
  {en:'discuss',zh:'讨论, 议论',pos:'vt.',theme:'其他'},
  {en:'dismiss',zh:'解散; 解雇; 遣散',pos:'vt.',theme:'其他'},
  {en:'disturb',zh:'扰乱; 打扰',pos:'vt.',theme:'其他'},
  {en:'divide',zh:'分; 划分',pos:'vt.',theme:'其他'},
  {en:'eighth',zh:'第八',pos:'num.',theme:'其他'},
  {en:'encourage',zh:'鼓励',pos:'vt.',theme:'其他'},
  {en:'enjoy',zh:'欣赏; 享受……之乐趣; 喜欢',pos:'vt.',theme:'其他'},
  {en:'enter',zh:'进入',pos:'vt.',theme:'其他'},
  {en:'examine',zh:'检查; 诊察',pos:'vt.',theme:'其他'},
  {en:'excite',zh:'使兴奋, 使激动',pos:'vt.',theme:'其他'},
  {en:'expect',zh:'预料; 盼望',pos:'vt.',theme:'其他'},
  {en:'explain',zh:'解释; 说明',pos:'vt.',theme:'其他'},
  {en:'express',zh:'表达; 表示',pos:'vt.',theme:'其他'},
  {en:'feed',zh:'喂(养); 饲(养)',pos:'vt.',theme:'其他'},
  {en:'fetch',zh:'(去)取(物)来',pos:'vt.',theme:'其他'},
  {en:'fifth',zh:'第五',pos:'num.',theme:'其他'},
  {en:'fill',zh:'填空, 装满',pos:'vt.',theme:'其他'},
  {en:'find',zh:'找到, 发现, 感到',pos:'vt.',theme:'其他'},
  {en:'follow',zh:'跟随; 仿效; 跟得上',pos:'vt.',theme:'其他'},
  {en:'force',zh:'强迫;迫使',pos:'vt.',theme:'其他'},
  {en:'fourth',zh:'四十',pos:'num.',theme:'其他'},
  {en:'freeze',zh:'结冰',pos:'vi.',theme:'其他'},
  {en:'go',zh:'去; 走',pos:'vi.',theme:'其他'},
  {en:'good-bye',zh:'再见; 再会',pos:'int.',theme:'其他'},
  {en:'guess',zh:'猜',pos:'vi.',theme:'其他'},
  {en:'happen',zh:'(偶然)发生',pos:'vi.',theme:'其他'},
  {en:'have',zh:'有; 吃; 喝; 进行; 经受',pos:'vt.',theme:'其他'},
  {en:'hello',zh:'沈．喂; 你好(用于打招呼、问',pos:'int.',theme:'其他'},
  {en:'hit',zh:'打, 撞, 击中',pos:'vt.',theme:'其他'},
  {en:'hurry',zh:'赶快, 急忙',pos:'vi.',theme:'其他'},
  {en:'imagine',zh:'想象; 设想',pos:'vt.',theme:'其他'},
  {en:'improve',zh:'改进, 更新',pos:'vt.',theme:'其他'},
  {en:'include',zh:'包含; 包括',pos:'vt.',theme:'其他'},
  {en:'insist',zh:'坚持; 坚持认为',pos:'vi.',theme:'其他'},
  {en:'introduce',zh:'介绍',pos:'vt.',theme:'其他'},
  {en:'invent',zh:'发明; 创造',pos:'vt.',theme:'其他'},
  {en:'invite',zh:'邀请, 招待',pos:'vt.',theme:'其他'},
  {en:'lay',zh:'放; 搁',pos:'vt.',theme:'其他'},
  {en:'lead',zh:'领导; 带领',pos:'vt.',theme:'其他'},
  {en:'lend',zh:'借(出), 把……借给',pos:'vt.',theme:'其他'},
  {en:'live',zh:'生活; 居住; 活着',pos:'vi.',theme:'其他'},
  {en:'master',zh:'精通; 掌握',pos:'vt.',theme:'其他'},
  {en:'mean',zh:'意思是, 意指',pos:'vt.',theme:'其他'},
  {en:'meet',zh:'遇见, 见到',pos:'vt.',theme:'其他'},
  {en:'miss',zh:'失去, 错过, 思念',pos:'vt.',theme:'其他'},
  {en:'murder',zh:'谋杀',pos:'vt.',theme:'其他'},
  {en:'ninth',zh:'第九',pos:'num.',theme:'其他'},
  {en:'nod',zh:'点头 外的',pos:'vi.',theme:'其他'},
  {en:'order',zh:'定购, 订货; 点菜',pos:'vt.',theme:'其他'},
  {en:'prepare',zh:'准备; 预备; 调制; 配制',pos:'vt.',theme:'其他'},
  {en:'prevent',zh:'阻止; 防止; 预防',pos:'vt.',theme:'其他'},
  {en:'print',zh:'印刷',pos:'vt.',theme:'其他'},
  {en:'produce',zh:'生产; 制造',pos:'vt.',theme:'其他'},
  {en:'pronounce',zh:'发音',pos:'vt.',theme:'其他'},
  {en:'protect',zh:'保护',pos:'vt.',theme:'其他'},
  {en:'prove',zh:'证明',pos:'vt.',theme:'其他'},
  {en:'provide',zh:'提供',pos:'vt.',theme:'其他'},
  {en:'punish',zh:'惩罚; 处罚',pos:'vt.',theme:'其他'},
  {en:'raise',zh:'使升高; 饲养',pos:'vt.',theme:'其他'},
  {en:'realise',zh:'认识到, 实现',pos:'vt.',theme:'其他'},
  {en:'refuse',zh:'拒绝, 不愿',pos:'vt.',theme:'其他'},
  {en:'remain',zh:'余下; 留下',pos:'vt.',theme:'其他'},
  {en:'repeat',zh:'重说; 重做',pos:'vt.',theme:'其他'},
  {en:'require',zh:'需求; 要求',pos:'vt.',theme:'其他'},
  {en:'retell',zh:'重讲; 重复; 复述',pos:'vt.',theme:'其他'},
  {en:'rush',zh:'冲, 奔跑',pos:'vi.',theme:'其他'},
  {en:'serve',zh:'招待(顾客等), 服',pos:'vt.',theme:'其他'},
  {en:'seventh',zh:'第七',pos:'num.',theme:'其他'},
  {en:'share',zh:'分享; 共同使用',pos:'vt.',theme:'其他'},
  {en:'sixth',zh:'第六',pos:'num.',theme:'其他'},
  {en:'sort',zh:'把……分类, 拣选',pos:'vt.',theme:'其他'},
  {en:'sound',zh:'听起来; (使)发出声音',pos:'vi. & vt.',theme:'其他'},
  {en:'steal',zh:'偷; 窃取',pos:'vt.',theme:'其他'},
  {en:'stick',zh:'粘住, 钉住; 坚持',pos:'vi.',theme:'其他'},
  {en:'succeed',zh:'成功',pos:'vi.',theme:'其他'},
  {en:'suggest',zh:'建议, 提议',pos:'vt.',theme:'其他'},
  {en:'suppose',zh:'猜想, 假定, 料想 物前)',pos:'vt.',theme:'其他'},
  {en:'surprise',zh:'使惊奇, 使诧异',pos:'vt.',theme:'其他'},
  {en:'tenth',zh:'第十',pos:'num.',theme:'其他'},
  {en:'thank',zh:'感谢, 致谢, 道谢',pos:'vt.',theme:'其他'},
  {en:'the',zh:'这(那)个, 这(那)些(用于特定人或',pos:'art.',theme:'其他'},
  {en:'there',zh:'那!你瞧(表示引起注意)',pos:'int.',theme:'其他'},
  {en:'tie',zh:'(用绳, 线)系, 拴, 扎',pos:'vt.',theme:'其他'},
  {en:'translate',zh:'翻译',pos:'vt.',theme:'其他'},
  {en:'trouble',zh:'使苦恼, 使忧虑, 使麻烦',pos:'vt.',theme:'其他'},
  {en:'trust',zh:'相信, 信任, 信赖',pos:'vt.',theme:'其他'},
  {en:'twelfth',zh:'第十二',pos:'num.',theme:'其他'},
  {en:'twentieth',zh:'第二十',pos:'num.',theme:'其他'},
  {en:'wait',zh:'等, 等候',pos:'vi.',theme:'其他'},
  {en:'warn',zh:'警告, 预先通知',pos:'vt.',theme:'其他'},
  {en:'weigh',zh:'称……的重量, 重(若干)',pos:'vt.',theme:'其他'},
  {en:'wound',zh:'伤, 伤害',pos:'vt.',theme:'其他'},
  {en:'ability',zh:'能力; 才能',pos:'n.',theme:'其他名词'},
  {en:'accent',zh:'口音; 音调',pos:'n.',theme:'其他名词'},
  {en:'accident',zh:'事故, 意外的事',pos:'n.',theme:'其他名词'},
  {en:'ache',zh:'痛; 疼痛',pos:'vi. & n.',theme:'其他名词'},
  {en:'act',zh:'演出, 行动',pos:'n.',theme:'其他名词'},
  {en:'action',zh:'行动',pos:'n.',theme:'其他名词'},
  {en:'activity',zh:'活动',pos:'n.',theme:'其他名词'},
  {en:'address',zh:'地址',pos:'n.',theme:'其他名词'},
  {en:'advantage',zh:'优点; 好处',pos:'n.',theme:'其他名词'},
  {en:'advertisement',zh:'广告',pos:'n.',theme:'其他名词'},
  {en:'advice',zh:'忠告; 劝告; 建议',pos:'n.',theme:'其他名词'},
  {en:'age',zh:'年龄; 时代',pos:'n.',theme:'其他名词'},
  {en:'agreement',zh:'同意; 一致; 协定',pos:'n.',theme:'其他名词'},
  {en:'air',zh:'空气; 大气',pos:'n.',theme:'其他名词'},
  {en:'airline',zh:'航空公司',pos:'n.',theme:'其他名词'},
  {en:'airplane',zh:'(美)飞机',pos:'n.',theme:'其他名词'},
  {en:'america',zh:'美国; 美洲',pos:'n.',theme:'其他名词'},
  {en:'anybody',zh:'任何人, 无论谁',pos:'pron.',theme:'其他名词'},
  {en:'anyone',zh:'任何人, 无论谁',pos:'pron.',theme:'其他名词'},
  {en:'anything',zh:'什么事(物); 任何事(物)',pos:'pron.',theme:'其他名词'},
  {en:'april',zh:'四月',pos:'n.',theme:'其他名词'},
  {en:'area',zh:'面积; 地域; 区域; 范围; 领域',pos:'n.',theme:'其他名词'},
  {en:'article',zh:'文章; 东西; 冠词',pos:'n.',theme:'其他名词'},
  {en:'asia',zh:'亚洲',pos:'n.',theme:'其他名词'},
  {en:'attention',zh:'关心; 注意',pos:'n.',theme:'其他名词'},
  {en:'august',zh:'八月',pos:'n.',theme:'其他名词'},
  {en:'australia',zh:'澳洲; 澳大利亚 此外',pos:'n.',theme:'其他名词'},
  {en:'background',zh:'背景 的',pos:'n.',theme:'其他名词'},
  {en:'bag',zh:'书包; 提包; 袋子',pos:'n.',theme:'其他名词'},
  {en:'balloon',zh:'气球',pos:'n.',theme:'其他名词'},
  {en:'bamboo',zh:'竹',pos:'n.',theme:'其他名词'},
  {en:'bank',zh:'(河、海、湖的)岸, 堤; 银行',pos:'n.',theme:'其他名词'},
  {en:'baseball',zh:'棒球',pos:'n.',theme:'其他名词'},
  {en:'basket',zh:'篮子',pos:'n.',theme:'其他名词'},
  {en:'beach',zh:'海滨, 海滩',pos:'n.',theme:'其他名词'},
  {en:'behaviour',zh:'行为, 举止',pos:'n.',theme:'其他名词'},
  {en:'bell',zh:'钟, 铃; 钟(铃)声; 钟形物',pos:'n.',theme:'其他名词'},
  {en:'bill',zh:'帐单; 法案, 议案; (美)钞票, 纸币',pos:'n.',theme:'其他名词'},
  {en:'birth',zh:'出生; 诞生',pos:'n.',theme:'其他名词'},
  {en:'birthday',zh:'生日',pos:'n.',theme:'其他名词'},
  {en:'bit',zh:'一点, 一些, 少量',pos:'n.',theme:'其他名词'},
  {en:'black',zh:'黑色',pos:'n.',theme:'其他名词'},
  {en:'board',zh:'木板; 布告牌; 委员会; (政府的)部',pos:'n.',theme:'其他名词'},
  {en:'book',zh:'书; 本子',pos:'n.',theme:'其他名词'},
  {en:'bottom',zh:'底部; 底',pos:'n.',theme:'其他名词'},
  {en:'box',zh:'盒子, 箱子',pos:'n.',theme:'其他名词'},
  {en:'boy',zh:'男孩',pos:'n.',theme:'其他名词'},
  {en:'breath',zh:'气息; 呼吸',pos:'n.',theme:'其他名词'},
  {en:'brown',zh:'褐色, 棕色',pos:'n.',theme:'其他名词'},
  {en:'building',zh:'建筑物; 房屋; 大楼',pos:'n.',theme:'其他名词'},
  {en:'butterfly',zh:'蝴蝶',pos:'n.',theme:'其他名词'},
  {en:'cabbage',zh:'卷心菜; 洋白菜',pos:'n.',theme:'其他名词'},
  {en:'camel',zh:'骆驼',pos:'n.',theme:'其他名词'},
  {en:'camp',zh:'(夏令)营',pos:'n.',theme:'其他名词'},
  {en:'canada',zh:'加拿大',pos:'n.',theme:'其他名词'},
  {en:'cancer',zh:'癌',pos:'n.',theme:'其他名词'},
  {en:'candle',zh:'蜡烛',pos:'n.',theme:'其他名词'},
  {en:'cap',zh:'(无檐的或仅在前面有檐的)帽子',pos:'n.',theme:'其他名词'},
  {en:'captain',zh:'(海军)上校; 船长; 舰长; 队长',pos:'n.',theme:'其他名词'},
  {en:'card',zh:'卡片; 名片; 纸牌',pos:'n.',theme:'其他名词'},
  {en:'care',zh:'照料; 小心',pos:'n.',theme:'其他名词'},
  {en:'cause',zh:'原因; 起因',pos:'n.',theme:'其他名词'},
  {en:'cd',zh:'光盘',pos:'n.',theme:'其他名词'},
  {en:'ceiling',zh:'天花板; 顶棚',pos:'n.',theme:'其他名词'},
  {en:'cent',zh:'美分(100',pos:'n.',theme:'其他名词'},
  {en:'centre',zh:'中心, 中央',pos:'n.',theme:'其他名词'},
  {en:'chance',zh:'机会, 可能性',pos:'n.',theme:'其他名词'},
  {en:'change',zh:'零钱; 找头．改变, 变化',pos:'n.',theme:'其他名词'},
  {en:'check',zh:'检查; 批改',pos:'n.',theme:'其他名词'},
  {en:'cheer',zh:'欢呼; 喝彩',pos:'n. & vi.',theme:'其他名词'},
  {en:'chess',zh:'棋',pos:'n.',theme:'其他名词'},
  {en:'chest',zh:'箱子; 盒子; 胸部',pos:'n.',theme:'其他名词'},
  {en:'china',zh:'中国',pos:'n.',theme:'其他名词'},
  {en:'chopsticks',zh:'筷子',pos:'n.',theme:'其他名词'},
  {en:'christmas',zh:'圣诞节(12 月 25)',pos:'n.',theme:'其他名词'},
  {en:'church',zh:'教堂; 教会',pos:'n.',theme:'其他名词'},
  {en:'cinema',zh:'电影院; 电影',pos:'n.',theme:'其他名词'},
  {en:'circle',zh:'圆圈',pos:'n.',theme:'其他名词'},
  {en:'clap',zh:'拍手; 鼓掌',pos:'vi. & n.',theme:'其他名词'},
  {en:'classmate',zh:'同班同学',pos:'n.',theme:'其他名词'},
  {en:'clock',zh:'钟',pos:'n.',theme:'其他名词'},
  {en:'club',zh:'俱乐部',pos:'n.',theme:'其他名词'},
  {en:'coach',zh:'教练; 马车; 长途车',pos:'n.',theme:'其他名词'},
  {en:'coal',zh:'煤; 煤块',pos:'n.',theme:'其他名词'},
  {en:'coast',zh:'海岸; 海滨',pos:'n.',theme:'其他名词'},
  {en:'coin',zh:'硬币',pos:'n.',theme:'其他名词'},
  {en:'coke',zh:'可口可乐',pos:'n.',theme:'其他名词'},
  {en:'colour',zh:'颜色',pos:'n.',theme:'其他名词'},
  {en:'communication',zh:'交际; 交往; 通',pos:'n.',theme:'其他名词'},
  {en:'competition',zh:'比赛; 竞赛',pos:'n.',theme:'其他名词'},
  {en:'composition',zh:'作文; 作曲',pos:'n.',theme:'其他名词'},
  {en:'condition',zh:'条件; 状况',pos:'n.',theme:'其他名词'},
  {en:'conference',zh:'(正式的)会议',pos:'n.',theme:'其他名词'},
  {en:'control',zh:'控制',pos:'vt. & n.',theme:'其他名词'},
  {en:'conversation',zh:'谈话, 交谈',pos:'n.',theme:'其他名词'},
  {en:'cooker',zh:'炊具(锅、炉灶、烤炉等)',pos:'n.',theme:'其他名词'},
  {en:'copy',zh:'抄本, 副本; 一本(份, 册……)',pos:'n.',theme:'其他名词'},
  {en:'corner',zh:'角; 角落; 拐角',pos:'n.',theme:'其他名词'},
  {en:'cotton',zh:'棉花',pos:'n.',theme:'其他名词'},
  {en:'countryside',zh:'乡下, 农村',pos:'n.',theme:'其他名词'},
  {en:'couple',zh:'夫妇; 一对',pos:'n.',theme:'其他名词'},
  {en:'courage',zh:'勇气; 胆略',pos:'n.',theme:'其他名词'},
  {en:'cover',zh:'盖子; 罩',pos:'n.',theme:'其他名词'},
  {en:'crayon',zh:'蜡笔; 蜡笔画',pos:'n.',theme:'其他名词'},
  {en:'cross',zh:'十字形的东西',pos:'n.',theme:'其他名词'},
  {en:'cry',zh:'叫喊; 哭声',pos:'n.',theme:'其他名词'},
  {en:'dad',zh:'(口语)爸爸, 爹爹',pos:'n.',theme:'其他名词'},
  {en:'danger',zh:'危险',pos:'n.',theme:'其他名词'},
  {en:'date',zh:'日期; 约会',pos:'n.',theme:'其他名词'},
  {en:'day',zh:'天; 日; 白天',pos:'n.',theme:'其他名词'},
  {en:'december',zh:'十二月',pos:'n.',theme:'其他名词'},
  {en:'decision',zh:'决定; 决心',pos:'n.',theme:'其他名词'},
  {en:'dentist',zh:'牙科医生',pos:'n.',theme:'其他名词'},
  {en:'development',zh:'发展; 发达; 发育; 开',pos:'n.',theme:'其他名词'},
  {en:'dialogue',zh:'对话',pos:'n.',theme:'其他名词'},
  {en:'diary',zh:'日记; 日记簿',pos:'n.',theme:'其他名词'},
  {en:'difference',zh:'不同',pos:'n.',theme:'其他名词'},
  {en:'difficulty',zh:'困难; 费力',pos:'n.',theme:'其他名词'},
  {en:'discovery',zh:'发现',pos:'n.',theme:'其他名词'},
  {en:'discussion',zh:'讨论, 辩论',pos:'n.',theme:'其他名词'},
  {en:'disease',zh:'病, 疾病',pos:'n.',theme:'其他名词'},
  {en:'dish',zh:'盘, 碟; 盘装菜; 盘形物',pos:'n.',theme:'其他名词'},
  {en:'doll',zh:'玩偶, 玩具娃娃',pos:'n.',theme:'其他名词'},
  {en:'dollar',zh:'元(美国、加拿大、澳大利亚等国货',pos:'n.',theme:'其他名词'},
  {en:'doubt',zh:'怀疑; 疑惑',pos:'n. & vt.',theme:'其他名词'},
  {en:'drawer',zh:'抽屉',pos:'n.',theme:'其他名词'},
  {en:'dream',zh:'梦, 英语',pos:'n. & vt.',theme:'其他名词'},
  {en:'drug',zh:'药; 药物; 毒品',pos:'n.',theme:'其他名词'},
  {en:'drum',zh:'鼓',pos:'n.',theme:'其他名词'},
  {en:'dumpling',zh:'饺子',pos:'n.',theme:'其他名词'},
  {en:'edge',zh:'边缘',pos:'n.',theme:'其他名词'},
  {en:'effort',zh:'努力; 艰难的尝试',pos:'n.',theme:'其他名词'},
  {en:'enemy',zh:'敌人; 敌军',pos:'n.',theme:'其他名词'},
  {en:'england',zh:'英格兰',pos:'n.',theme:'其他名词'},
  {en:'europe',zh:'欧洲',pos:'n.',theme:'其他名词'},
  {en:'everybody',zh:'每人, 人人',pos:'pron.',theme:'其他名词'},
  {en:'everyone',zh:'每人; 人人',pos:'pron.',theme:'其他名词'},
  {en:'everything',zh:'每件事, 事事',pos:'pron.',theme:'其他名词'},
  {en:'examination',zh:'考试, 测试',pos:'n.',theme:'其他名词'},
  {en:'example',zh:'例子; 榜样',pos:'n.',theme:'其他名词'},
  {en:'excuse',zh:'借口; 辩解',pos:'n.',theme:'其他名词'},
  {en:'exercise',zh:'锻炼, 做操; 练习',pos:'n.',theme:'其他名词'},
  {en:'experience',zh:'经验; 经历',pos:'n.',theme:'其他名词'},
  {en:'fact',zh:'事实, 现实',pos:'n.',theme:'其他名词'},
  {en:'farmer',zh:'农民',pos:'n.',theme:'其他名词'},
  {en:'fear',zh:'害怕; 恐惧; 担忧',pos:'n.',theme:'其他名词'},
  {en:'february',zh:'二月',pos:'n.',theme:'其他名词'},
  {en:'feeling',zh:'感情; 感觉',pos:'n.',theme:'其他名词'},
  {en:'fire',zh:'火; 火炉; 火灾',pos:'n.',theme:'其他名词'},
  {en:'fisherman',zh:'渔民; 钓鱼健身者',pos:'n.',theme:'其他名词'},
  {en:'flag',zh:'旗; 标志',pos:'n.',theme:'其他名词'},
  {en:'flat',zh:'楼中一套房间; 公寓(常用',pos:'n.',theme:'其他名词'},
  {en:'flu',zh:'流行性感冒',pos:'n.',theme:'其他名词'},
  {en:'foreigner',zh:'外国人',pos:'n.',theme:'其他名词'},
  {en:'form',zh:'表格; 形式; 结构',pos:'n.',theme:'其他名词'},
  {en:'fox',zh:'狐狸',pos:'n.',theme:'其他名词'},
  {en:'friday',zh:'星期五',pos:'n.',theme:'其他名词'},
  {en:'fridge',zh:'冰箱',pos:'n.',theme:'其他名词'},
  {en:'friendship',zh:'友谊, 友情 语)好极了, 很好',pos:'n.',theme:'其他名词'},
  {en:'frog',zh:'青蛙',pos:'n.',theme:'其他名词'},
  {en:'fun',zh:'有趣的事, 娱乐, 玩笑',pos:'n.',theme:'其他名词'},
  {en:'future',zh:'将来',pos:'n.',theme:'其他名词'},
  {en:'gate',zh:'大门',pos:'n.',theme:'其他名词'},
  {en:'gentleman',zh:'绅士; 先生',pos:'n.',theme:'其他名词'},
  {en:'giraffe',zh:'长颈鹿',pos:'n.',theme:'其他名词'},
  {en:'girl',zh:'女孩',pos:'n.',theme:'其他名词'},
  {en:'glove',zh:'手套',pos:'n.',theme:'其他名词'},
  {en:'goal',zh:'(足球)球门; 目标',pos:'n.',theme:'其他名词'},
  {en:'goat',zh:'山羊',pos:'n.',theme:'其他名词'},
  {en:'god',zh:'神; (大写)上帝 的',pos:'n.',theme:'其他名词'},
  {en:'gold',zh:'黄金',pos:'n.',theme:'其他名词'},
  {en:'goose',zh:'鹅',pos:'n.',theme:'其他名词'},
  {en:'grammar',zh:'语法',pos:'n.',theme:'其他名词'},
  {en:'grandchild',zh:'(外)孙或孙女; 孙辈',pos:'n.',theme:'其他名词'},
  {en:'granddaughter',zh:'(外)孙女',pos:'n.',theme:'其他名词'},
  {en:'grandparents',zh:'祖父母; 外祖父母',pos:'n.',theme:'其他名词'},
  {en:'grandson',zh:'(外)孙子',pos:'n.',theme:'其他名词'},
  {en:'granny',zh:'老奶奶; 祖母; 外婆',pos:'n.',theme:'其他名词'},
  {en:'greeting',zh:'祝贺; 问候',pos:'n.',theme:'其他名词'},
  {en:'ground',zh:'地面',pos:'n.',theme:'其他名词'},
  {en:'group',zh:'组, 群',pos:'n.',theme:'其他名词'},
  {en:'guard',zh:'警戒; 保护装置',pos:'n.',theme:'其他名词'},
  {en:'guest',zh:'客人; 宾客',pos:'n.',theme:'其他名词'},
  {en:'guitar',zh:'吉他',pos:'n.',theme:'其他名词'},
  {en:'gun',zh:'枪; 炮',pos:'n.',theme:'其他名词'},
  {en:'gymnasium',zh:'体操; 体育馆; 健身房',pos:'n.',theme:'其他名词'},
  {en:'habit',zh:'习惯; 习性',pos:'n.',theme:'其他名词'},
  {en:'hall',zh:'大堂; 会堂; 礼堂',pos:'n.',theme:'其他名词'},
  {en:'ham',zh:'火腿',pos:'n.',theme:'其他名词'},
  {en:'handbag',zh:'女用皮包; 手提包',pos:'n.',theme:'其他名词'},
  {en:'handwriting',zh:'书法',pos:'n.',theme:'其他名词'},
  {en:'hate',zh:'恨, 讨厌',pos:'vt. & n.',theme:'其他名词'},
  {en:'he',zh:'他',pos:'pron.',theme:'其他名词'},
  {en:'heat',zh:'热',pos:'n.',theme:'其他名词'},
  {en:'heaven',zh:'天; 天空',pos:'n.',theme:'其他名词'},
  {en:'help',zh:'帮助, 帮忙',pos:'n. & vt.',theme:'其他名词'},
  {en:'hen',zh:'母鸡',pos:'n.',theme:'其他名词'},
  {en:'her',zh:'她(宾格), 她的',pos:'pron.',theme:'其他名词'},
  {en:'hers',zh:'她的',pos:'pron.',theme:'其他名词'},
  {en:'herself',zh:'她自己',pos:'pron.',theme:'其他名词'},
  {en:'him',zh:'他(宾格)',pos:'pron.',theme:'其他名词'},
  {en:'himself',zh:'他自己',pos:'pron.',theme:'其他名词'},
  {en:'his',zh:'他的',pos:'pron.',theme:'其他名词'},
  {en:'hobby',zh:'业余爱好; 奢好',pos:'n.',theme:'其他名词'},
  {en:'hometown',zh:'故乡',pos:'n.',theme:'其他名词'},
  {en:'honour',zh:'荣誉; 敬意',pos:'n.',theme:'其他名词'},
  {en:'hot dog',zh:'热狗(红肠面包)',pos:'n.',theme:'其他名词'},
  {en:'hotel',zh:'旅馆, 饭店, 宾馆',pos:'n.',theme:'其他名词'},
  {en:'housework',zh:'家务劳动',pos:'n.',theme:'其他名词'},
  {en:'ice-cream',zh:'冰淇淋',pos:'n.',theme:'其他名词'},
  {en:'idea',zh:'主意, 意见, 打算, 想法',pos:'n.',theme:'其他名词'},
  {en:'illness',zh:'疾病',pos:'n.',theme:'其他名词'},
  {en:'india',zh:'印度',pos:'n.',theme:'其他名词'},
  {en:'ink',zh:'墨水; 油墨',pos:'n.',theme:'其他名词'},
  {en:'instruction',zh:'说明, 须知; 教导',pos:'n.',theme:'其他名词'},
  {en:'intention',zh:'意图; 目的',pos:'n.',theme:'其他名词'},
  {en:'interest',zh:'兴趣, 趣味; 利息',pos:'n.',theme:'其他名词'},
  {en:'interview',zh:'采访; 会见; 面试',pos:'n. & vt.',theme:'其他名词'},
  {en:'introduction',zh:'介绍; 引进',pos:'n.',theme:'其他名词'},
  {en:'iron',zh:'(不可数名词)铁; 熨斗',pos:'n.',theme:'其他名词'},
  {en:'it',zh:'它',pos:'pron.',theme:'其他名词'},
  {en:'its',zh:'它的',pos:'pron.',theme:'其他名词'},
  {en:'itself',zh:'它自己',pos:'pron.',theme:'其他名词'},
  {en:'january',zh:'一月',pos:'n.',theme:'其他名词'},
  {en:'japan',zh:'日本',pos:'n.',theme:'其他名词'},
  {en:'jeans',zh:'牛仔裤',pos:'n.',theme:'其他名词'},
  {en:'joke',zh:'笑话',pos:'n.',theme:'其他名词'},
  {en:'joy',zh:'欢乐; 高兴; 乐趣',pos:'n.',theme:'其他名词'},
  {en:'july',zh:'七月',pos:'n.',theme:'其他名词'},
  {en:'june',zh:'六月',pos:'n.',theme:'其他名词'},
  {en:'keyboard',zh:'键盘',pos:'n.',theme:'其他名词'},
  {en:'kiss',zh:'吻; 亲吻',pos:'n. & vt.',theme:'其他名词'},
  {en:'kite',zh:'风筝',pos:'n.',theme:'其他名词'},
  {en:'laboratory',zh:'实验室',pos:'n.',theme:'其他名词'},
  {en:'labour',zh:'劳动',pos:'n.',theme:'其他名词'},
  {en:'lady',zh:'女士, 夫人',pos:'n.',theme:'其他名词'},
  {en:'lamb',zh:'羔羊',pos:'n.',theme:'其他名词'},
  {en:'lamp',zh:'灯; 灯油',pos:'n.',theme:'其他名词'},
  {en:'language',zh:'语言',pos:'n.',theme:'其他名词'},
  {en:'laugh',zh:'/',pos:'n.',theme:'其他名词'},
  {en:'lemonade',zh:'柠檬水',pos:'n.',theme:'其他名词'},
  {en:'level',zh:'水平线; 水平',pos:'n.',theme:'其他名词'},
  {en:'license',zh:'执照; 许可证',pos:'n.',theme:'其他名词'},
  {en:'life',zh:'生命; 生涯; 生活; 人生; 生物',pos:'n.',theme:'其他名词'},
  {en:'light',zh:'光, 光亮; 灯, 灯光',pos:'n.',theme:'其他名词'},
  {en:'line',zh:'绳索, 线, 排, 行, 线路',pos:'n.',theme:'其他名词'},
  {en:'list',zh:'一览表, 清单',pos:'n.',theme:'其他名词'},
  {en:'london',zh:'伦敦',pos:'n.',theme:'其他名词'},
  {en:'lot',zh:'许多, 好些',pos:'n.',theme:'其他名词'},
  {en:'love',zh:'爱; 热爱; 很喜欢',pos:'n. & vt.',theme:'其他名词'},
  {en:'luck',zh:'运气, 好运',pos:'n.',theme:'其他名词'},
  {en:'madam / madame',zh:'夫人, 女士',pos:'n.',theme:'其他名词'},
  {en:'man',zh:'成年男人; 人, 人类',pos:'n.',theme:'其他名词'},
  {en:'march',zh:'三月',pos:'n.',theme:'其他名词'},
  {en:'marriage',zh:'结婚; 婚姻',pos:'n.',theme:'其他名词'},
  {en:'mathematics',zh:'数学',pos:'n.',theme:'其他名词'},
  {en:'may',zh:'五月',pos:'n.',theme:'其他名词'},
  {en:'me',zh:'我(宾格)',pos:'pron.',theme:'其他名词'},
  {en:'meaning',zh:'意思, 含义',pos:'n.',theme:'其他名词'},
  {en:'member',zh:'成员, 会员',pos:'n.',theme:'其他名词'},
  {en:'memory',zh:'回忆, 记忆',pos:'n.',theme:'其他名词'},
  {en:'mention',zh:'提及, 提到, 记载',pos:'n. & vt.',theme:'其他名词'},
  {en:'metal',zh:'金属',pos:'n.',theme:'其他名词'},
  {en:'method',zh:'方法; 办法',pos:'n.',theme:'其他名词'},
  {en:'metre',zh:'米, 公尺',pos:'n.',theme:'其他名词'},
  {en:'mind',zh:'思想; 想法',pos:'n.',theme:'其他名词'},
  {en:'mine',zh:'我的(物主代词)',pos:'pron.',theme:'其他名词'},
  {en:'mirror',zh:'镜子',pos:'n.',theme:'其他名词'},
  {en:'model',zh:'模型, 原形; 范例; 模范',pos:'n.',theme:'其他名词'},
  {en:'monday',zh:'星期一',pos:'n.',theme:'其他名词'},
  {en:'money',zh:'钱; 货币',pos:'n.',theme:'其他名词'},
  {en:'monitor',zh:'(班级内的)班长; 纠察生监视',pos:'n.',theme:'其他名词'},
  {en:'motorcycle',zh:'摩托车',pos:'n.',theme:'其他名词'},
  {en:'mun',zh:'妈妈',pos:'n.',theme:'其他名词'},
  {en:'my',zh:'我的',pos:'pron.',theme:'其他名词'},
  {en:'myself',zh:'我自己',pos:'pron.',theme:'其他名词'},
  {en:'name',zh:'名字, 姓名, 名称',pos:'n.',theme:'其他名词'},
  {en:'need',zh:'需要, 需求',pos:'n.',theme:'其他名词'},
  {en:'neighbour',zh:'邻居, 邻人',pos:'n.',theme:'其他名词'},
  {en:'nobody',zh:'没有人, 谁也不',pos:'pron.',theme:'其他名词'},
  {en:'noise',zh:'声音, 噪声, 喧闹声',pos:'n.',theme:'其他名词'},
  {en:'noon',zh:'中午, 正午',pos:'n.',theme:'其他名词'},
  {en:'note',zh:'便条; 笔记, 注释; 钞票; 纸币; 音符',pos:'n.',theme:'其他名词'},
  {en:'nothing',zh:'没有东西, 没有什么',pos:'pron.',theme:'其他名词'},
  {en:'notice',zh:'布告, 通告; 注意',pos:'n.',theme:'其他名词'},
  {en:'november',zh:'十二月',pos:'n.',theme:'其他名词'},
  {en:'object',zh:'物, 物体; 宾语',pos:'n.',theme:'其他名词'},
  {en:'october',zh:'十月',pos:'n.',theme:'其他名词'},
  {en:'offer',zh:'提供, 建议',pos:'vt. & n.',theme:'其他名词'},
  {en:'oneself',zh:'自己, 自身',pos:'pron.',theme:'其他名词'},
  {en:'operation',zh:'手术; 操作',pos:'n.',theme:'其他名词'},
  {en:'other',zh:'别人, 别的东西',pos:'pron.',theme:'其他名词'},
  {en:'our',zh:'我们的',pos:'pron.',theme:'其他名词'},
  {en:'ours',zh:'我们的',pos:'pron.',theme:'其他名词'},
  {en:'ourselves',zh:'我们自己',pos:'pron.',theme:'其他名词'},
  {en:'outside',zh:'外面',pos:'n.',theme:'其他名词'},
  {en:'overcoat',zh:'大衣',pos:'n.',theme:'其他名词'},
  {en:'owner',zh:'物主, 所有人',pos:'n.',theme:'其他名词'},
  {en:'package',zh:'一包; 一袋; 一盒',pos:'n.',theme:'其他名词'},
  {en:'page',zh:'页, 页码',pos:'n.',theme:'其他名词'},
  {en:'palace',zh:'宫, 宫殿',pos:'n.',theme:'其他名词'},
  {en:'pancake',zh:'薄煎饼',pos:'n.',theme:'其他名词'},
  {en:'panda',zh:'熊猫',pos:'n.',theme:'其他名词'},
  {en:'paper',zh:'纸; 报纸',pos:'n.',theme:'其他名词'},
  {en:'pardon',zh:'原谅, 宽恕, 对不起',pos:'n.',theme:'其他名词'},
  {en:'park',zh:'公园',pos:'n.',theme:'其他名词'},
  {en:'part',zh:'部分; 成分; 角色; 部件; 零件',pos:'n.',theme:'其他名词'},
  {en:'passage',zh:'一节; 一段; 地道; 走廊',pos:'n.',theme:'其他名词'},
  {en:'passport',zh:'护照',pos:'n.',theme:'其他名词'},
  {en:'path',zh:'小道, 小径',pos:'n.',theme:'其他名词'},
  {en:'pear',zh:'梨子, 梨树',pos:'n.',theme:'其他名词'},
  {en:'penny',zh:'(英)便士; 美分',pos:'n.',theme:'其他名词'},
  {en:'percent',zh:'百分之…',pos:'n.',theme:'其他名词'},
  {en:'period',zh:'定期, 时代',pos:'n.',theme:'其他名词'},
  {en:'person',zh:'人',pos:'n.',theme:'其他名词'},
  {en:'pet',zh:'宠物, 爱畜',pos:'n.',theme:'其他名词'},
  {en:'photograph',zh:'照片',pos:'n.',theme:'其他名词'},
  {en:'piano',zh:'钢琴',pos:'n.',theme:'其他名词'},
  {en:'picnic',zh:'野餐',pos:'n.',theme:'其他名词'},
  {en:'piece',zh:'一块(片, 张, 件……)',pos:'n.',theme:'其他名词'},
  {en:'ping-pong',zh:'乒乓球',pos:'n.',theme:'其他名词'},
  {en:'pioneer',zh:'先锋, 开拓者',pos:'n.',theme:'其他名词'},
  {en:'pity',zh:'怜悯, 同情',pos:'n.',theme:'其他名词'},
  {en:'place',zh:'地方, 处所',pos:'n.',theme:'其他名词'},
  {en:'planet',zh:'行星',pos:'n.',theme:'其他名词'},
  {en:'plastic',zh:'塑料',pos:'n.',theme:'其他名词'},
  {en:'playground',zh:'操场, 运动场',pos:'n.',theme:'其他名词'},
  {en:'pleasure',zh:'高兴, 愉快',pos:'n.',theme:'其他名词'},
  {en:'plenty',zh:'充足, 大量',pos:'n.',theme:'其他名词'},
  {en:'pocket',zh:'(衣服的)口袋',pos:'n.',theme:'其他名词'},
  {en:'policeman',zh:'警察; 巡警',pos:'n.',theme:'其他名词'},
  {en:'policy',zh:'政策; 方针',pos:'n.',theme:'其他名词'},
  {en:'pond',zh:'池塘',pos:'n.',theme:'其他名词'},
  {en:'pool',zh:'水塘, 水池',pos:'n.',theme:'其他名词'},
  {en:'position',zh:'位置',pos:'n.',theme:'其他名词'},
  {en:'postcard',zh:'明信片',pos:'n.',theme:'其他名词'},
  {en:'postman',zh:'邮递员',pos:'n.',theme:'其他名词'},
  {en:'praise',zh:'赞扬, 表扬',pos:'n. & vt.',theme:'其他名词'},
  {en:'pride',zh:'自豪; 骄傲',pos:'n.',theme:'其他名词'},
  {en:'prison',zh:'监狱',pos:'n.',theme:'其他名词'},
  {en:'prisoner',zh:'囚犯',pos:'n.',theme:'其他名词'},
  {en:'problem',zh:'问题, 难题',pos:'n.',theme:'其他名词'},
  {en:'programme',zh:'节目; 项目',pos:'n.',theme:'其他名词'},
  {en:'progress',zh:'进步; 上进',pos:'n.',theme:'其他名词'},
  {en:'promise',zh:'答应; 允许',pos:'n. & vi.',theme:'其他名词'},
  {en:'pronunciation',zh:'发音',pos:'n.',theme:'其他名词'},
  {en:'pupil',zh:'(小)学生',pos:'n.',theme:'其他名词'},
  {en:'purple',zh:'紫色',pos:'n.',theme:'其他名词'},
  {en:'purse',zh:'钱包',pos:'n.',theme:'其他名词'},
  {en:'question',zh:'问题',pos:'n.',theme:'其他名词'},
  {en:'railway',zh:'铁路; 铁道',pos:'n.',theme:'其他名词'},
  {en:'raincoat',zh:'雨衣',pos:'n.',theme:'其他名词'},
  {en:'rat',zh:'老鼠',pos:'n.',theme:'其他名词'},
  {en:'record',zh:'记录; 唱片',pos:'n.',theme:'其他名词'},
  {en:'recorder',zh:'录音机',pos:'n.',theme:'其他名词'},
  {en:'red',zh:'红色',pos:'n.',theme:'其他名词'},
  {en:'regret',zh:'可惜; 遗憾; 痛惜; 哀悼',pos:'n. & vt.',theme:'其他名词'},
  {en:'relation',zh:'关系; 亲属',pos:'n.',theme:'其他名词'},
  {en:'rest',zh:'休息; 剩余的部分, 其余的人(物)',pos:'n.',theme:'其他名词'},
  {en:'result',zh:'结果, 效果',pos:'n.',theme:'其他名词'},
  {en:'riddle',zh:'谜(语)',pos:'n.',theme:'其他名词'},
  {en:'right',zh:'权利',pos:'n.',theme:'其他名词'},
  {en:'risk',zh:'冒险; 风险',pos:'n.',theme:'其他名词'},
  {en:'rock',zh:'岩石, 大石头',pos:'n.',theme:'其他名词'},
  {en:'rope',zh:'绳; 索',pos:'n.',theme:'其他名词'},
  {en:'rose',zh:'玫瑰花',pos:'n.',theme:'其他名词'},
  {en:'row',zh:'(一)排; (一)打',pos:'n.',theme:'其他名词'},
  {en:'rubber',zh:'橡胶; 合成橡胶',pos:'n.',theme:'其他名词'},
  {en:'rubbish',zh:'垃圾; 废物',pos:'n.',theme:'其他名词'},
  {en:'rusia',zh:'俄罗斯, 俄国',pos:'n.',theme:'其他名词'},
  {en:'sail',zh:'航行',pos:'n.',theme:'其他名词'},
  {en:'same',zh:'同样的事',pos:'n.',theme:'其他名词'},
  {en:'sand',zh:'沙, 沙子',pos:'n.',theme:'其他名词'},
  {en:'saturday',zh:'星期六',pos:'n.',theme:'其他名词'},
  {en:'sausage',zh:'香肠; 腊肠',pos:'n.',theme:'其他名词'},
  {en:'scarf',zh:'领巾; 围巾',pos:'n.',theme:'其他名词'},
  {en:'schoolbag',zh:'书包',pos:'n.',theme:'其他名词'},
  {en:'seat',zh:'座位, 座',pos:'n.',theme:'其他名词'},
  {en:'secretary',zh:'秘书; 书记',pos:'n.',theme:'其他名词'},
  {en:'sense',zh:'感觉; 意识',pos:'n.',theme:'其他名词'},
  {en:'sentence',zh:'句子',pos:'n.',theme:'其他名词'},
  {en:'september',zh:'九月',pos:'n.',theme:'其他名词'},
  {en:'shame',zh:'遗憾的事; 羞愧',pos:'n.',theme:'其他名词'},
  {en:'shape',zh:'形状, 外形',pos:'n.',theme:'其他名词'},
  {en:'she',zh:'她',pos:'pron.',theme:'其他名词'},
  {en:'shelf',zh:'架子; 搁板; 格层; 礁; 陆',pos:'n.',theme:'其他名词'},
  {en:'shorts',zh:'短裤; 运动短裤',pos:'n.',theme:'其他名词'},
  {en:'shower',zh:'阵雨; 淋浴',pos:'n.',theme:'其他名词'},
  {en:'side',zh:'边, 旁边, 面, 侧面',pos:'n.',theme:'其他名词'},
  {en:'sight',zh:'情景; 风景; 视力',pos:'n.',theme:'其他名词'},
  {en:'silence',zh:'安静; 沉默',pos:'n.',theme:'其他名词'},
  {en:'silk',zh:'(蚕)丝, 丝织品',pos:'n.',theme:'其他名词'},
  {en:'silver',zh:'银',pos:'n.',theme:'其他名词'},
  {en:'sir',zh:'先生; 阁下',pos:'n.',theme:'其他名词'},
  {en:'situation',zh:'形势, 情况 ．',pos:'n.',theme:'其他名词'},
  {en:'skill',zh:'技能, 技巧',pos:'n.',theme:'其他名词'},
  {en:'skirt',zh:'女裙',pos:'n.',theme:'其他名词'},
  {en:'smile',zh:'微笑',pos:'n. & n.',theme:'其他名词'},
  {en:'smoke',zh:'烟',pos:'n.',theme:'其他名词'},
  {en:'soap',zh:'肥皂',pos:'n.',theme:'其他名词'},
  {en:'somebody',zh:'某人; 有人; 有名气的人',pos:'pron.',theme:'其他名词'},
  {en:'someone',zh:'某一个人 止',pos:'pron.',theme:'其他名词'},
  {en:'something',zh:'某事; 某物',pos:'pron.',theme:'其他名词'},
  {en:'speaker',zh:'演讲人, 演说家',pos:'n.',theme:'其他名词'},
  {en:'speech',zh:'演讲 的, 那样的',pos:'n.',theme:'其他名词'},
  {en:'speed',zh:'速度',pos:'n.',theme:'其他名词'},
  {en:'spirit',zh:'精神',pos:'n.',theme:'其他名词'},
  {en:'square',zh:'广场',pos:'n.',theme:'其他名词'},
  {en:'stairs',zh:'楼梯',pos:'n.',theme:'其他名词'},
  {en:'stamp',zh:'邮票',pos:'n.',theme:'其他名词'},
  {en:'state',zh:'状态; 情形; 国家, (美国的)州',pos:'n.',theme:'其他名词'},
  {en:'stay',zh:'停留, 逗留, 呆',pos:'n. & vi.',theme:'其他名词'},
  {en:'steam',zh:'汽; 水蒸气',pos:'n.',theme:'其他名词'},
  {en:'steel',zh:'钢, 钢铁',pos:'n.',theme:'其他名词'},
  {en:'step',zh:'脚步, 台阶, 梯级',pos:'n.',theme:'其他名词'},
  {en:'stone',zh:'石头, 石料',pos:'n.',theme:'其他名词'},
  {en:'stranger',zh:'陌生人, 外人',pos:'n.',theme:'其他名词'},
  {en:'stream',zh:'小河; 溪流',pos:'n.',theme:'其他名词'},
  {en:'success',zh:'成功',pos:'n.',theme:'其他名词'},
  {en:'suggestion',zh:'建议',pos:'n.',theme:'其他名词'},
  {en:'sunday',zh:'星期日',pos:'n.',theme:'其他名词'},
  {en:'supermarket',zh:'超级市场 宾语从句等)',pos:'n.',theme:'其他名词'},
  {en:'supper',zh:'晚餐, 晚饭',pos:'n.',theme:'其他名词'},
  {en:'supply',zh:'供给, 供应 物、序数词、最高级、专有名词, 世上独一无二事',pos:'vt. & n.',theme:'其他名词'},
  {en:'surface',zh:'表面',pos:'n.',theme:'其他名词'},
  {en:'sweater',zh:'厚运动衫, 毛衣',pos:'n.',theme:'其他名词'},
  {en:'swimming',zh:'游泳',pos:'n.',theme:'其他名词'},
  {en:'swing',zh:'秋千',pos:'n.',theme:'其他名词'},
  {en:'symbol',zh:'象征, 标志; 符号',pos:'n.',theme:'其他名词'},
  {en:'tail',zh:'(动物的)尾巴 件',pos:'n.',theme:'其他名词'},
  {en:'tale',zh:'故事, 传说',pos:'n.',theme:'其他名词'},
  {en:'tape',zh:'磁带; 录音带',pos:'n.',theme:'其他名词'},
  {en:'temperature',zh:'温度',pos:'n.',theme:'其他名词'},
  {en:'tent',zh:'帐篷',pos:'n.',theme:'其他名词'},
  {en:'term',zh:'学期; 术语; 条款; 项',pos:'n.',theme:'其他名词'},
  {en:'their',zh:'他(或她、它)们的',pos:'pron.',theme:'其他名词'},
  {en:'theirs',zh:'他们的',pos:'pron.',theme:'其他名词'},
  {en:'them',zh:'他／她／它们(宾格)',pos:'pron.',theme:'其他名词'},
  {en:'themselves',zh:'他／她／它们自己',pos:'pron.',theme:'其他名词'},
  {en:'they',zh:'他(她)们; 它们; 人们',pos:'pron.',theme:'其他名词'},
  {en:'thing',zh:'东西; (',pos:'n.',theme:'其他名词'},
  {en:'thought',zh:'思考, 思想; 念头',pos:'n.',theme:'其他名词'},
  {en:'thread',zh:'线',pos:'n.',theme:'其他名词'},
  {en:'thursday',zh:'星期四',pos:'n.',theme:'其他名词'},
  {en:'toilet',zh:'厕所',pos:'n.',theme:'其他名词'},
  {en:'tongue',zh:'舌, 舌头',pos:'n.',theme:'其他名词'},
  {en:'tool',zh:'工具, 器具',pos:'n.',theme:'其他名词'},
  {en:'toothache',zh:'牙痛 懂得; 明白; 理解',pos:'n.',theme:'其他名词'},
  {en:'toothbrush',zh:'牙刷',pos:'n.',theme:'其他名词'},
  {en:'toothpaste',zh:'牙膏',pos:'n.',theme:'其他名词'},
  {en:'top',zh:'顶部, (物体的)上面',pos:'n.',theme:'其他名词'},
  {en:'tourist',zh:'旅行者, 观光者',pos:'n.',theme:'其他名词'},
  {en:'towel',zh:'毛巾',pos:'n.',theme:'其他名词'},
  {en:'tower',zh:'塔',pos:'n.',theme:'其他名词'},
  {en:'toy',zh:'玩具; 玩物',pos:'n.',theme:'其他名词'},
  {en:'traffic',zh:'交通, 来往车辆',pos:'n.',theme:'其他名词'},
  {en:'training',zh:'培训',pos:'n.',theme:'其他名词'},
  {en:'treasure',zh:'金银财宝; 财富',pos:'n.',theme:'其他名词'},
  {en:'treatment',zh:'治疗, 疗法',pos:'n.',theme:'其他名词'},
  {en:'trousers',zh:'裤子, 长裤',pos:'n.',theme:'其他名词'},
  {en:'truck',zh:'卡车, 运货车; 车皮',pos:'n.',theme:'其他名词'},
  {en:'truth',zh:'真理, 事实, 真相, 实际情况',pos:'n.',theme:'其他名词'},
  {en:'tuesday',zh:'星期二',pos:'n.',theme:'其他名词'},
  {en:'tv',zh:'电视; 电视机',pos:'n.',theme:'其他名词'},
  {en:'umbrella',zh:'雨伞',pos:'n.',theme:'其他名词'},
  {en:'unit',zh:'单元, 单位',pos:'n.',theme:'其他名词'},
  {en:'us',zh:'我们(宾格)',pos:'pron.',theme:'其他名词'},
  {en:'use',zh:'利用, 使用, 应用',pos:'n. & vt.',theme:'其他名词'},
  {en:'vehicle',zh:'运输工具, 车辆',pos:'n.',theme:'其他名词'},
  {en:'victory',zh:'胜利',pos:'n.',theme:'其他名词'},
  {en:'violin',zh:'小提琴',pos:'n.',theme:'其他名词'},
  {en:'visitor',zh:'访问者, 参观者',pos:'n.',theme:'其他名词'},
  {en:'voice',zh:'说话声; 语态',pos:'n.',theme:'其他名词'},
  {en:'watermelon',zh:'西瓜',pos:'n.',theme:'其他名词'},
  {en:'way',zh:'路, 路线, 方式, 手段',pos:'n.',theme:'其他名词'},
  {en:'we',zh:'我们',pos:'pron.',theme:'其他名词'},
  {en:'wealth',zh:'财产, 财富',pos:'n.',theme:'其他名词'},
  {en:'wednesday',zh:'星期三',pos:'n.',theme:'其他名词'},
  {en:'weekday',zh:'平日',pos:'n.',theme:'其他名词'},
  {en:'weekend',zh:'周末',pos:'n.',theme:'其他名词'},
  {en:'whale',zh:'鲸',pos:'n.',theme:'其他名词'},
  {en:'what',zh:'什么, 怎么样',pos:'pron.',theme:'其他名词'},
  {en:'wheat',zh:'小麦',pos:'n.',theme:'其他名词'},
  {en:'wheel',zh:'轮, 机轮',pos:'n.',theme:'其他名词'},
  {en:'which',zh:'那(哪)个; 那(哪)一些',pos:'pron.',theme:'其他名词'},
  {en:'who',zh:'谁',pos:'pron.',theme:'其他名词'},
  {en:'whom',zh:'(',pos:'pron.',theme:'其他名词'},
  {en:'whose',zh:'谁的',pos:'pron.',theme:'其他名词'},
  {en:'wine',zh:'酒',pos:'n.',theme:'其他名词'},
  {en:'wing',zh:'翅膀',pos:'n.',theme:'其他名词'},
  {en:'winner',zh:'获胜者',pos:'n.',theme:'其他名词'},
  {en:'wish',zh:'愿望, 祝愿',pos:'n.',theme:'其他名词'},
  {en:'wolf',zh:'狼',pos:'n.',theme:'其他名词'},
  {en:'woman',zh:'妇女, 女人 ’',pos:'n.',theme:'其他名词'},
  {en:'wood',zh:'木头, 木材',pos:'n.',theme:'其他名词'},
  {en:'word',zh:'词, 单词, 话',pos:'n.',theme:'其他名词'},
  {en:'yard',zh:'码; 院子; 场地',pos:'n.',theme:'其他名词'},
  {en:'yellow',zh:'黄色',pos:'n.',theme:'其他名词'},
  {en:'you',zh:'你; 你们',pos:'pron.',theme:'其他名词'},
  {en:'your',zh:'你的; 你们的',pos:'pron.',theme:'其他名词'},
  {en:'yours',zh:'你的; 你们的(名词性物主代',pos:'pron.',theme:'其他名词'},
  {en:'yourself',zh:'你自己',pos:'pron.',theme:'其他名词'},
  {en:'yourselves',zh:'你们自己',pos:'pron.',theme:'其他名词'},
  {en:'zebra',zh:'班马',pos:'n.',theme:'其他名词'},
  {en:'zoo',zh:'动物园',pos:'n.',theme:'其他名词'},
  {en:'above',zh:'在……上面',pos:'prep.',theme:'功能词'},
  {en:'across',zh:'横过; 穿过',pos:'prep.',theme:'功能词'},
  {en:'against',zh:'对着, 反对 周围; 大约',pos:'prep.',theme:'功能词'},
  {en:'although',zh:'虽然; 尽管',pos:'conj.',theme:'功能词'},
  {en:'among',zh:'在……中间; 在(三个以上)之间',pos:'prep.',theme:'功能词'},
  {en:'and',zh:'和; 又; 而',pos:'conj.',theme:'功能词'},
  {en:'at',zh:'在(几点钟); 在(某处)',pos:'prep.',theme:'功能词'},
  {en:'because',zh:'因为',pos:'conj.',theme:'功能词'},
  {en:'behind',zh:'(表示位置)在……后面',pos:'prep.',theme:'功能词'},
  {en:'below',zh:'在……下面',pos:'prep.',theme:'功能词'},
  {en:'beside',zh:'在…旁边; 靠近',pos:'prep.',theme:'功能词'},
  {en:'besides',zh:'除……以外(还有)',pos:'prep.',theme:'功能词'},
  {en:'between',zh:'在(两者)之间, 在……中间',pos:'prep.',theme:'功能词'},
  {en:'beyond',zh:'(表示位置)在……的那边',pos:'prep.',theme:'功能词'},
  {en:'but',zh:'但是; 可是',pos:'conj.',theme:'功能词'},
  {en:'by',zh:'靠近; 在…旁边; 在…时间; 不迟于',pos:'prep.',theme:'功能词'},
  {en:'down',zh:'沿着, 沿……而下',pos:'prep.',theme:'功能词'},
  {en:'except',zh:'除……之外',pos:'prep.',theme:'功能词'},
  {en:'for',zh:'为了…;向…,往;与…交换;防',pos:'prep.',theme:'功能词'},
  {en:'from',zh:'从; 从……起; 来自',pos:'prep.',theme:'功能词'},
  {en:'if',zh:'如果, 假使; 是否, 是不是',pos:'conj.',theme:'功能词'},
  {en:'in',zh:'在……里(内); 在……; 以……',pos:'prep.',theme:'功能词'},
  {en:'inside',zh:'在……里面',pos:'prep.',theme:'功能词'},
  {en:'into',zh:'到……里; 向内; 变成',pos:'prep.',theme:'功能词'},
  {en:'like',zh:'像; 跟……一样',pos:'prep.',theme:'功能词'},
  {en:'nor',zh:'也不',pos:'conj.',theme:'功能词'},
  {en:'of',zh:'(表示所属、数量, 其',pos:'prep.',theme:'功能词'},
  {en:'off',zh:'离开, 脱离, (走)开',pos:'prep.',theme:'功能词'},
  {en:'on',zh:'在……上面; 关于',pos:'prep.',theme:'功能词'},
  {en:'or',zh:'或, 就是, 否则',pos:'conj.',theme:'功能词'},
  {en:'over',zh:'在…上方; 越过; 遍及',pos:'prep.',theme:'功能词'},
  {en:'than',zh:'比 受动作的人或物)给; 对, 向, 到; 在……之前',pos:'conj.',theme:'功能词'},
  {en:'though',zh:'虽然, 可是',pos:'conj.',theme:'功能词'},
  {en:'through',zh:'穿(通)过; 从始至终',pos:'prep.',theme:'功能词'},
  {en:'till',zh:'直到, 直到……为止',pos:'conj. & prep.',theme:'功能词'},
  {en:'to',zh:'(动词不定式符号, 无词义); (表示接',pos:'prep.',theme:'功能词'},
  {en:'toward',zh:'向, 朝, 对于',pos:'prep.',theme:'功能词'},
  {en:'under',zh:'在……下面, 向……下面',pos:'prep.',theme:'功能词'},
  {en:'unless',zh:'如果不; 除非',pos:'conj.',theme:'功能词'},
  {en:'upon',zh:'在……上面',pos:'prep.',theme:'功能词'},
  {en:'whatever',zh:'&',pos:'conj.',theme:'功能词'},
  {en:'when',zh:'当……的时候',pos:'conj.',theme:'功能词'},
  {en:'whenever',zh:'每当, 无论何时',pos:'conj.',theme:'功能词'},
  {en:'whether',zh:'是否',pos:'conj.',theme:'功能词'},
  {en:'while',zh:'在……的时候, 和……',pos:'conj.',theme:'功能词'},
  {en:'with',zh:'关于, 带有, 以, 和, 用, 有',pos:'prep.',theme:'功能词'},
  {en:'without',zh:'没有',pos:'prep.',theme:'功能词'},
  {en:'answer',zh:'回答, 答复; 答案',pos:'n.',theme:'动作与行为'},
  {en:'ask',zh:'问,询问; 请求, 要求; 邀请',pos:'v.',theme:'动作与行为'},
  {en:'begin',zh:'开始, 着手',pos:'v.',theme:'动作与行为'},
  {en:'break',zh:'打破(断、碎); 损坏,',pos:'v.',theme:'动作与行为'},
  {en:'bring',zh:'拿来, 带来, 取来',pos:'vt.',theme:'动作与行为'},
  {en:'build',zh:'建筑; 造',pos:'v.',theme:'动作与行为'},
  {en:'carry',zh:'拿; 搬; 带; 提; 抬; 背; 抱; 运等 的',pos:'vt.',theme:'动作与行为'},
  {en:'catch',zh:'接住; 捉住; 赶上; 染',pos:'v.',theme:'动作与行为'},
  {en:'climb',zh:'爬, 攀登',pos:'v.',theme:'动作与行为'},
  {en:'close',zh:'关, 关闭',pos:'vt.',theme:'动作与行为'},
  {en:'continue',zh:'继续',pos:'vi.',theme:'动作与行为'},
  {en:'cut',zh:'切, 剪, 削, 割',pos:'v.',theme:'动作与行为'},
  {en:'dance',zh:'跳舞',pos:'n. & vi.',theme:'动作与行为'},
  {en:'draw',zh:'绘画; 绘制; 拉, 拖; 提',pos:'v.',theme:'动作与行为'},
  {en:'drop',zh:'滴',pos:'n.',theme:'动作与行为'},
  {en:'end',zh:'末尾; 终点; 结束',pos:'n.',theme:'动作与行为'},
  {en:'finish',zh:'结束; 做完',pos:'v.',theme:'动作与行为'},
  {en:'fix',zh:'修理; 安装; 确定, 决定',pos:'vt.',theme:'动作与行为'},
  {en:'get',zh:'成为; 得到; 具有; 到达',pos:'vt.',theme:'动作与行为'},
  {en:'give',zh:'给; 递给; 付出; 给予',pos:'vt.',theme:'动作与行为'},
  {en:'grow',zh:'生长; 发育; 种植; 变成',pos:'v.',theme:'动作与行为'},
  {en:'hear',zh:'听见; 听说, 得知',pos:'v.',theme:'动作与行为'},
  {en:'hold',zh:'拿; 抱; 握住; 举行; 进',pos:'vt.',theme:'动作与行为'},
  {en:'jump',zh:'跳跃; 惊起; 猛扑',pos:'v.',theme:'动作与行为'},
  {en:'keep',zh:'保持; 保存; 继续不断',pos:'v.',theme:'动作与行为'},
  {en:'let',zh:'让',pos:'vt.',theme:'动作与行为'},
  {en:'lie',zh:'躺; 卧; 平放; 位于',pos:'v.',theme:'动作与行为'},
  {en:'listen',zh:'听, 仔细听',pos:'vi.',theme:'动作与行为'},
  {en:'lock',zh:'锁',pos:'n.',theme:'动作与行为'},
  {en:'look',zh:'看, 瞧',pos:'n.',theme:'动作与行为'},
  {en:'make',zh:'制造, 做; 使得',pos:'vt.',theme:'动作与行为'},
  {en:'move',zh:'移动, 搬动, 搬家',pos:'v.',theme:'动作与行为'},
  {en:'open',zh:'开着的, 开口的',pos:'adj.',theme:'动作与行为'},
  {en:'paint',zh:'油漆',pos:'n.',theme:'动作与行为'},
  {en:'pass',zh:'传, 递; 经过; 通过',pos:'vt.',theme:'动作与行为'},
  {en:'pick',zh:'拾起, 采集; 挑选',pos:'v.',theme:'动作与行为'},
  {en:'play',zh:'玩; 打(球); 游戏; 播放',pos:'v.',theme:'动作与行为'},
  {en:'pull',zh:'拉, 拖',pos:'v.',theme:'动作与行为'},
  {en:'push',zh:'推',pos:'n. & v.',theme:'动作与行为'},
  {en:'put',zh:'放, 摆 复习; 评论',pos:'v.',theme:'动作与行为'},
  {en:'read',zh:'读; 朗读',pos:'v.',theme:'动作与行为'},
  {en:'rise',zh:'上升, 上涨',pos:'vi.',theme:'动作与行为'},
  {en:'run',zh:'跑, 奔跑; (颜色)褪色',pos:'vi.',theme:'动作与行为'},
  {en:'say',zh:'说, 讲',pos:'vt.',theme:'动作与行为'},
  {en:'see',zh:'看见, 看到; 领会; 拜会',pos:'vt.',theme:'动作与行为'},
  {en:'send',zh:'打发, 派遣; 送, 邮寄',pos:'v.',theme:'动作与行为'},
  {en:'set',zh:'释放, 安置, 设置(布景, 背景)',pos:'vt.',theme:'动作与行为'},
  {en:'shut',zh:'关上, 封闭; 禁闭',pos:'v.',theme:'动作与行为'},
  {en:'sing',zh:'唱, 唱歌',pos:'v.',theme:'动作与行为'},
  {en:'sit',zh:'坐',pos:'vi.',theme:'动作与行为'},
  {en:'smell',zh:'嗅, 闻到; 发',pos:'v.',theme:'动作与行为'},
  {en:'speak',zh:'说, 讲; 谈话; 发言',pos:'v.',theme:'动作与行为'},
  {en:'stand',zh:'站; 立; 起立; 坐落',pos:'v.',theme:'动作与行为'},
  {en:'start',zh:'开始, 着手; 出发',pos:'v.',theme:'动作与行为'},
  {en:'stop',zh:'停止, 停留; (停车)站',pos:'n.',theme:'动作与行为'},
  {en:'swim',zh:'游泳, 游 那儿',pos:'vi.',theme:'动作与行为'},
  {en:'take',zh:'拿; 拿走; 做; 服用; 乘',pos:'vt.',theme:'动作与行为'},
  {en:'talk',zh:'谈话, 讲话, 演讲; 交谈',pos:'n. & v.',theme:'动作与行为'},
  {en:'taste',zh:'品尝, 尝味; 味道',pos:'n.',theme:'动作与行为'},
  {en:'tell',zh:'告诉; 讲述; 吩咐',pos:'vt.',theme:'动作与行为'},
  {en:'throw',zh:'投, 掷, 扔',pos:'v.',theme:'动作与行为'},
  {en:'touch',zh:'触摸, 接触 向(高处); 向(在)……上(面)游',pos:'vt. & n.',theme:'动作与行为'},
  {en:'try',zh:'试, 试图, 努力',pos:'v.',theme:'动作与行为'},
  {en:'turn',zh:'旋转, 翻转, 转变, 转弯',pos:'v.',theme:'动作与行为'},
  {en:'walk',zh:'步行, 散步',pos:'v. & n.',theme:'动作与行为'},
  {en:'watch',zh:'观看, 注视; 当心, 注意',pos:'vt.',theme:'动作与行为'},
  {en:'write',zh:'写, 书写, 写作, 著述',pos:'v.',theme:'动作与行为'},
  {en:'capital',zh:'首都; 省会; 大写; 资本',pos:'n.',theme:'地理与地名'},
  {en:'blackboard',zh:'黑板',pos:'n.',theme:'学校学习'},
  {en:'chalk',zh:'粉笔',pos:'n.',theme:'学校学习'},
  {en:'chemistry',zh:'化学',pos:'n.',theme:'学校学习'},
  {en:'chinese',zh:'中国的; 中国人的; 中国话的,',pos:'adj.',theme:'学校学习'},
  {en:'class',zh:'(学校里的)班; 年级; 课',pos:'n.',theme:'学校学习'},
  {en:'classroom',zh:'教室',pos:'n.',theme:'学校学习'},
  {en:'college',zh:'学院; 专科学校',pos:'n.',theme:'学校学习'},
  {en:'correct',zh:'改正; 纠正',pos:'v.',theme:'学校学习'},
  {en:'course',zh:'过程; 经过; 课程',pos:'n.',theme:'学校学习'},
  {en:'degree',zh:'程度; 度数; 学位',pos:'n.',theme:'学校学习'},
  {en:'dictionary',zh:'词典, 字典',pos:'n.',theme:'学校学习'},
  {en:'education',zh:'教育, 培养',pos:'n.',theme:'学校学习'},
  {en:'english',zh:'英国的; 英国人的; 英语的',pos:'adj.',theme:'学校学习'},
  {en:'eraser',zh:'橡皮擦; 黑板擦',pos:'n.',theme:'学校学习'},
  {en:'geography',zh:'地理学',pos:'n.',theme:'学校学习'},
  {en:'grade',zh:'等级; (中小学的)学年; 成绩, 分数',pos:'n.',theme:'学校学习'},
  {en:'history',zh:'历史, 历史学 印地安人; 印度人',pos:'n.',theme:'学校学习'},
  {en:'homework',zh:'家庭作业',pos:'n.',theme:'学校学习'},
  {en:'knowledge',zh:'知识, 学问',pos:'n.',theme:'学校学习'},
  {en:'learn',zh:'学, 学习, 学',pos:'vt.',theme:'学校学习'},
  {en:'lesson',zh:'课; 功课; 教训',pos:'n.',theme:'学校学习'},
  {en:'library',zh:'图书馆, 图书室',pos:'n.',theme:'学校学习'},
  {en:'mark',zh:'标记; 标明',pos:'n. & vt.',theme:'学校学习'},
  {en:'mistake',zh:'弄错',pos:'vt.',theme:'学校学习'},
  {en:'notebook',zh:'笔记簿',pos:'n.',theme:'学校学习'},
  {en:'pen',zh:'钢笔, 笔',pos:'n.',theme:'学校学习'},
  {en:'pencil',zh:'铅笔',pos:'n.',theme:'学校学习'},
  {en:'physics',zh:'物理(学)',pos:'n.',theme:'学校学习'},
  {en:'practice',zh:'练习',pos:'n.',theme:'学校学习'},
  {en:'review',zh:'重新调查; 回顾; 复习',pos:'vt.',theme:'学校学习'},
  {en:'ruler',zh:'统治者; 直尺',pos:'n.',theme:'学校学习'},
  {en:'school',zh:'学校',pos:'n.',theme:'学校学习'},
  {en:'science',zh:'科学, 自然科学',pos:'n.',theme:'学校学习'},
  {en:'score',zh:'得分; 分数',pos:'n. & v.',theme:'学校学习'},
  {en:'student',zh:'学生',pos:'n.',theme:'学校学习'},
  {en:'study',zh:'学习; 研究',pos:'v.',theme:'学校学习'},
  {en:'subject',zh:'题目; 主题; 学科; 主语',pos:'n.',theme:'学校学习'},
  {en:'teacher',zh:'教师, 教员',pos:'n.',theme:'学校学习'},
  {en:'test',zh:'测试, 考查, 试验',pos:'vi. & n.',theme:'学校学习'},
  {en:'university',zh:'大学',pos:'n.',theme:'学校学习'},
  {en:'aunt',zh:'伯母; 舅母; 审; 姑; 姨',pos:'n.',theme:'家庭与朋友'},
  {en:'baby',zh:'婴儿',pos:'n.',theme:'家庭与朋友'},
  {en:'brother',zh:'兄; 弟',pos:'n.',theme:'家庭与朋友'},
  {en:'child',zh:'孩子, 儿童',pos:'n.',theme:'家庭与朋友'},
  {en:'cousin',zh:'堂(表)兄弟, 堂(表)姐妹',pos:'n.',theme:'家庭与朋友'},
  {en:'daughter',zh:'女儿',pos:'n.',theme:'家庭与朋友'},
  {en:'family',zh:'家庭',pos:'n.',theme:'家庭与朋友'},
  {en:'father',zh:'父亲',pos:'n.',theme:'家庭与朋友'},
  {en:'friend',zh:'朋友',pos:'n.',theme:'家庭与朋友'},
  {en:'grandfather',zh:'爷',pos:'n.',theme:'家庭与朋友'},
  {en:'husband',zh:'丈夫 的',pos:'n.',theme:'家庭与朋友'},
  {en:'kid',zh:'小孩',pos:'n.',theme:'家庭与朋友'},
  {en:'mother',zh:'母亲',pos:'n.',theme:'家庭与朋友'},
  {en:'parent',zh:'父(母), 双亲',pos:'n.',theme:'家庭与朋友'},
  {en:'sister',zh:'姐; 妹',pos:'n.',theme:'家庭与朋友'},
  {en:'son',zh:'儿子',pos:'n.',theme:'家庭与朋友'},
  {en:'uncle',zh:'叔; 伯; 舅; 姑夫; 姨父',pos:'n.',theme:'家庭与朋友'},
  {en:'wife',zh:'妻子',pos:'n.',theme:'家庭与朋友'},
  {en:'afraid',zh:'害怕的; 担心的',pos:'adj.',theme:'情感与品质'},
  {en:'angry',zh:'生气的, 愤怒的',pos:'adj.',theme:'情感与品质'},
  {en:'brave',zh:'勇敢的',pos:'adj.',theme:'情感与品质'},
  {en:'careful',zh:'小心的; 仔细的; 谨慎的',pos:'adj.',theme:'情感与品质'},
  {en:'careless',zh:'粗心的; 漫不经心的',pos:'adj.',theme:'情感与品质'},
  {en:'clever',zh:'聪明的, 伶俐的',pos:'adj.',theme:'情感与品质'},
  {en:'crazy',zh:'疯狂的',pos:'adj.',theme:'情感与品质'},
  {en:'happy',zh:'幸福的; 快乐的, 高兴的',pos:'adj.',theme:'情感与品质'},
  {en:'honest',zh:'诚实的; 正直的',pos:'adj.',theme:'情感与品质'},
  {en:'kind',zh:'种; 类型',pos:'n.',theme:'情感与品质'},
  {en:'lazy',zh:'放; 搁',pos:'adj.',theme:'情感与品质'},
  {en:'lonely',zh:'孤独的, 寂寞的',pos:'adj.',theme:'情感与品质'},
  {en:'nervous',zh:'紧张不安的',pos:'adj.',theme:'情感与品质'},
  {en:'polite',zh:'有礼貌的; 有教养的',pos:'adj.',theme:'情感与品质'},
  {en:'proud',zh:'自豪的; 骄傲的',pos:'adj.',theme:'情感与品质'},
  {en:'sad',zh:'(使人)悲伤的',pos:'adj.',theme:'情感与品质'},
  {en:'serious',zh:'严肃的, 严重的; 认真的 后, 由于',pos:'adj.',theme:'情感与品质'},
  {en:'shy',zh:'害羞的',pos:'adj.',theme:'情感与品质'},
  {en:'silly',zh:'傻的; 愚蠢的',pos:'adj.',theme:'情感与品质'},
  {en:'smart',zh:'灵巧的; 伶俐的; (人、服装等)时',pos:'adj.',theme:'情感与品质'},
  {en:'strict',zh:'严格的, 严密的',pos:'adj.',theme:'情感与品质'},
  {en:'stupid',zh:'愚蠢的, 笨的',pos:'adj.',theme:'情感与品质'},
  {en:'wise',zh:'聪明的, 英明的, 有见识的',pos:'adj.',theme:'情感与品质'},
  {en:'deep',zh:'深的;深厚的',pos:'adj.',theme:'数字与度量'},
  {en:'eight',zh:'八',pos:'num.',theme:'数字与度量'},
  {en:'eighteen',zh:'十八',pos:'num.',theme:'数字与度量'},
  {en:'eighty',zh:'八十',pos:'num.',theme:'数字与度量'},
  {en:'eleven',zh:'十一',pos:'num.',theme:'数字与度量'},
  {en:'fifteen',zh:'十五',pos:'num.',theme:'数字与度量'},
  {en:'fifty',zh:'五十',pos:'num.',theme:'数字与度量'},
  {en:'five',zh:'五',pos:'num.',theme:'数字与度量'},
  {en:'forty',zh:'四十',pos:'num.',theme:'数字与度量'},
  {en:'four',zh:'四',pos:'num.',theme:'数字与度量'},
  {en:'fourteen',zh:'十四',pos:'num.',theme:'数字与度量'},
  {en:'height',zh:'高; 高度; 海拔',pos:'n.',theme:'数字与度量'},
  {en:'inch',zh:'英寸',pos:'n.',theme:'数字与度量'},
  {en:'kilometer',zh:'千米(公里)',pos:'n.',theme:'数字与度量'},
  {en:'mile',zh:'英里',pos:'n.',theme:'数字与度量'},
  {en:'nine',zh:'九',pos:'num.',theme:'数字与度量'},
  {en:'nineteen',zh:'十九',pos:'num.',theme:'数字与度量'},
  {en:'ninety',zh:'九十',pos:'num.',theme:'数字与度量'},
  {en:'one',zh:'一(个, 只……)',pos:'num.',theme:'数字与度量'},
  {en:'pound',zh:'磅; 英镑',pos:'n.',theme:'数字与度量'},
  {en:'seven',zh:'七',pos:'num.',theme:'数字与度量'},
  {en:'seventeen',zh:'十七',pos:'num.',theme:'数字与度量'},
  {en:'seventy',zh:'七十',pos:'num.',theme:'数字与度量'},
  {en:'six',zh:'六',pos:'num.',theme:'数字与度量'},
  {en:'sixteen',zh:'十六',pos:'num.',theme:'数字与度量'},
  {en:'sixty',zh:'六十',pos:'num.',theme:'数字与度量'},
  {en:'size',zh:'尺寸, 大小',pos:'n.',theme:'数字与度量'},
  {en:'ten',zh:'十',pos:'num.',theme:'数字与度量'},
  {en:'thick',zh:'厚的',pos:'adj.',theme:'数字与度量'},
  {en:'thirteen',zh:'十三',pos:'num.',theme:'数字与度量'},
  {en:'thirty',zh:'三十',pos:'num.',theme:'数字与度量'},
  {en:'ton',zh:'(重量单位) 吨',pos:'n.',theme:'数字与度量'},
  {en:'twelve',zh:'十二',pos:'num.',theme:'数字与度量'},
  {en:'twenty',zh:'二十',pos:'num.',theme:'数字与度量'},
  {en:'two',zh:'二',pos:'num.',theme:'数字与度量'},
  {en:'weight',zh:'重, 重量 道',pos:'n.',theme:'数字与度量'},
  {en:'art',zh:'艺术, 美术; 技艺',pos:'n.',theme:'文化与艺术'},
  {en:'ball',zh:'球',pos:'n.',theme:'文化与艺术'},
  {en:'basketball',zh:'篮球',pos:'n.',theme:'文化与艺术'},
  {en:'celebrate',zh:'庆祝',pos:'v.',theme:'文化与艺术'},
  {en:'concert',zh:'音乐会; 演奏会',pos:'n.',theme:'文化与艺术'},
  {en:'fan',zh:'风扇; 影迷; 球迷',pos:'n.',theme:'文化与艺术'},
  {en:'festival',zh:'节日的, 喜庆的',pos:'n.',theme:'文化与艺术'},
  {en:'film',zh:'电影; 影片; 胶卷',pos:'num.',theme:'文化与艺术'},
  {en:'football',zh:'(英式)足球; (美式)橄榄球',pos:'n.',theme:'文化与艺术'},
  {en:'game',zh:'游戏; 运动; 比赛',pos:'n.',theme:'文化与艺术'},
  {en:'gift',zh:'礼物; 赠品',pos:'n.',theme:'文化与艺术'},
  {en:'lose',zh:'失去, 丢失',pos:'v.',theme:'文化与艺术'},
  {en:'match',zh:'比赛; 竞赛; 火柴',pos:'n.',theme:'文化与艺术'},
  {en:'movie',zh:'(口语)电影',pos:'n.',theme:'文化与艺术'},
  {en:'museum',zh:'博物馆, 博物院',pos:'n.',theme:'文化与艺术'},
  {en:'music',zh:'音乐, 乐曲',pos:'n.',theme:'文化与艺术'},
  {en:'picture',zh:'图片, 画片, 照片',pos:'n.',theme:'文化与艺术'},
  {en:'poem',zh:'诗',pos:'n.',theme:'文化与艺术'},
  {en:'present',zh:'礼物, 赠品',pos:'n.',theme:'文化与艺术'},
  {en:'prize',zh:'奖赏, 奖品',pos:'n.',theme:'文化与艺术'},
  {en:'race',zh:'种族, 民族; 赛跑, 竞赛 话, 铃声; 环形物(如环、圈、戒指等)',pos:'n.',theme:'文化与艺术'},
  {en:'show',zh:'展示; 展览(会); 演出',pos:'n.',theme:'文化与艺术'},
  {en:'skate',zh:'溜冰, 滑冰',pos:'vi.',theme:'文化与艺术'},
  {en:'song',zh:'歌唱; 歌曲',pos:'n.',theme:'文化与艺术'},
  {en:'sport',zh:'体育运动, 锻炼; 运动会',pos:'n.',theme:'文化与艺术'},
  {en:'story',zh:'故事, 小说',pos:'n.',theme:'文化与艺术'},
  {en:'team',zh:'队, 组',pos:'n.',theme:'文化与艺术'},
  {en:'tennis',zh:'网球 关系',pos:'n.',theme:'文化与艺术'},
  {en:'theatre',zh:'剧场, 戏院',pos:'n.',theme:'文化与艺术'},
  {en:'volleyball',zh:'排球',pos:'n.',theme:'文化与艺术'},
  {en:'win',zh:'获胜, 赢得',pos:'v.',theme:'文化与艺术'},
  {en:'abroad',zh:'到(在)国外',pos:'adv.',theme:'旅行交通'},
  {en:'airport',zh:'航空站, 飞机场 亚洲人',pos:'n.',theme:'旅行交通'},
  {en:'bicycle',zh:'自行车',pos:'n.',theme:'旅行交通'},
  {en:'boat',zh:'小船, 小舟',pos:'n.',theme:'旅行交通'},
  {en:'bridge',zh:'桥',pos:'n.',theme:'旅行交通'},
  {en:'bus',zh:'公共汽车 席; 会长; 议长',pos:'n.',theme:'旅行交通'},
  {en:'car',zh:'汽车; 小卧车',pos:'n.',theme:'旅行交通'},
  {en:'direction',zh:'方向; 方位',pos:'n.',theme:'旅行交通'},
  {en:'drive',zh:'驾驶, 开(车); 驱赶',pos:'v.',theme:'旅行交通'},
  {en:'east',zh:'东方的; 东部的; 朝东的; 从东方来的',pos:'adj.',theme:'旅行交通'},
  {en:'fly',zh:'飞行; 苍蝇',pos:'n.',theme:'旅行交通'},
  {en:'foreign',zh:'外国的',pos:'adj.',theme:'旅行交通'},
  {en:'holiday',zh:'假日; 假期',pos:'n.',theme:'旅行交通'},
  {en:'map',zh:'地图',pos:'n.',theme:'旅行交通'},
  {en:'north',zh:'北的; 朝北的; 从北来的',pos:'adj.',theme:'旅行交通'},
  {en:'passenger',zh:'乘客, 旅客',pos:'n.',theme:'旅行交通'},
  {en:'plane',zh:'飞机',pos:'n.',theme:'旅行交通'},
  {en:'ride',zh:'骑(马、自行车); 乘车',pos:'v.',theme:'旅行交通'},
  {en:'road',zh:'路, 道路',pos:'n.',theme:'旅行交通'},
  {en:'ship',zh:'船, 舰',pos:'n.',theme:'旅行交通'},
  {en:'south',zh:'南(方)的; 向南的; 从南来的',pos:'adj.',theme:'旅行交通'},
  {en:'station',zh:'站, 所, 车站; 电台',pos:'n.',theme:'旅行交通'},
  {en:'street',zh:'街, 街道',pos:'n.',theme:'旅行交通'},
  {en:'taxi',zh:'出租汽车',pos:'n.',theme:'旅行交通'},
  {en:'ticket',zh:'票; 卷',pos:'n.',theme:'旅行交通'},
  {en:'tour',zh:'参观, 观光, 旅行',pos:'n.',theme:'旅行交通'},
  {en:'train',zh:'火车',pos:'n.',theme:'旅行交通'},
  {en:'travel',zh:'旅行',pos:'n. & vi.',theme:'旅行交通'},
  {en:'trip',zh:'旅行, 旅程',pos:'n.',theme:'旅行交通'},
  {en:'vacation',zh:'假期, 休假',pos:'n.',theme:'旅行交通'},
  {en:'visit',zh:'参观, 访问, 拜访',pos:'n. & vt.',theme:'旅行交通'},
  {en:'west',zh:'(在)西的, 向西的, 从西来的',pos:'adj.',theme:'旅行交通'},
  {en:'bathroom',zh:'浴室',pos:'n.',theme:'日常生活'},
  {en:'bed',zh:'床',pos:'n.',theme:'日常生活'},
  {en:'bedroom',zh:'寝室, 卧室',pos:'n.',theme:'日常生活'},
  {en:'beef',zh:'牛肉 撕开',pos:'n.',theme:'日常生活'},
  {en:'bottle',zh:'瓶子',pos:'n.',theme:'日常生活'},
  {en:'bowl',zh:'碗',pos:'n.',theme:'日常生活'},
  {en:'bread',zh:'面包; 食物, 粮食; 生计',pos:'n.',theme:'日常生活'},
  {en:'breakfast',zh:'早餐',pos:'n.',theme:'日常生活'},
  {en:'brush',zh:'刷; 擦',pos:'v.',theme:'日常生活'},
  {en:'cake',zh:'蛋糕; 糕点; 饼',pos:'n.',theme:'日常生活'},
  {en:'chair',zh:'椅子',pos:'n.',theme:'日常生活'},
  {en:'chicken',zh:'鸡; 鸡肉',pos:'n.',theme:'日常生活'},
  {en:'clothes',zh:'衣服; 各种衣物',pos:'n.',theme:'日常生活'},
  {en:'coat',zh:'外套; 涂层; 表皮; 皮毛',pos:'n.',theme:'日常生活'},
  {en:'coffee',zh:'咖啡',pos:'n.',theme:'日常生活'},
  {en:'cook',zh:'炊事员, 厨师',pos:'n.',theme:'日常生活'},
  {en:'cup',zh:'茶杯',pos:'n.',theme:'日常生活'},
  {en:'desk',zh:'书桌, 写字台',pos:'n.',theme:'日常生活'},
  {en:'dinner',zh:'正餐, 宴会',pos:'n.',theme:'日常生活'},
  {en:'door',zh:'门',pos:'n.',theme:'日常生活'},
  {en:'dress',zh:'女服, 连衣裙; (统指)服装; 童装',pos:'n.',theme:'日常生活'},
  {en:'egg',zh:'蛋; 卵',pos:'n.',theme:'日常生活'},
  {en:'fish',zh:'鱼; 鱼肉',pos:'n.',theme:'日常生活'},
  {en:'floor',zh:'地面, 地板; (楼房的)层',pos:'n.',theme:'日常生活'},
  {en:'food',zh:'食物, 食品',pos:'n.',theme:'日常生活'},
  {en:'fork',zh:'叉, 餐叉',pos:'n.',theme:'日常生活'},
  {en:'furniture',zh:'(总称)家具',pos:'n.',theme:'日常生活'},
  {en:'garden',zh:'花园, 果园, 菜园',pos:'n.',theme:'日常生活'},
  {en:'glass',zh:'玻璃杯; 玻璃; (复)眼镜',pos:'n.',theme:'日常生活'},
  {en:'hat',zh:'帽子(一般指有边的); 礼帽',pos:'n.',theme:'日常生活'},
  {en:'home',zh:'家; 家; 回家',pos:'n. & adv.',theme:'日常生活'},
  {en:'house',zh:'房子; 住宅',pos:'n.',theme:'日常生活'},
  {en:'jacket',zh:'短上衣, 夹克衫',pos:'n.',theme:'日常生活'},
  {en:'juice',zh:'汁; 液',pos:'n.',theme:'日常生活'},
  {en:'key',zh:'钥匙; 答案; 键; 关键',pos:'n.',theme:'日常生活'},
  {en:'kitchen',zh:'厨房',pos:'n.',theme:'日常生活'},
  {en:'knife',zh:'小刀; 匕首; 刀片',pos:'n.',theme:'日常生活'},
  {en:'lunch',zh:'午餐, 午饭',pos:'n.',theme:'日常生活'},
  {en:'meal',zh:'一餐(饭)',pos:'n.',theme:'日常生活'},
  {en:'meat',zh:'(猪、牛、羊等的)肉',pos:'n.',theme:'日常生活'},
  {en:'milk',zh:'牛奶',pos:'n.',theme:'日常生活'},
  {en:'noodle',zh:'面条',pos:'n.',theme:'日常生活'},
  {en:'plate',zh:'板; 片; 牌; 盘子; 盆子',pos:'n.',theme:'日常生活'},
  {en:'pork',zh:'猪肉',pos:'n.',theme:'日常生活'},
  {en:'rice',zh:'稻米; 米饭',pos:'n.',theme:'日常生活'},
  {en:'room',zh:'房间, 室; 空间; 地方',pos:'n.',theme:'日常生活'},
  {en:'salt',zh:'盐',pos:'n.',theme:'日常生活'},
  {en:'shirt',zh:'男衬衫',pos:'n.',theme:'日常生活'},
  {en:'shoe',zh:'鞋',pos:'n.',theme:'日常生活'},
  {en:'sleep',zh:'睡觉',pos:'vi.',theme:'日常生活'},
  {en:'sock',zh:'短袜',pos:'n.',theme:'日常生活'},
  {en:'sofa',zh:'(长)沙发',pos:'adj.',theme:'日常生活'},
  {en:'spoon',zh:'匙, 调羹',pos:'n.',theme:'日常生活'},
  {en:'sugar',zh:'糖',pos:'n.',theme:'日常生活'},
  {en:'table',zh:'桌子, 表格',pos:'n.',theme:'日常生活'},
  {en:'tea',zh:'茶; 茶叶',pos:'n.',theme:'日常生活'},
  {en:'wake',zh:'醒, 醒来, 叫醒',pos:'v.',theme:'日常生活'},
  {en:'wall',zh:'墙',pos:'n.',theme:'日常生活'},
  {en:'wash',zh:'洗(涤), 冲洗',pos:'v.',theme:'日常生活'},
  {en:'water',zh:'水',pos:'n.',theme:'日常生活'},
  {en:'wear',zh:'穿, 戴',pos:'v.',theme:'日常生活'},
  {en:'window',zh:'窗户',pos:'n.',theme:'日常生活'},
  {en:'after',zh:'在后; 后来',pos:'adv.',theme:'时间与数量'},
  {en:'afternoon',zh:'下午, 午后',pos:'n.',theme:'时间与数量'},
  {en:'ago',zh:'以前',pos:'adv.',theme:'时间与数量'},
  {en:'all',zh:'全部地',pos:'adv.',theme:'时间与数量'},
  {en:'already',zh:'已经',pos:'adv.',theme:'时间与数量'},
  {en:'always',zh:'总是; 一直; 永远',pos:'adv.',theme:'时间与数量'},
  {en:'before',zh:'在……以前; 在……前面',pos:'prep.',theme:'时间与数量'},
  {en:'both',zh:'两; 双',pos:'adj.',theme:'时间与数量'},
  {en:'century',zh:'世纪, 百年',pos:'n.',theme:'时间与数量'},
  {en:'double',zh:'两倍的; 双的',pos:'adj.',theme:'时间与数量'},
  {en:'dozen',zh:'十二个; 一打',pos:'n.',theme:'时间与数量'},
  {en:'during',zh:'在……期问',pos:'prep.',theme:'时间与数量'},
  {en:'each',zh:'每人, 每个, 每件',pos:'adj. & pron.',theme:'时间与数量'},
  {en:'early',zh:'早的',pos:'adj.',theme:'时间与数量'},
  {en:'either',zh:'两方任一方的; 二者之一',pos:'adj.',theme:'时间与数量'},
  {en:'enough',zh:'足够的; 充分的',pos:'adj.',theme:'时间与数量'},
  {en:'evening',zh:'傍晚, 晚上',pos:'n.',theme:'时间与数量'},
  {en:'ever',zh:'曾经; 无论何时',pos:'adv.',theme:'时间与数量'},
  {en:'every',zh:'每一, 每个的',pos:'adv.',theme:'时间与数量'},
  {en:'few',zh:'不多, 少数; 不多的, 少数的',pos:'pron.',theme:'时间与数量'},
  {en:'first',zh:'第一',pos:'num.',theme:'时间与数量'},
  {en:'half',zh:'半, 一半, 半个',pos:'adj. & n.',theme:'时间与数量'},
  {en:'hour',zh:'小时',pos:'n.',theme:'时间与数量'},
  {en:'hundred',zh:'百',pos:'num.',theme:'时间与数量'},
  {en:'last',zh:'最近刚过去的; 最后的',pos:'adj.',theme:'时间与数量'},
  {en:'late',zh:'晚的, 迟的',pos:'adj.',theme:'时间与数量'},
  {en:'least',zh:'最少, 最少量',pos:'n.',theme:'时间与数量'},
  {en:'many',zh:'许多人(事)',pos:'pron.',theme:'时间与数量'},
  {en:'minute',zh:'分钟; 一会儿, 瞬间',pos:'n.',theme:'时间与数量'},
  {en:'moment',zh:'片刻, 瞬间',pos:'n.',theme:'时间与数量'},
  {en:'month',zh:'月, 月份',pos:'n.',theme:'时间与数量'},
  {en:'more',zh:'另',pos:'adj. & adv.',theme:'时间与数量'},
  {en:'morning',zh:'早晨, 上午',pos:'n.',theme:'时间与数量'},
  {en:'much',zh:'许多的, 大量的',pos:'adj.',theme:'时间与数量'},
  {en:'neither',zh:'(两者)都不; 也不',pos:'adj.',theme:'时间与数量'},
  {en:'never',zh:'决不, 从来没有',pos:'adv.',theme:'时间与数量'},
  {en:'next',zh:'最近的; 紧挨着的, 隔壁的; 下一次',pos:'adj.',theme:'时间与数量'},
  {en:'night',zh:'夜; 夜间',pos:'n.',theme:'时间与数量'},
  {en:'none',zh:'无任何东西或人, 无一人',pos:'pron.',theme:'时间与数量'},
  {en:'number',zh:'数, 数字, 号码; 数量',pos:'n.',theme:'时间与数量'},
  {en:'often',zh:'经常, 常常',pos:'adv.',theme:'时间与数量'},
  {en:'once',zh:'一度, 从前',pos:'adv.',theme:'时间与数量'},
  {en:'pair',zh:'一双, 一对',pos:'n.',theme:'时间与数量'},
  {en:'quarter',zh:'四分之一, 一刻钟',pos:'n.',theme:'时间与数量'},
  {en:'second',zh:'秒',pos:'n.',theme:'时间与数量'},
  {en:'seldom',zh:'很少, 不常',pos:'adv.',theme:'时间与数量'},
  {en:'several',zh:'几个, 数个',pos:'pron.',theme:'时间与数量'},
  {en:'since',zh:'从那时以来',pos:'adv.',theme:'时间与数量'},
  {en:'sometimes',zh:'有时',pos:'adv.',theme:'时间与数量'},
  {en:'soon',zh:'不久, 很快, 一会儿',pos:'adv.',theme:'时间与数量'},
  {en:'still',zh:'仍然, 还',pos:'adv.',theme:'时间与数量'},
  {en:'third',zh:'第三',pos:'num.',theme:'时间与数量'},
  {en:'thousand',zh:'千',pos:'num.',theme:'时间与数量'},
  {en:'time',zh:'时间; 时期; 钟点; 次, 回',pos:'n.',theme:'时间与数量'},
  {en:'today',zh:'今天; 现在, 当前',pos:'adv. & n.',theme:'时间与数量'},
  {en:'tomorrow',zh:'明天',pos:'adv. & n.',theme:'时间与数量'},
  {en:'total',zh:'总数的; 总括的; 完全的, 全然',pos:'adj.',theme:'时间与数量'},
  {en:'twice',zh:'两次; 两倍',pos:'adv.',theme:'时间与数量'},
  {en:'until',zh:'直到……为止',pos:'prep. & conj.',theme:'时间与数量'},
  {en:'week',zh:'星期, 周',pos:'n.',theme:'时间与数量'},
  {en:'whole',zh:'整个的; 全部的',pos:'adj.',theme:'时间与数量'},
  {en:'year',zh:'年',pos:'n.',theme:'时间与数量'},
  {en:'yesterday',zh:'昨天',pos:'n. & adv.',theme:'时间与数量'},
  {en:'yet',zh:'尚, 还, 仍然',pos:'adv.',theme:'时间与数量'},
  {en:'zero',zh:'零; 零度; 零点',pos:'n. & num.',theme:'时间与数量'},
  {en:'army',zh:'军队',pos:'n.',theme:'社区与社会'},
  {en:'city',zh:'市, 城市, 都市',pos:'n.',theme:'社区与社会'},
  {en:'country',zh:'国家; 农村, 乡下',pos:'n.',theme:'社区与社会'},
  {en:'culture',zh:'文化',pos:'n.',theme:'社区与社会'},
  {en:'government',zh:'政府',pos:'n.',theme:'社区与社会'},
  {en:'law',zh:'法律; 法令; 定律',pos:'n.',theme:'社区与社会'},
  {en:'magazine',zh:'杂志',pos:'n.',theme:'社区与社会'},
  {en:'meeting',zh:'会; 集会; 会见; 汇合点',pos:'n.',theme:'社区与社会'},
  {en:'news',zh:'新闻, 消息',pos:'n.',theme:'社区与社会'},
  {en:'newspaper',zh:'报纸',pos:'n.',theme:'社区与社会'},
  {en:'party',zh:'聚会, 晚会; 党派',pos:'n.',theme:'社区与社会'},
  {en:'peace',zh:'和平',pos:'n.',theme:'社区与社会'},
  {en:'people',zh:'人, 人们; 人民 通俗的',pos:'n.',theme:'社区与社会'},
  {en:'police',zh:'警察, 警务人员',pos:'n.',theme:'社区与社会'},
  {en:'population',zh:'人口, 人数',pos:'n.',theme:'社区与社会'},
  {en:'public',zh:'公共的; 公众的',pos:'adj.',theme:'社区与社会'},
  {en:'radio',zh:'无线电, 收音机',pos:'n.',theme:'社区与社会'},
  {en:'report',zh:'报道, 报告',pos:'n. & v.',theme:'社区与社会'},
  {en:'rule',zh:'规则, 规定',pos:'n.',theme:'社区与社会'},
  {en:'safety',zh:'安全, 保险',pos:'n.',theme:'社区与社会'},
  {en:'society',zh:'社会',pos:'n.',theme:'社区与社会'},
  {en:'soldier',zh:'士兵, 战士 木棒(棍), 枝条',pos:'n.',theme:'社区与社会'},
  {en:'town',zh:'城镇; 城',pos:'n.',theme:'社区与社会'},
  {en:'village',zh:'村庄, 乡村',pos:'n.',theme:'社区与社会'},
  {en:'war',zh:'战争',pos:'n.',theme:'社区与社会'},
  {en:'world',zh:'世界',pos:'n.',theme:'社区与社会'},
  {en:'camera',zh:'照相机; 摄象机',pos:'n.',theme:'科技与未来'},
  {en:'computer',zh:'电子计算机',pos:'n.',theme:'科技与未来'},
  {en:'develop',zh:'(使)发展; (使)发达',pos:'v.',theme:'科技与未来'},
  {en:'discover',zh:'发现',pos:'vt.',theme:'科技与未来'},
  {en:'experiment',zh:'实验',pos:'n.',theme:'科技与未来'},
  {en:'information',zh:'信息',pos:'n.',theme:'科技与未来'},
  {en:'internet',zh:'互联网; 因特网',pos:'n.',theme:'科技与未来'},
  {en:'invention',zh:'发明, 创造',pos:'n.',theme:'科技与未来'},
  {en:'machine',zh:'机器',pos:'n.',theme:'科技与未来'},
  {en:'message',zh:'消息, 音信',pos:'n.',theme:'科技与未来'},
  {en:'research',zh:'研究; 调查',pos:'n.',theme:'科技与未来'},
  {en:'robot',zh:'机器人',pos:'n.',theme:'科技与未来'},
  {en:'scientist',zh:'科学家 该(',pos:'n.',theme:'科技与未来'},
  {en:'screen',zh:'幕, 荧光屏',pos:'n.',theme:'科技与未来'},
  {en:'space',zh:'空间',pos:'n.',theme:'科技与未来'},
  {en:'technology',zh:'技术 (通)过; 自始至终, 全部',pos:'n.',theme:'科技与未来'},
  {en:'telephone',zh:'打电话',pos:'v.',theme:'科技与未来'},
  {en:'video',zh:'录像, 视频',pos:'n.',theme:'科技与未来'},
  {en:'website',zh:'(互联网)网站',pos:'n.',theme:'科技与未来'},
  {en:'afford',zh:'负担的起(…的费用); 抽得出(时',pos:'vt.',theme:'职业与工作'},
  {en:'boss',zh:'领班; 老板',pos:'n.',theme:'职业与工作'},
  {en:'business',zh:'(本分)工作; 职业; 生意; 交易',pos:'n.',theme:'职业与工作'},
  {en:'cheap',zh:'便宜的, 贱',pos:'adj.',theme:'职业与工作'},
  {en:'company',zh:'公司',pos:'n.',theme:'职业与工作'},
  {en:'cost',zh:'值(多少钱); 花费',pos:'v.',theme:'职业与工作'},
  {en:'driver',zh:'司机, 驾驶员',pos:'n.',theme:'职业与工作'},
  {en:'duty',zh:'责任, 义务',pos:'n.',theme:'职业与工作'},
  {en:'engineer',zh:'工程师; 技师',pos:'n.',theme:'职业与工作'},
  {en:'expensive',zh:'昂贵的',pos:'adj.',theme:'职业与工作'},
  {en:'factory',zh:'工厂',pos:'n.',theme:'职业与工作'},
  {en:'free',zh:'自由的, 空闲的; 免费的',pos:'adj.',theme:'职业与工作'},
  {en:'hero',zh:'英雄; 勇士',pos:'n.',theme:'职业与工作'},
  {en:'industry',zh:'工业',pos:'n.',theme:'职业与工作'},
  {en:'job',zh:'(一份)工作',pos:'n.',theme:'职业与工作'},
  {en:'king',zh:'国王',pos:'n.',theme:'职业与工作'},
  {en:'leader',zh:'领袖; 领导人',pos:'n.',theme:'职业与工作'},
  {en:'manager',zh:'经理',pos:'n.',theme:'职业与工作'},
  {en:'market',zh:'市场, 集市 器',pos:'n.',theme:'职业与工作'},
  {en:'office',zh:'办公室',pos:'n.',theme:'职业与工作'},
  {en:'officer',zh:'军官; 公务员; 官',pos:'n.',theme:'职业与工作'},
  {en:'pay',zh:'付钱, 给……报酬',pos:'v.',theme:'职业与工作'},
  {en:'pilot',zh:'飞行员',pos:'n.',theme:'职业与工作'},
  {en:'poor',zh:'贫穷的; 可怜的; 不好的, 差的',pos:'adj.',theme:'职业与工作'},
  {en:'president',zh:'总统; 主席',pos:'n.',theme:'职业与工作'},
  {en:'price',zh:'价格, 价钱',pos:'n.',theme:'职业与工作'},
  {en:'queen',zh:'皇后; 女皇',pos:'n.',theme:'职业与工作'},
  {en:'rich',zh:'富裕的; 有钱的',pos:'adj.',theme:'职业与工作'},
  {en:'role',zh:'角色',pos:'n.',theme:'职业与工作'},
  {en:'sale',zh:'卖; 出售',pos:'n.',theme:'职业与工作'},
  {en:'save',zh:'救, 挽救, 节省',pos:'vt.',theme:'职业与工作'},
  {en:'servant',zh:'仆人, 佣人',pos:'n.',theme:'职业与工作'},
  {en:'service',zh:'服务',pos:'n.',theme:'职业与工作'},
  {en:'shop',zh:'买东西',pos:'vi.',theme:'职业与工作'},
  {en:'store',zh:'商店',pos:'n.',theme:'职业与工作'},
  {en:'task',zh:'任务, 工作',pos:'n.',theme:'职业与工作'},
  {en:'trade',zh:'贸易',pos:'n.',theme:'职业与工作'},
  {en:'value',zh:'价值, 益处',pos:'n.',theme:'职业与工作'},
  {en:'waste',zh:'浪费',pos:'n. & vt.',theme:'职业与工作'},
  {en:'work',zh:'工作, 劳动, 事情',pos:'n.',theme:'职业与工作'},
  {en:'worker',zh:'工人, 工作者',pos:'n.',theme:'职业与工作'},
  {en:'worth',zh:'有……的价值, 值得……的',pos:'adj.',theme:'职业与工作'},
  {en:'animal',zh:'动物',pos:'n.',theme:'自然与环境'},
  {en:'ant',zh:'蚂蚁',pos:'n.',theme:'自然与环境'},
  {en:'autumn',zh:'秋天, 秋季',pos:'n.',theme:'自然与环境'},
  {en:'bear',zh:'熊',pos:'n.',theme:'自然与环境'},
  {en:'bee',zh:'蜜蜂',pos:'n.',theme:'自然与环境'},
  {en:'bird',zh:'鸟',pos:'n.',theme:'自然与环境'},
  {en:'cat',zh:'猫',pos:'n.',theme:'自然与环境'},
  {en:'cloud',zh:'云; 云状物; 阴影',pos:'n.',theme:'自然与环境'},
  {en:'cow',zh:'母牛, 奶牛',pos:'n.',theme:'自然与环境'},
  {en:'dog',zh:'狗',pos:'n.',theme:'自然与环境'},
  {en:'duck',zh:'鸭子',pos:'n.',theme:'自然与环境'},
  {en:'earth',zh:'地球; 土, 泥; 大地',pos:'n.',theme:'自然与环境'},
  {en:'elephant',zh:'象',pos:'n.',theme:'自然与环境'},
  {en:'energy',zh:'精力; 能量',pos:'n.',theme:'自然与环境'},
  {en:'environment',zh:'环境',pos:'n.',theme:'自然与环境'},
  {en:'fall',zh:'落下; 降落; 倒',pos:'vi.',theme:'自然与环境'},
  {en:'farm',zh:'农场; 农庄 备…;适合…;因为…;在…的期间;对于…;对…来说',pos:'n.',theme:'自然与环境'},
  {en:'field',zh:'田地; 牧场; 场地',pos:'n.',theme:'自然与环境'},
  {en:'flower',zh:'花',pos:'n.',theme:'自然与环境'},
  {en:'forest',zh:'森林',pos:'n.',theme:'自然与环境'},
  {en:'grass',zh:'草; 草场; 牧草',pos:'n.',theme:'自然与环境'},
  {en:'hill',zh:'小山; 丘陵; 土堆; 斜坡',pos:'n.',theme:'自然与环境'},
  {en:'horse',zh:'马',pos:'n.',theme:'自然与环境'},
  {en:'island',zh:'岛',pos:'n.',theme:'自然与环境'},
  {en:'lake',zh:'湖',pos:'n.',theme:'自然与环境'},
  {en:'land',zh:'陆地; 土地',pos:'n.',theme:'自然与环境'},
  {en:'leaf',zh:'(树, 菜)叶',pos:'n.',theme:'自然与环境'},
  {en:'lion',zh:'狮子',pos:'n.',theme:'自然与环境'},
  {en:'monkey',zh:'猴子',pos:'n.',theme:'自然与环境'},
  {en:'moon',zh:'月球; 月光; 月状物',pos:'n.',theme:'自然与环境'},
  {en:'mountain',zh:'山, 山脉',pos:'n.',theme:'自然与环境'},
  {en:'mouse',zh:'鼠, 耗子; (计算机)鼠标',pos:'n.',theme:'自然与环境'},
  {en:'natural',zh:'自然的',pos:'adj.',theme:'自然与环境'},
  {en:'nature',zh:'自然, 性质, 种类',pos:'n.',theme:'自然与环境'},
  {en:'ocean',zh:'海洋',pos:'n.',theme:'自然与环境'},
  {en:'pig',zh:'猪',pos:'n.',theme:'自然与环境'},
  {en:'plant',zh:'种植, 播种',pos:'vt.',theme:'自然与环境'},
  {en:'rabbit',zh:'兔, 家兔',pos:'n.',theme:'自然与环境'},
  {en:'rain',zh:'雨, 雨水',pos:'n.',theme:'自然与环境'},
  {en:'river',zh:'江; 河; 水道; 巨流',pos:'n.',theme:'自然与环境'},
  {en:'sea',zh:'海, 海洋',pos:'n.',theme:'自然与环境'},
  {en:'season',zh:'季; 季节 出示; 显示',pos:'n.',theme:'自然与环境'},
  {en:'sheep',zh:'(绵)羊; 羊皮; 驯服者',pos:'n.',theme:'自然与环境'},
  {en:'sky',zh:'天; 天空',pos:'n.',theme:'自然与环境'},
  {en:'snake',zh:'蛇',pos:'n.',theme:'自然与环境'},
  {en:'snow',zh:'雪',pos:'n.',theme:'自然与环境'},
  {en:'spring',zh:'春天, 春季',pos:'n.',theme:'自然与环境'},
  {en:'star',zh:'星, 恒星',pos:'n.',theme:'自然与环境'},
  {en:'storm',zh:'风暴, 暴(风)雨',pos:'n.',theme:'自然与环境'},
  {en:'summer',zh:'夏天, 夏季',pos:'n.',theme:'自然与环境'},
  {en:'sun',zh:'太阳, 阳光',pos:'n.',theme:'自然与环境'},
  {en:'tiger',zh:'老虎',pos:'n.',theme:'自然与环境'},
  {en:'tree',zh:'树',pos:'n.',theme:'自然与环境'},
  {en:'weather',zh:'天气',pos:'n.',theme:'自然与环境'},
  {en:'wind',zh:'风',pos:'n.',theme:'自然与环境'},
  {en:'winter',zh:'冬天, 冬季',pos:'n.',theme:'自然与环境'},
  {en:'alive',zh:'活着的, 存在的',pos:'adj.',theme:'身体与健康'},
  {en:'arm',zh:'臂, 支架',pos:'n.',theme:'身体与健康'},
  {en:'blind',zh:'瞎的',pos:'n.',theme:'身体与健康'},
  {en:'body',zh:'身体',pos:'n.',theme:'身体与健康'},
  {en:'brain',zh:'脑子',pos:'n.',theme:'身体与健康'},
  {en:'cold',zh:'冷的, 寒的',pos:'adj.',theme:'身体与健康'},
  {en:'cough',zh:'咳嗽',pos:'n. & vi.',theme:'身体与健康'},
  {en:'dead',zh:'死的; 无生命的',pos:'adj.',theme:'身体与健康'},
  {en:'deaf',zh:'聋的',pos:'adj.',theme:'身体与健康'},
  {en:'death',zh:'死',pos:'n.',theme:'身体与健康'},
  {en:'die',zh:'死',pos:'v.',theme:'身体与健康'},
  {en:'doctor',zh:'医生, 大夫; 博士',pos:'n.',theme:'身体与健康'},
  {en:'ear',zh:'耳朵; 耳状物; 听力, 听觉',pos:'n.',theme:'身体与健康'},
  {en:'eye',zh:'眼睛',pos:'n.',theme:'身体与健康'},
  {en:'face',zh:'脸',pos:'n.',theme:'身体与健康'},
  {en:'fat',zh:'脂肪',pos:'n.',theme:'身体与健康'},
  {en:'fever',zh:'发烧; 发热',pos:'n.',theme:'身体与健康'},
  {en:'finger',zh:'手指',pos:'n.',theme:'身体与健康'},
  {en:'foot',zh:'足, 脚; 英尺',pos:'n.',theme:'身体与健康'},
  {en:'hair',zh:'头发',pos:'n.',theme:'身体与健康'},
  {en:'hand',zh:'手; 指针',pos:'n.',theme:'身体与健康'},
  {en:'head',zh:'头; 头脑(像); 才智; 首脑; 源头; 标题',pos:'n.',theme:'身体与健康'},
  {en:'health',zh:'健康, 卫生',pos:'n.',theme:'身体与健康'},
  {en:'healthy',zh:'健康的; 健壮的',pos:'adj.',theme:'身体与健康'},
  {en:'heart',zh:'心, 心脏; 纸牌中的红桃',pos:'n.',theme:'身体与健康'},
  {en:'hospital',zh:'医院',pos:'n.',theme:'身体与健康'},
  {en:'hurt',zh:'伤害, 受伤; 伤人感情',pos:'vt.',theme:'身体与健康'},
  {en:'ill',zh:'有病的; 不健康的',pos:'adj.',theme:'身体与健康'},
  {en:'knee',zh:'膝盖',pos:'n.',theme:'身体与健康'},
  {en:'leg',zh:'腿; 腿脚; 支柱',pos:'n.',theme:'身体与健康'},
  {en:'medicine',zh:'药',pos:'n.',theme:'身体与健康'},
  {en:'mouth',zh:'嘴, 口',pos:'n.',theme:'身体与健康'},
  {en:'neck',zh:'颈, 脖子',pos:'n.',theme:'身体与健康'},
  {en:'nose',zh:'鼻',pos:'n.',theme:'身体与健康'},
  {en:'nurse',zh:'护士; 保育员',pos:'n.',theme:'身体与健康'},
  {en:'patient',zh:'病人',pos:'n.',theme:'身体与健康'},
  {en:'short',zh:'短的; 矮的',pos:'adj.',theme:'身体与健康'},
  {en:'shoulder',zh:'肩膀; (道路的)路肩',pos:'n.',theme:'身体与健康'},
  {en:'sick',zh:'有病的, 患病的; (想)呕吐',pos:'adj.',theme:'身体与健康'},
  {en:'stomach',zh:'胃, 胃部',pos:'n.',theme:'身体与健康'},
  {en:'strong',zh:'强(壮)的; 坚固的; 强烈的; 坚强',pos:'adj.',theme:'身体与健康'},
  {en:'tall',zh:'高的',pos:'adj.',theme:'身体与健康'},
  {en:'thin',zh:'薄的; 瘦的; 稀的',pos:'adj.',theme:'身体与健康'},
  {en:'tooth',zh:'牙齿',pos:'n.',theme:'身体与健康'},
  {en:'weak',zh:'差的, 弱的, 淡的',pos:'adj.',theme:'身体与健康'},
  {en:'call',zh:'叫; 电话, 通话',pos:'n.',theme:'通讯与媒体'},
  {en:'letter',zh:'信; 字母',pos:'n.',theme:'通讯与媒体'},
  {en:'mail',zh:'邮政',pos:'n.',theme:'通讯与媒体'},
  {en:'post',zh:'投寄; 邮寄',pos:'v.',theme:'通讯与媒体'},
  {en:'receive',zh:'收到, 得到',pos:'v.',theme:'通讯与媒体'},
  {en:'reply',zh:'回答, 答复',pos:'n.',theme:'通讯与媒体'},
  {en:'search',zh:'搜寻, 搜查',pos:'n. & v.',theme:'通讯与媒体'},
  {en:'text',zh:'文本, 课文',pos:'n.',theme:'通讯与媒体'},
  {en:'apple',zh:'苹果',pos:'n.',theme:'饮食与烹饪'},
  {en:'banana',zh:'香蕉',pos:'n.',theme:'饮食与烹饪'},
  {en:'biscuit',zh:'饼干',pos:'n.',theme:'饮食与烹饪'},
  {en:'butter',zh:'黄油; 奶油',pos:'n.',theme:'饮食与烹饪'},
  {en:'candy',zh:'糖果',pos:'n.',theme:'饮食与烹饪'},
  {en:'cheese',zh:'奶酪',pos:'n.',theme:'饮食与烹饪'},
  {en:'chocolate',zh:'巧克力',pos:'n.',theme:'饮食与烹饪'},
  {en:'delicious',zh:'美味的, 可口的',pos:'adj.',theme:'饮食与烹饪'},
  {en:'drink',zh:'喝, 饮',pos:'v.',theme:'饮食与烹饪'},
  {en:'eat',zh:'吃',pos:'v.',theme:'饮食与烹饪'},
  {en:'fruit',zh:'水果; 果实',pos:'n.',theme:'饮食与烹饪'},
  {en:'grape',zh:'葡萄',pos:'n.',theme:'饮食与烹饪'},
  {en:'hamburger',zh:'汉堡包',pos:'n.',theme:'饮食与烹饪'},
  {en:'hungry',zh:'(饥)饿的',pos:'adj.',theme:'饮食与烹饪'},
  {en:'ice',zh:'冰',pos:'n.',theme:'饮食与烹饪'},
  {en:'menu',zh:'菜单',pos:'n.',theme:'饮食与烹饪'},
  {en:'oil',zh:'油',pos:'n.',theme:'饮食与烹饪'},
  {en:'orange',zh:'橘子, 橙子, 橘子汁',pos:'n.',theme:'饮食与烹饪'},
  {en:'pie',zh:'甜馅饼',pos:'n.',theme:'饮食与烹饪'},
  {en:'potato',zh:'土豆, 马铃薯',pos:'n.',theme:'饮食与烹饪'},
  {en:'restaurant',zh:'饭馆, 饭店',pos:'n.',theme:'饮食与烹饪'},
  {en:'salad',zh:'色拉(西餐中的一种凉拌菜); 沙律',pos:'n.',theme:'饮食与烹饪'},
  {en:'sandwich',zh:'三明治(夹心面包片)',pos:'n.',theme:'饮食与烹饪'},
  {en:'soup',zh:'汤 的',pos:'n.',theme:'饮食与烹饪'},
  {en:'sour',zh:'酸的',pos:'adj.',theme:'饮食与烹饪'},
  {en:'strawberry',zh:'草莓',pos:'n.',theme:'饮食与烹饪'},
  {en:'sweet',zh:'甜食; 蜜饯; 甜点; 糖果; 芳香',pos:'n.',theme:'饮食与烹饪'},
  {en:'thirsty',zh:'渴的',pos:'adj.',theme:'饮食与烹饪'},
  {en:'tomato',zh:'西红柿, 番茄',pos:'n.',theme:'饮食与烹饪'},
  {en:'vegetable',zh:'蔬菜',pos:'n.',theme:'饮食与烹饪'},
  {en:'about',zh:'大约; 到处; 四处',pos:'adv.',theme:'高频动词'},
  {en:'again',zh:'再一次; 再, 又',pos:'adv.',theme:'高频动词'},
  {en:'agree',zh:'同意; 应允',pos:'v.',theme:'高频动词'},
  {en:'almost',zh:'几乎, 差不多',pos:'adv.',theme:'高频动词'},
  {en:'along',zh:'向前; 和…在一起; 一',pos:'adv.',theme:'高频动词'},
  {en:'aloud',zh:'大声地',pos:'adv.',theme:'高频动词'},
  {en:'also',zh:'也',pos:'adv.',theme:'高频动词'},
  {en:'anyway',zh:'不管怎样',pos:'adv.',theme:'高频动词'},
  {en:'anywhere',zh:'任何地方',pos:'adv.',theme:'高频动词'},
  {en:'around',zh:'在周围; 在附近',pos:'adv.',theme:'高频动词'},
  {en:'as',zh:'像……一样; 如同; 因为',pos:'adv. & conj.',theme:'高频动词'},
  {en:'avoid',zh:'避免; 躲开; 逃避',pos:'v.',theme:'高频动词'},
  {en:'awake',zh:'唤醒; 醒着的',pos:'v.',theme:'高频动词'},
  {en:'away',zh:'离开; 原离',pos:'adv.',theme:'高频动词'},
  {en:'back',zh:'回(原处); 向后',pos:'adv.',theme:'高频动词'},
  {en:'be',zh:'是(原形), 成为',pos:'v.',theme:'高频动词'},
  {en:'beat',zh:'敲打; 跳动; 打赢',pos:'v.',theme:'高频动词'},
  {en:'become',zh:'变得; 成为',pos:'v.',theme:'高频动词'},
  {en:'believe',zh:'相信; 认为',pos:'v.',theme:'高频动词'},
  {en:'blow',zh:'吹; 刮风; 吹气',pos:'v.',theme:'高频动词'},
  {en:'borrow',zh:'(向别人)借用; 借',pos:'v.',theme:'高频动词'},
  {en:'burn',zh:'燃, 烧; 着火; 使烧',pos:'v.',theme:'高频动词'},
  {en:'cancel',zh:'取消',pos:'v.',theme:'高频动词'},
  {en:'cheat',zh:'骗取, 哄骗; 作弊',pos:'v.',theme:'高频动词'},
  {en:'clone',zh:'克隆(无性繁殖出来的有机体群)',pos:'v.',theme:'高频动词'},
  {en:'communicate',zh:'交际; 传达(感情, 信',pos:'v.',theme:'高频动词'},
  {en:'deal',zh:'量, 数额; 交易',pos:'v.',theme:'高频动词'},
  {en:'decide',zh:'决定; 下决心',pos:'v.',theme:'高频动词'},
  {en:'dig',zh:'挖(洞、沟等); 掘',pos:'v.',theme:'高频动词'},
  {en:'downstairs',zh:'在楼下; 到楼下',pos:'adv.',theme:'高频动词'},
  {en:'dry',zh:'使……干; 弄干',pos:'v.',theme:'高频动词'},
  {en:'else',zh:'别的, 其他的',pos:'adv.',theme:'高频动词'},
  {en:'especially',zh:'特别, 尤其',pos:'adv.',theme:'高频动词'},
  {en:'even',zh:'甚至, 连(……都); 更',pos:'adv.',theme:'高频动词'},
  {en:'everywhere',zh:'到处',pos:'adv.',theme:'高频动词'},
  {en:'fail',zh:'失败; 不及格; 衰退',pos:'v.',theme:'高频动词'},
  {en:'fight',zh:'打仗; 打架; 争论',pos:'v. & n.',theme:'高频动词'},
  {en:'forget',zh:'忘记; 忘掉',pos:'v.',theme:'高频动词'},
  {en:'forward',zh:'将来,今后; 向前,前进',pos:'adv.',theme:'高频动词'},
  {en:'hang',zh:'悬挂; 吊着; 把……吊起',pos:'v.',theme:'高频动词'},
  {en:'hardly',zh:'几乎不',pos:'adv.',theme:'高频动词'},
  {en:'here',zh:'这里, 在这里; 向这里',pos:'adv.',theme:'高频动词'},
  {en:'hide',zh:'把……藏起来; 隐藏',pos:'v.',theme:'高频动词'},
  {en:'hope',zh:'希望',pos:'n. & v.',theme:'高频动词'},
  {en:'how',zh:'怎样, 如何; 多少; 多么',pos:'adv.',theme:'高频动词'},
  {en:'however',zh:'可是; 然而; 尽管 熨烫',pos:'adv. & conj.',theme:'高频动词'},
  {en:'immediately',zh:'立即',pos:'adv.',theme:'高频动词'},
  {en:'increase',zh:'增加; 繁殖',pos:'v. & n.',theme:'高频动词'},
  {en:'influence',zh:'影响',pos:'n. & v.',theme:'高频动词'},
  {en:'instead',zh:'代替, 顶替',pos:'adv.',theme:'高频动词'},
  {en:'join',zh:'参加, 加入; 连接; 会合',pos:'v.',theme:'高频动词'},
  {en:'just',zh:'刚才; 恰好; 不过; 仅',pos:'adv.',theme:'高频动词'},
  {en:'kick',zh:'踢',pos:'v. & n.',theme:'高频动词'},
  {en:'kill',zh:'杀死, 弄死',pos:'v.',theme:'高频动词'},
  {en:'knock',zh:'敲; 打; 击',pos:'v. & n.',theme:'高频动词'},
  {en:'know',zh:'知道, 了解; 认识; 懂',pos:'v.',theme:'高频动词'},
  {en:'leave',zh:'离开; 把……留下, 剩下',pos:'v.',theme:'高频动词'},
  {en:'lift',zh:'举起; 抬起; (云、烟等)消散',pos:'v.',theme:'高频动词'},
  {en:'litter',zh:'乱丢杂物',pos:'v.',theme:'高频动词'},
  {en:'low',zh:'低; 矮',pos:'adj. & adv.',theme:'高频动词'},
  {en:'manage',zh:'管理; 设法',pos:'v.',theme:'高频动词'},
  {en:'marry',zh:'(使)成婚; 结婚',pos:'v.',theme:'高频动词'},
  {en:'maybe',zh:'可能, 大概, 也许',pos:'adv.',theme:'高频动词'},
  {en:'mend',zh:'修理, 修补',pos:'v.',theme:'高频动词'},
  {en:'must',zh:'必须, 应当; 必定是',pos:'modalv.',theme:'高频动词'},
  {en:'nearly',zh:'将近, 几乎',pos:'adv.',theme:'高频动词'},
  {en:'no',zh:'不, 不是',pos:'adv.',theme:'高频动词'},
  {en:'not',zh:'不, 没',pos:'adv.',theme:'高频动词'},
  {en:'now',zh:'现在',pos:'adv.',theme:'高频动词'},
  {en:'ok',zh:'(口语)好, 对, 不错',pos:'adv.',theme:'高频动词'},
  {en:'only',zh:'仅仅, 只, 才',pos:'adv.',theme:'高频动词'},
  {en:'out',zh:'外出, 在外; 向外; 熄',pos:'adv.',theme:'高频动词'},
  {en:'past',zh:'过',pos:'adv.',theme:'高频动词'},
  {en:'perhaps',zh:'可能, 或许',pos:'adv.',theme:'高频动词'},
  {en:'plan',zh:'计划, 打算',pos:'n. & v.',theme:'高频动词'},
  {en:'please',zh:'请; 使人高兴, 使人满意',pos:'v.',theme:'高频动词'},
  {en:'point',zh:'指, 指向',pos:'v.',theme:'高频动词'},
  {en:'practise',zh:'练习; 实践',pos:'v.',theme:'高频动词'},
  {en:'probably',zh:'很可能, 大概',pos:'adv.',theme:'高频动词'},
  {en:'quite',zh:'完全, 十分 正确地, 恰恰, 完全地',pos:'adv.',theme:'高频动词'},
  {en:'rather',zh:'相当, 宁可',pos:'adv.',theme:'高频动词'},
  {en:'reach',zh:'到达, 伸手(脚等)够到',pos:'v.',theme:'高频动词'},
  {en:'recite',zh:'背诵',pos:'v.',theme:'高频动词'},
  {en:'regard',zh:'把……看作 俄语',pos:'v.',theme:'高频动词'},
  {en:'relax',zh:'(使)放松, 轻松',pos:'v.',theme:'高频动词'},
  {en:'remember',zh:'记得, 想起',pos:'v.',theme:'高频动词'},
  {en:'repair',zh:'修理; 修补',pos:'n. & v.',theme:'高频动词'},
  {en:'return',zh:'归还, 回, 归',pos:'v.',theme:'高频动词'},
  {en:'ring',zh:'(钟、铃等)响; 打电话',pos:'v.',theme:'高频动词'},
  {en:'round',zh:'转过来',pos:'adv.',theme:'高频动词'},
  {en:'seem',zh:'似乎, 好像',pos:'v.',theme:'高频动词'},
  {en:'sell',zh:'卖, 售',pos:'v.',theme:'高频动词'},
  {en:'separate',zh:'使分开; 使分离',pos:'v.',theme:'高频动词'},
  {en:'shake',zh:'(使)摇动, 震动',pos:'v.',theme:'高频动词'},
  {en:'shine',zh:'发光; 照耀; 出',pos:'v.',theme:'高频动词'},
  {en:'shout',zh:'喊, 高声呼喊',pos:'n. & v.',theme:'高频动词'},
  {en:'showed',zh:'给…看',pos:'v.',theme:'高频动词'},
  {en:'slow',zh:'慢慢地, 缓慢地',pos:'adv.',theme:'高频动词'},
  {en:'so',zh:'如此, 这么, 非常; 同样',pos:'adv.',theme:'高频动词'},
  {en:'somewhere',zh:'在某处',pos:'adv.',theme:'高频动词'},
  {en:'spell',zh:'拼写',pos:'v.',theme:'高频动词'},
  {en:'spread',zh:'延伸; 展开',pos:'v.',theme:'高频动词'},
  {en:'such',zh:'那么',pos:'adv.',theme:'高频动词'},
  {en:'sweep',zh:'扫除, 扫',pos:'v.',theme:'高频动词'},
  {en:'teach',zh:'教书, 教',pos:'v.',theme:'高频动词'},
  {en:'then',zh:'当时, 那时; 然后; 那么(通常用于句',pos:'adv.',theme:'高频动词'},
  {en:'think',zh:'想; 认为; 考虑',pos:'v.',theme:'高频动词'},
  {en:'together',zh:'一起, 共同',pos:'adv.',theme:'高频动词'},
  {en:'tonight',zh:'今晚, 今夜',pos:'adv. & n.',theme:'高频动词'},
  {en:'too',zh:'也, 还; 又; 太, 过分; 很, 非常',pos:'adv.',theme:'高频动词'},
  {en:'up',zh:'向上; 在上方; 起来; 在……以上',pos:'adv.',theme:'高频动词'},
  {en:'upstairs',zh:'在楼上, 到楼上',pos:'adv.',theme:'高频动词'},
  {en:'very',zh:'很, 非常',pos:'adv.',theme:'高频动词'},
  {en:'want',zh:'想, 想要, 需要, 必要',pos:'v.',theme:'高频动词'},
  {en:'well',zh:'好',pos:'adv.',theme:'高频动词'},
  {en:'where',zh:'在哪里, 往哪里',pos:'adv.',theme:'高频动词'},
  {en:'why',zh:'为什么',pos:'adv. & int.',theme:'高频动词'},
  {en:'wonder',zh:'对……疑惑, 感到惊奇, 想知',pos:'v.',theme:'高频动词'},
  {en:'worry',zh:'烦恼, 担忧, 发怒, 困扰',pos:'v.',theme:'高频动词'},
  {en:'yes',zh:'是, 好, 同意',pos:'adv.',theme:'高频动词'},
  {en:'able',zh:'能够; 有能力的',pos:'adj.',theme:'高频形容词副词'},
  {en:'absent',zh:'缺席; 不在 国人',pos:'adj.',theme:'高频形容词副词'},
  {en:'active',zh:'积极的, 主动的',pos:'adj.',theme:'高频形容词副词'},
  {en:'alone',zh:'单独的, 孤独的',pos:'adj.',theme:'高频形容词副词'},
  {en:'american',zh:'美国人; 美国人的',pos:'adj.',theme:'高频形容词副词'},
  {en:'ancient',zh:'古代的;古老的',pos:'adj.',theme:'高频形容词副词'},
  {en:'another',zh:'再一; 另一; 别的; 不同的',pos:'adj.',theme:'高频形容词副词'},
  {en:'any',zh:'(无论)哪一个; 那些; 任何',pos:'pron. & adj.',theme:'高频形容词副词'},
  {en:'asian',zh:'亚洲的; 亚洲人的',pos:'adj.',theme:'高频形容词副词'},
  {en:'asleep',zh:'睡着的, 熟睡',pos:'adj.',theme:'高频形容词副词'},
  {en:'atlantic',zh:'大西洋(的)',pos:'n. & adj.',theme:'高频形容词副词'},
  {en:'australian',zh:'澳洲的; 澳大利亚的',pos:'adj.',theme:'高频形容词副词'},
  {en:'available',zh:'有用的; 有效',pos:'adj.',theme:'高频形容词副词'},
  {en:'bad',zh:'坏的; 有害的; 不利的',pos:'adj.',theme:'高频形容词副词'},
  {en:'basic',zh:'基本的',pos:'adj.',theme:'高频形容词副词'},
  {en:'beautiful',zh:'美丽的, 美观的',pos:'adj.',theme:'高频形容词副词'},
  {en:'big',zh:'大的',pos:'adj.',theme:'高频形容词副词'},
  {en:'bitter',zh:'有苦味的; 痛苦的; 难过的; 严酷',pos:'adj.',theme:'高频形容词副词'},
  {en:'blue',zh:'蓝色',pos:'adj.',theme:'高频形容词副词'},
  {en:'boring',zh:'乏味的; 无聊的',pos:'adj.',theme:'高频形容词副词'},
  {en:'born',zh:'出生',pos:'adj.',theme:'高频形容词副词'},
  {en:'bright',zh:'明亮的; 聪明的',pos:'adj.',theme:'高频形容词副词'},
  {en:'busy',zh:'忙(碌)的',pos:'adj.',theme:'高频形容词副词'},
  {en:'certain',zh:'确定的, 无疑的; 一定会……',pos:'adj.',theme:'高频形容词副词'},
  {en:'clear',zh:'清晰的; 明亮的; 清楚的',pos:'adj.',theme:'高频形容词副词'},
  {en:'cloudy',zh:'多云的, 阴天的',pos:'adj.',theme:'高频形容词副词'},
  {en:'comfortable',zh:'舒',pos:'adj.',theme:'高频形容词副词'},
  {en:'common',zh:'普通的, 一般的; 共有的',pos:'adj.',theme:'高频形容词副词'},
  {en:'cool',zh:'凉的, 凉爽的; 酷',pos:'adj.',theme:'高频形容词副词'},
  {en:'cruel',zh:'残酷的; 无情的',pos:'adj.',theme:'高频形容词副词'},
  {en:'daily',zh:'每日的; 日常的',pos:'adj.',theme:'高频形容词副词'},
  {en:'dangerous',zh:'危险的',pos:'adj.',theme:'高频形容词副词'},
  {en:'dark',zh:'黑暗; 暗处; 日暮;黑暗的; 暗淡的',pos:'adj.',theme:'高频形容词副词'},
  {en:'dear',zh:'亲爱的',pos:'adj.',theme:'高频形容词副词'},
  {en:'different',zh:'不同的, 有差异的',pos:'adj.',theme:'高频形容词副词'},
  {en:'difficult',zh:'难的; 艰难的; 不易相处的 在……过程中',pos:'adj.',theme:'高频形容词副词'},
  {en:'direct',zh:'直接的; 直达的; 直截了',pos:'adj.',theme:'高频形容词副词'},
  {en:'dirty',zh:'脏的',pos:'adj.',theme:'高频形容词副词'},
  {en:'easy',zh:'容易的; 不费力的',pos:'adj.',theme:'高频形容词副词'},
  {en:'elder',zh:'长者; 前辈',pos:'adj.',theme:'高频形容词副词'},
  {en:'electric',zh:'电的',pos:'adj.',theme:'高频形容词副词'},
  {en:'empty',zh:'敌人; 敌军',pos:'adj.',theme:'高频形容词副词'},
  {en:'european',zh:'欧洲的; 欧洲人的',pos:'adj. & n.',theme:'高频形容词副词'},
  {en:'everyday',zh:'每日的; 日常的',pos:'adj.',theme:'高频形容词副词'},
  {en:'excellent',zh:'极好的; 优秀的',pos:'adj.',theme:'高频形容词副词'},
  {en:'fair',zh:'公平的; 合理的',pos:'adj.',theme:'高频形容词副词'},
  {en:'famous',zh:'著名的 行',pos:'adj.',theme:'高频形容词副词'},
  {en:'fantastic',zh:'(口语)极好的; 很棒的; 美',pos:'adj.',theme:'高频形容词副词'},
  {en:'fast',zh:'快的, 迅速的; 紧密的',pos:'adj.',theme:'高频形容词副词'},
  {en:'favourite',zh:'最喜欢的',pos:'adj.',theme:'高频形容词副词'},
  {en:'final',zh:'最后的; 终极的',pos:'adj.',theme:'高频形容词副词'},
  {en:'fine',zh:'细的; 晴朗的; 美好的; (身体)健康的',pos:'adj.',theme:'高频形容词副词'},
  {en:'fit',zh:'健康的, 适合的',pos:'adj.',theme:'高频形容词副词'},
  {en:'fresh',zh:'新鲜的',pos:'adj.',theme:'高频形容词副词'},
  {en:'friendly',zh:'友好的',pos:'adj.',theme:'高频形容词副词'},
  {en:'front',zh:'前面的; 前部的; 前面; 前部',pos:'adj. & n.',theme:'高频形容词副词'},
  {en:'full',zh:'满的, 充满的; 完全的',pos:'adj.',theme:'高频形容词副词'},
  {en:'funny',zh:'有趣的, 滑稽可笑的',pos:'adj.',theme:'高频形容词副词'},
  {en:'general',zh:'大体的; 笼统的; 总的',pos:'adj.',theme:'高频形容词副词'},
  {en:'glad',zh:'高兴的; 乐意的',pos:'adj.',theme:'高频形容词副词'},
  {en:'golden',zh:'金(黄)色的',pos:'adj.',theme:'高频形容词副词'},
  {en:'good',zh:'好; 良好',pos:'adj.',theme:'高频形容词副词'},
  {en:'great',zh:'伟大的; 重要的; 好极了',pos:'adj.',theme:'高频形容词副词'},
  {en:'green',zh:'绿色的; 青的',pos:'adj.',theme:'高频形容词副词'},
  {en:'handsome',zh:'英俊的',pos:'adj.',theme:'高频形容词副词'},
  {en:'heavy',zh:'重的',pos:'adj.',theme:'高频形容词副词'},
  {en:'helpful',zh:'有帮助的, 有益的',pos:'adj.',theme:'高频形容词副词'},
  {en:'high',zh:'高的; 高度的',pos:'adj.',theme:'高频形容词副词'},
  {en:'hot',zh:'热的',pos:'adj.',theme:'高频形容词副词'},
  {en:'huge',zh:'巨大的, 庞大的',pos:'adj.',theme:'高频形容词副词'},
  {en:'human',zh:'人的, 人类的',pos:'adj.',theme:'高频形容词副词'},
  {en:'humorous',zh:'幽默的',pos:'adj.',theme:'高频形容词副词'},
  {en:'important',zh:'重要的',pos:'adj.',theme:'高频形容词副词'},
  {en:'indian',zh:'(美洲)印地安人的; 印度人的',pos:'adj.',theme:'高频形容词副词'},
  {en:'interesting',zh:'有趣的',pos:'adj.',theme:'高频形容词副词'},
  {en:'international',zh:'国际的',pos:'adj.',theme:'高频形容词副词'},
  {en:'japanese',zh:'日本的, 日本人的, 日语',pos:'adj.',theme:'高频形容词副词'},
  {en:'large',zh:'大的, 巨大的',pos:'adj.',theme:'高频形容词副词'},
  {en:'left',zh:'左边的',pos:'adj.',theme:'高频形容词副词'},
  {en:'little',zh:'小的, 少的',pos:'adj.',theme:'高频形容词副词'},
  {en:'lively',zh:'活泼的; 充满生气的',pos:'adj.',theme:'高频形容词副词'},
  {en:'long',zh:'长的, 远',pos:'adj.',theme:'高频形容词副词'},
  {en:'loud',zh:'大声的',pos:'adj.',theme:'高频形容词副词'},
  {en:'lovely',zh:'美好的; 可爱的',pos:'adj.',theme:'高频形容词副词'},
  {en:'lucky',zh:'运气好, 侥幸',pos:'adj.',theme:'高频形容词副词'},
  {en:'mad',zh:'发疯的; 生气的',pos:'adj.',theme:'高频形容词副词'},
  {en:'magic',zh:'有魔力的',pos:'adj.',theme:'高频形容词副词'},
  {en:'main',zh:'主要的',pos:'adj.',theme:'高频形容词副词'},
  {en:'medical',zh:'医学的, 医疗的',pos:'adj.',theme:'高频形容词副词'},
  {en:'middle',zh:'中间; 当中; 中级',pos:'adj. & n.',theme:'高频形容词副词'},
  {en:'modern',zh:'现代化的',pos:'adj.',theme:'高频形容词副词'},
  {en:'national',zh:'国家的, 全国性的, 民族的',pos:'adj.',theme:'高频形容词副词'},
  {en:'near',zh:'近的',pos:'adj.',theme:'高频形容词副词'},
  {en:'necessary',zh:'必需的, 必要',pos:'adj.',theme:'高频形容词副词'},
  {en:'new',zh:'新的; 新鲜的',pos:'adj.',theme:'高频形容词副词'},
  {en:'nice',zh:'令人愉快的; 好的, 漂亮的',pos:'adj.',theme:'高频形容词副词'},
  {en:'normal',zh:'正常的(状态) 外面',pos:'n. & adj.',theme:'高频形容词副词'},
  {en:'northern',zh:'北方的, 北部的',pos:'adj.',theme:'高频形容词副词'},
  {en:'old',zh:'老的, 旧的',pos:'adj.',theme:'高频形容词副词'},
  {en:'own',zh:'自己的',pos:'adj.',theme:'高频形容词副词'},
  {en:'pacific',zh:'太平洋的',pos:'adj.',theme:'高频形容词副词'},
  {en:'pale',zh:'苍白的; 灰白的',pos:'adj.',theme:'高频形容词副词'},
  {en:'perfect',zh:'完美的, 及好的 俗的',pos:'adj.',theme:'高频形容词副词'},
  {en:'personal',zh:'个人的, 私人的',pos:'adj.',theme:'高频形容词副词'},
  {en:'pink',zh:'粉红色的',pos:'adj.',theme:'高频形容词副词'},
  {en:'plain',zh:'家常的; 普通的',pos:'adj.',theme:'高频形容词副词'},
  {en:'pleasant',zh:'令人愉快的, 舒适的 进展',pos:'adj.',theme:'高频形容词副词'},
  {en:'popular',zh:'(口语)(音乐、艺术等)大众的,',pos:'adj.',theme:'高频形容词副词'},
  {en:'possible',zh:'可能的',pos:'adj.',theme:'高频形容词副词'},
  {en:'pretty',zh:'漂亮的, 俊俏的',pos:'adj.',theme:'高频形容词副词'},
  {en:'primary',zh:'初等的, 初级的',pos:'adj.',theme:'高频形容词副词'},
  {en:'private',zh:'私人的',pos:'adj.',theme:'高频形容词副词'},
  {en:'proper',zh:'恰当的, 合适的',pos:'adj.',theme:'高频形容词副词'},
  {en:'quick',zh:'快的, 敏捷的',pos:'adj.',theme:'高频形容词副词'},
  {en:'quiet',zh:'安静的, 寂静的',pos:'adj.',theme:'高频形容词副词'},
  {en:'rainy',zh:'下雨的; 多雨的',pos:'adj.',theme:'高频形容词副词'},
  {en:'rapid',zh:'快的, 迅速的',pos:'adj.',theme:'高频形容词副词'},
  {en:'ready',zh:'准备好的 着…',pos:'adj.',theme:'高频形容词副词'},
  {en:'real',zh:'真实的, 确实的',pos:'adj.',theme:'高频形容词副词'},
  {en:'recent',zh:'近来的, 最近的',pos:'adj.',theme:'高频形容词副词'},
  {en:'russian',zh:'俄国人的, 俄语的',pos:'adj.',theme:'高频形容词副词'},
  {en:'safe',zh:'安全的',pos:'adj.',theme:'高频形容词副词'},
  {en:'secret',zh:'秘密, 内情',pos:'adj.',theme:'高频形容词副词'},
  {en:'silent',zh:'无声的; 无对话的',pos:'adj.',theme:'高频形容词副词'},
  {en:'similar',zh:'相似的; 像',pos:'adj.',theme:'高频形容词副词'},
  {en:'simple',zh:'简单的; 简易的',pos:'adj.',theme:'高频形容词副词'},
  {en:'single',zh:'单一的, 单个的',pos:'adj.',theme:'高频形容词副词'},
  {en:'sleepy',zh:'想睡的; 困倦的; 瞌睡的',pos:'adj.',theme:'高频形容词副词'},
  {en:'small',zh:'小的, 少的',pos:'adj.',theme:'高频形容词副词'},
  {en:'smooth',zh:'光滑的; 平坦的',pos:'adj.',theme:'高频形容词副词'},
  {en:'snowy',zh:'雪(白)的; 下雪的; 多(积)雪的',pos:'adj.',theme:'高频形容词副词'},
  {en:'social',zh:'社会的; 社交的',pos:'adj.',theme:'高频形容词副词'},
  {en:'soft',zh:'软的; 柔软的',pos:'adj.',theme:'高频形容词副词'},
  {en:'solid',zh:'结实的; 固体的',pos:'adj.',theme:'高频形容词副词'},
  {en:'some',zh:'一些, 若干; 有些; 某一',pos:'adj.',theme:'高频形容词副词'},
  {en:'sorry',zh:'对不起, 抱歉; 难过的',pos:'adj.',theme:'高频形容词副词'},
  {en:'southern',zh:'南部的, 南方的',pos:'adj.',theme:'高频形容词副词'},
  {en:'special',zh:'特别的, 专门的',pos:'adj.',theme:'高频形容词副词'},
  {en:'standard',zh:'标准(的)',pos:'n. & adj.',theme:'高频形容词副词'},
  {en:'strange',zh:'奇怪的, 奇特的, 陌生的',pos:'adj.',theme:'高频形容词副词'},
  {en:'successful',zh:'成功的, 有成就的',pos:'adj.',theme:'高频形容词副词'},
  {en:'sudden',zh:'突然的',pos:'adj.',theme:'高频形容词副词'},
  {en:'sunny',zh:'晴朗的; 阳光充足的',pos:'adj.',theme:'高频形容词副词'},
  {en:'sure',zh:'确信, 肯定',pos:'adj.',theme:'高频形容词副词'},
  {en:'terrible',zh:'可怕的; 糟糕的',pos:'adj.',theme:'高频形容词副词'},
  {en:'that',zh:'那, 那个',pos:'adj. & pron.',theme:'高频形容词副词'},
  {en:'these',zh:'这些',pos:'adj. & pron.',theme:'高频形容词副词'},
  {en:'this',zh:'这, 这个',pos:'adj. & pron.',theme:'高频形容词副词'},
  {en:'those',zh:'那些',pos:'adj. & pron.',theme:'高频形容词副词'},
  {en:'tidy',zh:'整洁的, 干净的',pos:'adj.',theme:'高频形容词副词'},
  {en:'tiny',zh:'极小的, 微小的',pos:'adj.',theme:'高频形容词副词'},
  {en:'tired',zh:'疲劳的, 累的',pos:'adj.',theme:'高频形容词副词'},
  {en:'traditional',zh:'传统的',pos:'adj.',theme:'高频形容词副词'},
  {en:'true',zh:'真的, 真实的; 忠诚的',pos:'adj.',theme:'高频形容词副词'},
  {en:'ugly',zh:'丑陋的; 难看的',pos:'adj.',theme:'高频形容词副词'},
  {en:'underground',zh:'地下的',pos:'adj.',theme:'高频形容词副词'},
  {en:'used',zh:'用过的',pos:'adj.',theme:'高频形容词副词'},
  {en:'useful',zh:'有用的, 有益的',pos:'adj.',theme:'高频形容词副词'},
  {en:'useless',zh:'无用的',pos:'adj.',theme:'高频形容词副词'},
  {en:'usual',zh:'通常的, 平常的',pos:'adj.',theme:'高频形容词副词'},
  {en:'warm',zh:'暖和的, 温暖的, 热情的',pos:'adj.',theme:'高频形容词副词'},
  {en:'western',zh:'西方的, 西部的 官等)运转, 活动',pos:'adj.',theme:'高频形容词副词'},
  {en:'wet',zh:'湿的, 潮的, 多雨的',pos:'adj.',theme:'高频形容词副词'},
  {en:'white',zh:'白色的',pos:'adj.',theme:'高频形容词副词'},
  {en:'wide',zh:'宽阔的',pos:'adj.',theme:'高频形容词副词'},
  {en:'windy',zh:'有风的, 多风的',pos:'adj.',theme:'高频形容词副词'},
  {en:'wonderful',zh:'美妙的, 精彩的, 了不起',pos:'adj.',theme:'高频形容词副词'},
  {en:'wrong',zh:'错误的, 不正常的, 有毛病的',pos:'adj.',theme:'高频形容词副词'},
  {en:'young',zh:'年轻的',pos:'adj.',theme:'高频形容词副词'}
];